// Auth service: sign-in flows (Google OAuth + magic-link), JWT issuance,
// session management, step-up auth for privileged operations.
//
// Tokens follow the spec in docs/TECH.md:
//   * Access token: 15 min, RS256, contains user_id + active roles.
//   * Refresh token: 30 days, opaque, server-side rotation.

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=js"
// @generated from file iogrid/identity/v1/auth.proto (package iogrid.identity.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { User, UserRole } from "./identity_pbjs";
import { UUID } from "../../common/v1/types_pbjs";

/**
 * StepUpReason flags what the user is about to do — drives UX copy.
 *
 * @generated from enum iogrid.identity.v1.StepUpReason
 */
export enum StepUpReason {
  /**
   * @generated from enum value: STEP_UP_REASON_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STEP_UP_REASON_PAYOUT_CHANGE = 1;
   */
  PAYOUT_CHANGE = 1,

  /**
   * @generated from enum value: STEP_UP_REASON_IDENTITY_MERGE = 2;
   */
  IDENTITY_MERGE = 2,

  /**
   * @generated from enum value: STEP_UP_REASON_ACCOUNT_DELETE = 3;
   */
  ACCOUNT_DELETE = 3,

  /**
   * @generated from enum value: STEP_UP_REASON_API_KEY_ISSUE = 4;
   */
  API_KEY_ISSUE = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(StepUpReason)
proto3.util.setEnumType(StepUpReason, "iogrid.identity.v1.StepUpReason", [
  { no: 0, name: "STEP_UP_REASON_UNSPECIFIED" },
  { no: 1, name: "STEP_UP_REASON_PAYOUT_CHANGE" },
  { no: 2, name: "STEP_UP_REASON_IDENTITY_MERGE" },
  { no: 3, name: "STEP_UP_REASON_ACCOUNT_DELETE" },
  { no: 4, name: "STEP_UP_REASON_API_KEY_ISSUE" },
]);

/**
 * JwtClaims mirrors the RS256-signed access-token payload. Exposed in
 * proto so client SDKs can deserialize without parsing JWT manually.
 *
 * @generated from message iogrid.identity.v1.JwtClaims
 */
export class JwtClaims extends Message<JwtClaims> {
  /**
   * Subject = user UUID.
   *
   * @generated from field: string sub = 1;
   */
  sub = "";

  /**
   * Issuer, e.g. "https://api.iogrid.org/identity".
   *
   * @generated from field: string iss = 2;
   */
  iss = "";

  /**
   * Audience, e.g. ["gateway-bff", "proxy-gateway"].
   *
   * @generated from field: repeated string aud = 3;
   */
  aud: string[] = [];

  /**
   * Issued-at and expiration (matches RFC 7519 numeric date semantics).
   *
   * @generated from field: google.protobuf.Timestamp iat = 4;
   */
  iat?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp exp = 5;
   */
  exp?: Timestamp;

  /**
   * Roles snapshot at issuance time. Source of truth is still the User
   * record server-side — clients use this only for UI gating.
   *
   * @generated from field: repeated iogrid.identity.v1.UserRole roles = 6;
   */
  roles: UserRole[] = [];

  /**
   * Session id, opaque. Used for revocation.
   *
   * @generated from field: string sid = 7;
   */
  sid = "";

  /**
   * True when the underlying credential was minted in the last 5 minutes
   * and the request requires step-up authority.
   *
   * @generated from field: bool step_up = 8;
   */
  stepUp = false;

  constructor(data?: PartialMessage<JwtClaims>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.JwtClaims";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sub", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "iss", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "aud", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "iat", kind: "message", T: Timestamp },
    { no: 5, name: "exp", kind: "message", T: Timestamp },
    { no: 6, name: "roles", kind: "enum", T: proto3.getEnumType(UserRole), repeated: true },
    { no: 7, name: "sid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "step_up", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JwtClaims {
    return new JwtClaims().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JwtClaims {
    return new JwtClaims().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JwtClaims {
    return new JwtClaims().fromJsonString(jsonString, options);
  }

  static equals(a: JwtClaims | PlainMessage<JwtClaims> | undefined, b: JwtClaims | PlainMessage<JwtClaims> | undefined): boolean {
    return proto3.util.equals(JwtClaims, a, b);
  }
}

/**
 * Session is the server-side refresh-token record. Exposed so users can
 * see + revoke sessions from /account/sessions.
 *
 * @generated from message iogrid.identity.v1.Session
 */
export class Session extends Message<Session> {
  /**
   * @generated from field: iogrid.common.v1.UUID id = 1;
   */
  id?: UUID;

  /**
   * @generated from field: iogrid.common.v1.UUID user_id = 2;
   */
  userId?: UUID;

  /**
   * Human-readable user-agent string captured at sign-in.
   *
   * @generated from field: string user_agent = 3;
   */
  userAgent = "";

  /**
   * IP captured at sign-in (may be hashed at boundary in audit logs).
   *
   * @generated from field: string ip_address = 4;
   */
  ipAddress = "";

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp last_used_at = 6;
   */
  lastUsedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 7;
   */
  expiresAt?: Timestamp;

  constructor(data?: PartialMessage<Session>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.Session";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: UUID },
    { no: 2, name: "user_id", kind: "message", T: UUID },
    { no: 3, name: "user_agent", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "ip_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "created_at", kind: "message", T: Timestamp },
    { no: 6, name: "last_used_at", kind: "message", T: Timestamp },
    { no: 7, name: "expires_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Session {
    return new Session().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Session {
    return new Session().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Session {
    return new Session().fromJsonString(jsonString, options);
  }

  static equals(a: Session | PlainMessage<Session> | undefined, b: Session | PlainMessage<Session> | undefined): boolean {
    return proto3.util.equals(Session, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.StartGoogleSignInRequest
 */
export class StartGoogleSignInRequest extends Message<StartGoogleSignInRequest> {
  /**
   * URL the IdP should redirect to after Google completes. MUST be in
   * the server's allowlist.
   *
   * @generated from field: string return_to = 1;
   */
  returnTo = "";

  /**
   * PKCE code challenge (S256).
   *
   * @generated from field: string code_challenge = 2;
   */
  codeChallenge = "";

  constructor(data?: PartialMessage<StartGoogleSignInRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.StartGoogleSignInRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "return_to", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "code_challenge", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartGoogleSignInRequest {
    return new StartGoogleSignInRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartGoogleSignInRequest {
    return new StartGoogleSignInRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartGoogleSignInRequest {
    return new StartGoogleSignInRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StartGoogleSignInRequest | PlainMessage<StartGoogleSignInRequest> | undefined, b: StartGoogleSignInRequest | PlainMessage<StartGoogleSignInRequest> | undefined): boolean {
    return proto3.util.equals(StartGoogleSignInRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.StartGoogleSignInResponse
 */
export class StartGoogleSignInResponse extends Message<StartGoogleSignInResponse> {
  /**
   * Fully built Google authorize URL — client redirects the browser
   * here. The state parameter is server-signed.
   *
   * @generated from field: string authorize_url = 1;
   */
  authorizeUrl = "";

  /**
   * Opaque state token also embedded in the URL.
   *
   * @generated from field: string state = 2;
   */
  state = "";

  constructor(data?: PartialMessage<StartGoogleSignInResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.StartGoogleSignInResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "authorize_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartGoogleSignInResponse {
    return new StartGoogleSignInResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartGoogleSignInResponse {
    return new StartGoogleSignInResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartGoogleSignInResponse {
    return new StartGoogleSignInResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StartGoogleSignInResponse | PlainMessage<StartGoogleSignInResponse> | undefined, b: StartGoogleSignInResponse | PlainMessage<StartGoogleSignInResponse> | undefined): boolean {
    return proto3.util.equals(StartGoogleSignInResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.CompleteGoogleSignInRequest
 */
export class CompleteGoogleSignInRequest extends Message<CompleteGoogleSignInRequest> {
  /**
   * Authorization code returned by Google.
   *
   * @generated from field: string code = 1;
   */
  code = "";

  /**
   * The same state the server issued in StartGoogleSignIn.
   *
   * @generated from field: string state = 2;
   */
  state = "";

  /**
   * PKCE code verifier matching the prior challenge.
   *
   * @generated from field: string code_verifier = 3;
   */
  codeVerifier = "";

  constructor(data?: PartialMessage<CompleteGoogleSignInRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.CompleteGoogleSignInRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "code_verifier", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CompleteGoogleSignInRequest {
    return new CompleteGoogleSignInRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CompleteGoogleSignInRequest {
    return new CompleteGoogleSignInRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CompleteGoogleSignInRequest {
    return new CompleteGoogleSignInRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CompleteGoogleSignInRequest | PlainMessage<CompleteGoogleSignInRequest> | undefined, b: CompleteGoogleSignInRequest | PlainMessage<CompleteGoogleSignInRequest> | undefined): boolean {
    return proto3.util.equals(CompleteGoogleSignInRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.CompleteGoogleSignInResponse
 */
export class CompleteGoogleSignInResponse extends Message<CompleteGoogleSignInResponse> {
  /**
   * @generated from field: iogrid.identity.v1.AuthBundle bundle = 1;
   */
  bundle?: AuthBundle;

  /**
   * True iff this completion created a brand-new User (vs. signing in
   * to an existing one). UI surfaces a welcome step on first sign-in.
   *
   * @generated from field: bool new_user = 2;
   */
  newUser = false;

  /**
   * True iff this Google identifier was auto-merged into an existing
   * User by matching one of Google's verified-emails against an
   * existing magic-link identifier.
   *
   * @generated from field: bool merged = 3;
   */
  merged = false;

  constructor(data?: PartialMessage<CompleteGoogleSignInResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.CompleteGoogleSignInResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "bundle", kind: "message", T: AuthBundle },
    { no: 2, name: "new_user", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "merged", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CompleteGoogleSignInResponse {
    return new CompleteGoogleSignInResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CompleteGoogleSignInResponse {
    return new CompleteGoogleSignInResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CompleteGoogleSignInResponse {
    return new CompleteGoogleSignInResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CompleteGoogleSignInResponse | PlainMessage<CompleteGoogleSignInResponse> | undefined, b: CompleteGoogleSignInResponse | PlainMessage<CompleteGoogleSignInResponse> | undefined): boolean {
    return proto3.util.equals(CompleteGoogleSignInResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.RequestMagicLinkRequest
 */
export class RequestMagicLinkRequest extends Message<RequestMagicLinkRequest> {
  /**
   * Email to send the link to (MUST be syntactically valid).
   *
   * @generated from field: string email = 1;
   */
  email = "";

  /**
   * Optional post-auth return URL.
   *
   * @generated from field: string return_to = 2;
   */
  returnTo = "";

  constructor(data?: PartialMessage<RequestMagicLinkRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.RequestMagicLinkRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "return_to", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestMagicLinkRequest {
    return new RequestMagicLinkRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestMagicLinkRequest {
    return new RequestMagicLinkRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestMagicLinkRequest {
    return new RequestMagicLinkRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RequestMagicLinkRequest | PlainMessage<RequestMagicLinkRequest> | undefined, b: RequestMagicLinkRequest | PlainMessage<RequestMagicLinkRequest> | undefined): boolean {
    return proto3.util.equals(RequestMagicLinkRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.RequestMagicLinkResponse
 */
export class RequestMagicLinkResponse extends Message<RequestMagicLinkResponse> {
  /**
   * The link expires after this duration (UX surfaces "expires in 10m").
   *
   * @generated from field: google.protobuf.Duration expires_in = 1;
   */
  expiresIn?: Duration;

  /**
   * Always true when we accepted the request — but we DO NOT reveal
   * whether an account already exists for that email (anti-enumeration).
   *
   * @generated from field: bool accepted = 2;
   */
  accepted = false;

  constructor(data?: PartialMessage<RequestMagicLinkResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.RequestMagicLinkResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "expires_in", kind: "message", T: Duration },
    { no: 2, name: "accepted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestMagicLinkResponse {
    return new RequestMagicLinkResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestMagicLinkResponse {
    return new RequestMagicLinkResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestMagicLinkResponse {
    return new RequestMagicLinkResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RequestMagicLinkResponse | PlainMessage<RequestMagicLinkResponse> | undefined, b: RequestMagicLinkResponse | PlainMessage<RequestMagicLinkResponse> | undefined): boolean {
    return proto3.util.equals(RequestMagicLinkResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.CompleteMagicLinkRequest
 */
export class CompleteMagicLinkRequest extends Message<CompleteMagicLinkRequest> {
  /**
   * The single-use, signed token embedded in the emailed link.
   *
   * @generated from field: string token = 1;
   */
  token = "";

  constructor(data?: PartialMessage<CompleteMagicLinkRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.CompleteMagicLinkRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CompleteMagicLinkRequest {
    return new CompleteMagicLinkRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CompleteMagicLinkRequest {
    return new CompleteMagicLinkRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CompleteMagicLinkRequest {
    return new CompleteMagicLinkRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CompleteMagicLinkRequest | PlainMessage<CompleteMagicLinkRequest> | undefined, b: CompleteMagicLinkRequest | PlainMessage<CompleteMagicLinkRequest> | undefined): boolean {
    return proto3.util.equals(CompleteMagicLinkRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.CompleteMagicLinkResponse
 */
export class CompleteMagicLinkResponse extends Message<CompleteMagicLinkResponse> {
  /**
   * @generated from field: iogrid.identity.v1.AuthBundle bundle = 1;
   */
  bundle?: AuthBundle;

  /**
   * @generated from field: bool new_user = 2;
   */
  newUser = false;

  /**
   * True iff this magic-link was auto-merged into a Google-authenticated
   * account by matching Google's verified-emails list.
   *
   * @generated from field: bool merged = 3;
   */
  merged = false;

  constructor(data?: PartialMessage<CompleteMagicLinkResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.CompleteMagicLinkResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "bundle", kind: "message", T: AuthBundle },
    { no: 2, name: "new_user", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "merged", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CompleteMagicLinkResponse {
    return new CompleteMagicLinkResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CompleteMagicLinkResponse {
    return new CompleteMagicLinkResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CompleteMagicLinkResponse {
    return new CompleteMagicLinkResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CompleteMagicLinkResponse | PlainMessage<CompleteMagicLinkResponse> | undefined, b: CompleteMagicLinkResponse | PlainMessage<CompleteMagicLinkResponse> | undefined): boolean {
    return proto3.util.equals(CompleteMagicLinkResponse, a, b);
  }
}

/**
 * AuthBundle is what every successful sign-in flow returns. Clients
 * store the access token in memory (never localStorage) and the refresh
 * token in an httpOnly secure cookie.
 *
 * @generated from message iogrid.identity.v1.AuthBundle
 */
export class AuthBundle extends Message<AuthBundle> {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken = "";

  /**
   * @generated from field: google.protobuf.Timestamp access_token_expires_at = 2;
   */
  accessTokenExpiresAt?: Timestamp;

  /**
   * @generated from field: string refresh_token = 3;
   */
  refreshToken = "";

  /**
   * @generated from field: google.protobuf.Timestamp refresh_token_expires_at = 4;
   */
  refreshTokenExpiresAt?: Timestamp;

  /**
   * @generated from field: iogrid.identity.v1.User user = 5;
   */
  user?: User;

  constructor(data?: PartialMessage<AuthBundle>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.AuthBundle";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "access_token_expires_at", kind: "message", T: Timestamp },
    { no: 3, name: "refresh_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "refresh_token_expires_at", kind: "message", T: Timestamp },
    { no: 5, name: "user", kind: "message", T: User },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AuthBundle {
    return new AuthBundle().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AuthBundle {
    return new AuthBundle().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AuthBundle {
    return new AuthBundle().fromJsonString(jsonString, options);
  }

  static equals(a: AuthBundle | PlainMessage<AuthBundle> | undefined, b: AuthBundle | PlainMessage<AuthBundle> | undefined): boolean {
    return proto3.util.equals(AuthBundle, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.RefreshTokenRequest
 */
export class RefreshTokenRequest extends Message<RefreshTokenRequest> {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken = "";

  constructor(data?: PartialMessage<RefreshTokenRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.RefreshTokenRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "refresh_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshTokenRequest {
    return new RefreshTokenRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshTokenRequest {
    return new RefreshTokenRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshTokenRequest {
    return new RefreshTokenRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RefreshTokenRequest | PlainMessage<RefreshTokenRequest> | undefined, b: RefreshTokenRequest | PlainMessage<RefreshTokenRequest> | undefined): boolean {
    return proto3.util.equals(RefreshTokenRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.RefreshTokenResponse
 */
export class RefreshTokenResponse extends Message<RefreshTokenResponse> {
  /**
   * @generated from field: iogrid.identity.v1.AuthBundle bundle = 1;
   */
  bundle?: AuthBundle;

  constructor(data?: PartialMessage<RefreshTokenResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.RefreshTokenResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "bundle", kind: "message", T: AuthBundle },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshTokenResponse {
    return new RefreshTokenResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshTokenResponse {
    return new RefreshTokenResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshTokenResponse {
    return new RefreshTokenResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RefreshTokenResponse | PlainMessage<RefreshTokenResponse> | undefined, b: RefreshTokenResponse | PlainMessage<RefreshTokenResponse> | undefined): boolean {
    return proto3.util.equals(RefreshTokenResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.SignOutRequest
 */
export class SignOutRequest extends Message<SignOutRequest> {
  /**
   * The refresh token to revoke. Access token is not server-stateful.
   *
   * @generated from field: string refresh_token = 1;
   */
  refreshToken = "";

  constructor(data?: PartialMessage<SignOutRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.SignOutRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "refresh_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignOutRequest {
    return new SignOutRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignOutRequest {
    return new SignOutRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignOutRequest {
    return new SignOutRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SignOutRequest | PlainMessage<SignOutRequest> | undefined, b: SignOutRequest | PlainMessage<SignOutRequest> | undefined): boolean {
    return proto3.util.equals(SignOutRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.SignOutResponse
 */
export class SignOutResponse extends Message<SignOutResponse> {
  constructor(data?: PartialMessage<SignOutResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.SignOutResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignOutResponse {
    return new SignOutResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignOutResponse {
    return new SignOutResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignOutResponse {
    return new SignOutResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SignOutResponse | PlainMessage<SignOutResponse> | undefined, b: SignOutResponse | PlainMessage<SignOutResponse> | undefined): boolean {
    return proto3.util.equals(SignOutResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.ListSessionsRequest
 */
export class ListSessionsRequest extends Message<ListSessionsRequest> {
  constructor(data?: PartialMessage<ListSessionsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.ListSessionsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListSessionsRequest {
    return new ListSessionsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListSessionsRequest {
    return new ListSessionsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListSessionsRequest {
    return new ListSessionsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListSessionsRequest | PlainMessage<ListSessionsRequest> | undefined, b: ListSessionsRequest | PlainMessage<ListSessionsRequest> | undefined): boolean {
    return proto3.util.equals(ListSessionsRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.ListSessionsResponse
 */
export class ListSessionsResponse extends Message<ListSessionsResponse> {
  /**
   * @generated from field: repeated iogrid.identity.v1.Session sessions = 1;
   */
  sessions: Session[] = [];

  constructor(data?: PartialMessage<ListSessionsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.ListSessionsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sessions", kind: "message", T: Session, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListSessionsResponse {
    return new ListSessionsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListSessionsResponse {
    return new ListSessionsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListSessionsResponse {
    return new ListSessionsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListSessionsResponse | PlainMessage<ListSessionsResponse> | undefined, b: ListSessionsResponse | PlainMessage<ListSessionsResponse> | undefined): boolean {
    return proto3.util.equals(ListSessionsResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.RevokeSessionRequest
 */
export class RevokeSessionRequest extends Message<RevokeSessionRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID session_id = 1;
   */
  sessionId?: UUID;

  constructor(data?: PartialMessage<RevokeSessionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.RevokeSessionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_id", kind: "message", T: UUID },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RevokeSessionRequest {
    return new RevokeSessionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RevokeSessionRequest {
    return new RevokeSessionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RevokeSessionRequest {
    return new RevokeSessionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RevokeSessionRequest | PlainMessage<RevokeSessionRequest> | undefined, b: RevokeSessionRequest | PlainMessage<RevokeSessionRequest> | undefined): boolean {
    return proto3.util.equals(RevokeSessionRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.RevokeSessionResponse
 */
export class RevokeSessionResponse extends Message<RevokeSessionResponse> {
  constructor(data?: PartialMessage<RevokeSessionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.RevokeSessionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RevokeSessionResponse {
    return new RevokeSessionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RevokeSessionResponse {
    return new RevokeSessionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RevokeSessionResponse {
    return new RevokeSessionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RevokeSessionResponse | PlainMessage<RevokeSessionResponse> | undefined, b: RevokeSessionResponse | PlainMessage<RevokeSessionResponse> | undefined): boolean {
    return proto3.util.equals(RevokeSessionResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.RequestStepUpRequest
 */
export class RequestStepUpRequest extends Message<RequestStepUpRequest> {
  /**
   * @generated from field: iogrid.identity.v1.StepUpReason reason = 1;
   */
  reason = StepUpReason.UNSPECIFIED;

  constructor(data?: PartialMessage<RequestStepUpRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.RequestStepUpRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "reason", kind: "enum", T: proto3.getEnumType(StepUpReason) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestStepUpRequest {
    return new RequestStepUpRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestStepUpRequest {
    return new RequestStepUpRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestStepUpRequest {
    return new RequestStepUpRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RequestStepUpRequest | PlainMessage<RequestStepUpRequest> | undefined, b: RequestStepUpRequest | PlainMessage<RequestStepUpRequest> | undefined): boolean {
    return proto3.util.equals(RequestStepUpRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.RequestStepUpResponse
 */
export class RequestStepUpResponse extends Message<RequestStepUpResponse> {
  /**
   * Either an authorize_url (OAuth re-auth) or accepted=true (magic-link
   * re-sent). UI shows the appropriate flow.
   *
   * @generated from field: string authorize_url = 1;
   */
  authorizeUrl = "";

  /**
   * @generated from field: bool magic_link_sent = 2;
   */
  magicLinkSent = false;

  constructor(data?: PartialMessage<RequestStepUpResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.RequestStepUpResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "authorize_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "magic_link_sent", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestStepUpResponse {
    return new RequestStepUpResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestStepUpResponse {
    return new RequestStepUpResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestStepUpResponse {
    return new RequestStepUpResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RequestStepUpResponse | PlainMessage<RequestStepUpResponse> | undefined, b: RequestStepUpResponse | PlainMessage<RequestStepUpResponse> | undefined): boolean {
    return proto3.util.equals(RequestStepUpResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.CompleteStepUpRequest
 */
export class CompleteStepUpRequest extends Message<CompleteStepUpRequest> {
  /**
   * Same shape as the underlying flow's completion — exactly one set.
   *
   * @generated from field: string oauth_code = 1;
   */
  oauthCode = "";

  /**
   * @generated from field: string oauth_state = 2;
   */
  oauthState = "";

  /**
   * @generated from field: string magic_link_token = 3;
   */
  magicLinkToken = "";

  constructor(data?: PartialMessage<CompleteStepUpRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.CompleteStepUpRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "oauth_code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "oauth_state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "magic_link_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CompleteStepUpRequest {
    return new CompleteStepUpRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CompleteStepUpRequest {
    return new CompleteStepUpRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CompleteStepUpRequest {
    return new CompleteStepUpRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CompleteStepUpRequest | PlainMessage<CompleteStepUpRequest> | undefined, b: CompleteStepUpRequest | PlainMessage<CompleteStepUpRequest> | undefined): boolean {
    return proto3.util.equals(CompleteStepUpRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.CompleteStepUpResponse
 */
export class CompleteStepUpResponse extends Message<CompleteStepUpResponse> {
  /**
   * Short-lived (5 min) step-up token to pass to the privileged RPC.
   *
   * @generated from field: string step_up_token = 1;
   */
  stepUpToken = "";

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 2;
   */
  expiresAt?: Timestamp;

  constructor(data?: PartialMessage<CompleteStepUpResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.CompleteStepUpResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "step_up_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "expires_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CompleteStepUpResponse {
    return new CompleteStepUpResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CompleteStepUpResponse {
    return new CompleteStepUpResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CompleteStepUpResponse {
    return new CompleteStepUpResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CompleteStepUpResponse | PlainMessage<CompleteStepUpResponse> | undefined, b: CompleteStepUpResponse | PlainMessage<CompleteStepUpResponse> | undefined): boolean {
    return proto3.util.equals(CompleteStepUpResponse, a, b);
  }
}

