// Auth service: sign-in flows (Google OAuth + magic-link), JWT issuance,
// session management, step-up auth for privileged operations.
//
// Tokens follow the spec in docs/TECH.md:
//   * Access token: 15 min, RS256, contains user_id + active roles.
//   * Refresh token: 30 days, opaque, server-side rotation.

// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=js"
// @generated from file iogrid/identity/v1/auth.proto (package iogrid.identity.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AppleSignInRequest, AppleSignInResponse, CompleteGoogleSignInRequest, CompleteGoogleSignInResponse, CompleteMagicLinkRequest, CompleteMagicLinkResponse, CompleteSiwsBindingRequest, CompleteSiwsBindingResponse, CompleteStepUpRequest, CompleteStepUpResponse, ListBoundWalletsRequest, ListBoundWalletsResponse, ListSessionsRequest, ListSessionsResponse, RefreshTokenRequest, RefreshTokenResponse, RequestMagicLinkRequest, RequestMagicLinkResponse, RequestStepUpRequest, RequestStepUpResponse, RevokeSessionRequest, RevokeSessionResponse, SignOutRequest, SignOutResponse, StartGoogleSignInRequest, StartGoogleSignInResponse, StartSiwsBindingRequest, StartSiwsBindingResponse, UnbindWalletRequest, UnbindWalletResponse } from "./auth_pbjs";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * AuthService is the public face of identity-svc for sign-in flows and
 * session management. Wraps both Google OAuth and the magic-link flow.
 *
 * @generated from service iogrid.identity.v1.AuthService
 */
export const AuthService = {
  typeName: "iogrid.identity.v1.AuthService",
  methods: {
    /**
     * Google OAuth.
     *
     * @generated from rpc iogrid.identity.v1.AuthService.StartGoogleSignIn
     */
    startGoogleSignIn: {
      name: "StartGoogleSignIn",
      I: StartGoogleSignInRequest,
      O: StartGoogleSignInResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.identity.v1.AuthService.CompleteGoogleSignIn
     */
    completeGoogleSignIn: {
      name: "CompleteGoogleSignIn",
      I: CompleteGoogleSignInRequest,
      O: CompleteGoogleSignInResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Magic-link.
     *
     * @generated from rpc iogrid.identity.v1.AuthService.RequestMagicLink
     */
    requestMagicLink: {
      name: "RequestMagicLink",
      I: RequestMagicLinkRequest,
      O: RequestMagicLinkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.identity.v1.AuthService.CompleteMagicLink
     */
    completeMagicLink: {
      name: "CompleteMagicLink",
      I: CompleteMagicLinkRequest,
      O: CompleteMagicLinkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sign in with Apple (iOS native sheet → server-side JWT validation).
     *
     * @generated from rpc iogrid.identity.v1.AuthService.AppleSignIn
     */
    appleSignIn: {
      name: "AppleSignIn",
      I: AppleSignInRequest,
      O: AppleSignInResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Session lifecycle.
     *
     * @generated from rpc iogrid.identity.v1.AuthService.RefreshToken
     */
    refreshToken: {
      name: "RefreshToken",
      I: RefreshTokenRequest,
      O: RefreshTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.identity.v1.AuthService.SignOut
     */
    signOut: {
      name: "SignOut",
      I: SignOutRequest,
      O: SignOutResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.identity.v1.AuthService.ListSessions
     */
    listSessions: {
      name: "ListSessions",
      I: ListSessionsRequest,
      O: ListSessionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.identity.v1.AuthService.RevokeSession
     */
    revokeSession: {
      name: "RevokeSession",
      I: RevokeSessionRequest,
      O: RevokeSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Step-up authority for privileged operations.
     *
     * @generated from rpc iogrid.identity.v1.AuthService.RequestStepUp
     */
    requestStepUp: {
      name: "RequestStepUp",
      I: RequestStepUpRequest,
      O: RequestStepUpResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.identity.v1.AuthService.CompleteStepUp
     */
    completeStepUp: {
      name: "CompleteStepUp",
      I: CompleteStepUpRequest,
      O: CompleteStepUpResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sign-In-With-Solana wallet binding.
     *
     * @generated from rpc iogrid.identity.v1.AuthService.StartSiwsBinding
     */
    startSiwsBinding: {
      name: "StartSiwsBinding",
      I: StartSiwsBindingRequest,
      O: StartSiwsBindingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.identity.v1.AuthService.CompleteSiwsBinding
     */
    completeSiwsBinding: {
      name: "CompleteSiwsBinding",
      I: CompleteSiwsBindingRequest,
      O: CompleteSiwsBindingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.identity.v1.AuthService.ListBoundWallets
     */
    listBoundWallets: {
      name: "ListBoundWallets",
      I: ListBoundWalletsRequest,
      O: ListBoundWalletsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.identity.v1.AuthService.UnbindWallet
     */
    unbindWallet: {
      name: "UnbindWallet",
      I: UnbindWalletRequest,
      O: UnbindWalletResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

