// Identity service: canonical user records and bound identifiers (Google
// OAuth, magic-link, future Apple/GitHub). This service owns the
// `users` and `identifiers` tables in identity-svc's Postgres.

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=js"
// @generated from file iogrid/identity/v1/identity.proto (package iogrid.identity.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { PageRequest, PageResponse, UUID } from "../../common/v1/types_pbjs";

/**
 * IdentifierKind enumerates supported auth providers / mechanisms.
 *
 * IDENTIFIER_KIND_SOLANA represents a Sign-In-With-Solana wallet binding
 * where the user proved control of the address by signing a server-issued
 * challenge. The Identifier's subject holds the base58-encoded pubkey.
 *
 * @generated from enum iogrid.identity.v1.IdentifierKind
 */
export enum IdentifierKind {
  /**
   * @generated from enum value: IDENTIFIER_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: IDENTIFIER_KIND_GOOGLE = 1;
   */
  GOOGLE = 1,

  /**
   * @generated from enum value: IDENTIFIER_KIND_MAGIC_LINK = 2;
   */
  MAGIC_LINK = 2,

  /**
   * @generated from enum value: IDENTIFIER_KIND_APPLE = 3;
   */
  APPLE = 3,

  /**
   * @generated from enum value: IDENTIFIER_KIND_GITHUB = 4;
   */
  GITHUB = 4,

  /**
   * @generated from enum value: IDENTIFIER_KIND_SOLANA = 5;
   */
  SOLANA = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(IdentifierKind)
proto3.util.setEnumType(IdentifierKind, "iogrid.identity.v1.IdentifierKind", [
  { no: 0, name: "IDENTIFIER_KIND_UNSPECIFIED" },
  { no: 1, name: "IDENTIFIER_KIND_GOOGLE" },
  { no: 2, name: "IDENTIFIER_KIND_MAGIC_LINK" },
  { no: 3, name: "IDENTIFIER_KIND_APPLE" },
  { no: 4, name: "IDENTIFIER_KIND_GITHUB" },
  { no: 5, name: "IDENTIFIER_KIND_SOLANA" },
]);

/**
 * UserRole encodes the role(s) a user holds. A single user can be both
 * PROVIDER and CUSTOMER (and may also be STAFF). Roles drive route gating
 * in the management plane.
 *
 * @generated from enum iogrid.identity.v1.UserRole
 */
export enum UserRole {
  /**
   * @generated from enum value: USER_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: USER_ROLE_PROVIDER = 1;
   */
  PROVIDER = 1,

  /**
   * @generated from enum value: USER_ROLE_CUSTOMER = 2;
   */
  CUSTOMER = 2,

  /**
   * @generated from enum value: USER_ROLE_STAFF = 3;
   */
  STAFF = 3,

  /**
   * @generated from enum value: USER_ROLE_ADMIN = 4;
   */
  ADMIN = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(UserRole)
proto3.util.setEnumType(UserRole, "iogrid.identity.v1.UserRole", [
  { no: 0, name: "USER_ROLE_UNSPECIFIED" },
  { no: 1, name: "USER_ROLE_PROVIDER" },
  { no: 2, name: "USER_ROLE_CUSTOMER" },
  { no: 3, name: "USER_ROLE_STAFF" },
  { no: 4, name: "USER_ROLE_ADMIN" },
]);

/**
 * User is the canonical, immutable account record. Bound Identifiers
 * can come and go but a User exists for the life of the account.
 *
 * @generated from message iogrid.identity.v1.User
 */
export class User extends Message<User> {
  /**
   * @generated from field: iogrid.common.v1.UUID id = 1;
   */
  id?: UUID;

  /**
   * Primary display email. Always one of the verified emails attached
   * through Identifiers; chosen by the user.
   *
   * @generated from field: string primary_email = 2;
   */
  primaryEmail = "";

  /**
   * Human display name (may be empty for magic-link-only signups until
   * the user fills their profile).
   *
   * @generated from field: string display_name = 3;
   */
  displayName = "";

  /**
   * Avatar URL (may be empty).
   *
   * @generated from field: string picture_url = 4;
   */
  pictureUrl = "";

  /**
   * Set of roles the user currently holds.
   *
   * @generated from field: repeated iogrid.identity.v1.UserRole roles = 5;
   */
  roles: UserRole[] = [];

  /**
   * Audit timestamps.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 7;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp last_login_at = 8;
   */
  lastLoginAt?: Timestamp;

  /**
   * Soft-delete sentinel; null when active.
   *
   * @generated from field: google.protobuf.Timestamp deleted_at = 9;
   */
  deletedAt?: Timestamp;

  constructor(data?: PartialMessage<User>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.User";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: UUID },
    { no: 2, name: "primary_email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "picture_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "roles", kind: "enum", T: proto3.getEnumType(UserRole), repeated: true },
    { no: 6, name: "created_at", kind: "message", T: Timestamp },
    { no: 7, name: "updated_at", kind: "message", T: Timestamp },
    { no: 8, name: "last_login_at", kind: "message", T: Timestamp },
    { no: 9, name: "deleted_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): User {
    return new User().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): User {
    return new User().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): User {
    return new User().fromJsonString(jsonString, options);
  }

  static equals(a: User | PlainMessage<User> | undefined, b: User | PlainMessage<User> | undefined): boolean {
    return proto3.util.equals(User, a, b);
  }
}

/**
 * Identifier represents a single way the user can authenticate. A user
 * may have many identifiers; we auto-merge on verified-email match
 * (see auth.proto for the merge flow).
 *
 * @generated from message iogrid.identity.v1.Identifier
 */
export class Identifier extends Message<Identifier> {
  /**
   * @generated from field: iogrid.common.v1.UUID id = 1;
   */
  id?: UUID;

  /**
   * @generated from field: iogrid.common.v1.UUID user_id = 2;
   */
  userId?: UUID;

  /**
   * @generated from field: iogrid.identity.v1.IdentifierKind kind = 3;
   */
  kind = IdentifierKind.UNSPECIFIED;

  /**
   * For OAuth providers: the provider's stable subject id ("sub" in
   * OpenID Connect). For magic-link: empty.
   *
   * @generated from field: string subject = 4;
   */
  subject = "";

  /**
   * The verified email attached to this identifier (may be empty for
   * some non-email-based providers in the future).
   *
   * @generated from field: string verified_email = 5;
   */
  verifiedEmail = "";

  /**
   * For Google Workspace users: the `hd` claim — feeds enterprise
   * routing. Empty for consumer accounts.
   *
   * @generated from field: string hosted_domain = 6;
   */
  hostedDomain = "";

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp last_used_at = 8;
   */
  lastUsedAt?: Timestamp;

  constructor(data?: PartialMessage<Identifier>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.Identifier";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: UUID },
    { no: 2, name: "user_id", kind: "message", T: UUID },
    { no: 3, name: "kind", kind: "enum", T: proto3.getEnumType(IdentifierKind) },
    { no: 4, name: "subject", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "verified_email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "hosted_domain", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "created_at", kind: "message", T: Timestamp },
    { no: 8, name: "last_used_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Identifier {
    return new Identifier().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Identifier {
    return new Identifier().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Identifier {
    return new Identifier().fromJsonString(jsonString, options);
  }

  static equals(a: Identifier | PlainMessage<Identifier> | undefined, b: Identifier | PlainMessage<Identifier> | undefined): boolean {
    return proto3.util.equals(Identifier, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.GetUserRequest
 */
export class GetUserRequest extends Message<GetUserRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID id = 1;
   */
  id?: UUID;

  constructor(data?: PartialMessage<GetUserRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.GetUserRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: UUID },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserRequest {
    return new GetUserRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserRequest {
    return new GetUserRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserRequest {
    return new GetUserRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetUserRequest | PlainMessage<GetUserRequest> | undefined, b: GetUserRequest | PlainMessage<GetUserRequest> | undefined): boolean {
    return proto3.util.equals(GetUserRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.GetUserResponse
 */
export class GetUserResponse extends Message<GetUserResponse> {
  /**
   * @generated from field: iogrid.identity.v1.User user = 1;
   */
  user?: User;

  /**
   * All identifiers currently bound to this user.
   *
   * @generated from field: repeated iogrid.identity.v1.Identifier identifiers = 2;
   */
  identifiers: Identifier[] = [];

  constructor(data?: PartialMessage<GetUserResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.GetUserResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user", kind: "message", T: User },
    { no: 2, name: "identifiers", kind: "message", T: Identifier, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserResponse {
    return new GetUserResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserResponse {
    return new GetUserResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserResponse {
    return new GetUserResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetUserResponse | PlainMessage<GetUserResponse> | undefined, b: GetUserResponse | PlainMessage<GetUserResponse> | undefined): boolean {
    return proto3.util.equals(GetUserResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.ListUsersRequest
 */
export class ListUsersRequest extends Message<ListUsersRequest> {
  /**
   * @generated from field: iogrid.common.v1.PageRequest page = 1;
   */
  page?: PageRequest;

  /**
   * Optional filters. Empty = "no filter".
   *
   * @generated from field: iogrid.identity.v1.UserRole role_filter = 2;
   */
  roleFilter = UserRole.UNSPECIFIED;

  /**
   * @generated from field: string email_contains = 3;
   */
  emailContains = "";

  constructor(data?: PartialMessage<ListUsersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.ListUsersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page", kind: "message", T: PageRequest },
    { no: 2, name: "role_filter", kind: "enum", T: proto3.getEnumType(UserRole) },
    { no: 3, name: "email_contains", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListUsersRequest {
    return new ListUsersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListUsersRequest {
    return new ListUsersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListUsersRequest {
    return new ListUsersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListUsersRequest | PlainMessage<ListUsersRequest> | undefined, b: ListUsersRequest | PlainMessage<ListUsersRequest> | undefined): boolean {
    return proto3.util.equals(ListUsersRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.ListUsersResponse
 */
export class ListUsersResponse extends Message<ListUsersResponse> {
  /**
   * @generated from field: repeated iogrid.identity.v1.User users = 1;
   */
  users: User[] = [];

  /**
   * @generated from field: iogrid.common.v1.PageResponse page = 2;
   */
  page?: PageResponse;

  constructor(data?: PartialMessage<ListUsersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.ListUsersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "users", kind: "message", T: User, repeated: true },
    { no: 2, name: "page", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListUsersResponse {
    return new ListUsersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListUsersResponse {
    return new ListUsersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListUsersResponse {
    return new ListUsersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListUsersResponse | PlainMessage<ListUsersResponse> | undefined, b: ListUsersResponse | PlainMessage<ListUsersResponse> | undefined): boolean {
    return proto3.util.equals(ListUsersResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.UpdateUserRequest
 */
export class UpdateUserRequest extends Message<UpdateUserRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID id = 1;
   */
  id?: UUID;

  /**
   * Only the fields below are mutable via this RPC; other User fields
   * are managed implicitly (created_at, roles, login timestamps).
   *
   * @generated from field: string display_name = 2;
   */
  displayName = "";

  /**
   * @generated from field: string primary_email = 3;
   */
  primaryEmail = "";

  /**
   * @generated from field: string picture_url = 4;
   */
  pictureUrl = "";

  constructor(data?: PartialMessage<UpdateUserRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.UpdateUserRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: UUID },
    { no: 2, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "primary_email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "picture_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateUserRequest {
    return new UpdateUserRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateUserRequest {
    return new UpdateUserRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateUserRequest {
    return new UpdateUserRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateUserRequest | PlainMessage<UpdateUserRequest> | undefined, b: UpdateUserRequest | PlainMessage<UpdateUserRequest> | undefined): boolean {
    return proto3.util.equals(UpdateUserRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.UpdateUserResponse
 */
export class UpdateUserResponse extends Message<UpdateUserResponse> {
  /**
   * @generated from field: iogrid.identity.v1.User user = 1;
   */
  user?: User;

  constructor(data?: PartialMessage<UpdateUserResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.UpdateUserResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user", kind: "message", T: User },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateUserResponse {
    return new UpdateUserResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateUserResponse {
    return new UpdateUserResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateUserResponse {
    return new UpdateUserResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateUserResponse | PlainMessage<UpdateUserResponse> | undefined, b: UpdateUserResponse | PlainMessage<UpdateUserResponse> | undefined): boolean {
    return proto3.util.equals(UpdateUserResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.DeleteUserRequest
 */
export class DeleteUserRequest extends Message<DeleteUserRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID id = 1;
   */
  id?: UUID;

  /**
   * Caller MUST have a fresh step-up auth token (see auth.proto).
   *
   * @generated from field: string step_up_token = 2;
   */
  stepUpToken = "";

  constructor(data?: PartialMessage<DeleteUserRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.DeleteUserRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: UUID },
    { no: 2, name: "step_up_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteUserRequest {
    return new DeleteUserRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteUserRequest {
    return new DeleteUserRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteUserRequest {
    return new DeleteUserRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteUserRequest | PlainMessage<DeleteUserRequest> | undefined, b: DeleteUserRequest | PlainMessage<DeleteUserRequest> | undefined): boolean {
    return proto3.util.equals(DeleteUserRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.DeleteUserResponse
 */
export class DeleteUserResponse extends Message<DeleteUserResponse> {
  constructor(data?: PartialMessage<DeleteUserResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.DeleteUserResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteUserResponse {
    return new DeleteUserResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteUserResponse {
    return new DeleteUserResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteUserResponse {
    return new DeleteUserResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteUserResponse | PlainMessage<DeleteUserResponse> | undefined, b: DeleteUserResponse | PlainMessage<DeleteUserResponse> | undefined): boolean {
    return proto3.util.equals(DeleteUserResponse, a, b);
  }
}

/**
 * RemoveIdentifierRequest unbinds a single non-Solana identifier (Google,
 * magic-link email, future Apple/GitHub) from the user. Solana wallets are
 * removed via AuthService.UnbindWallet so the SIWS-specific audit trail is
 * preserved. The server refuses to remove the user's last verified
 * identifier — the account would become unrecoverable.
 *
 * @generated from message iogrid.identity.v1.RemoveIdentifierRequest
 */
export class RemoveIdentifierRequest extends Message<RemoveIdentifierRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID user_id = 1;
   */
  userId?: UUID;

  /**
   * @generated from field: iogrid.common.v1.UUID identifier_id = 2;
   */
  identifierId?: UUID;

  constructor(data?: PartialMessage<RemoveIdentifierRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.RemoveIdentifierRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "message", T: UUID },
    { no: 2, name: "identifier_id", kind: "message", T: UUID },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveIdentifierRequest {
    return new RemoveIdentifierRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveIdentifierRequest {
    return new RemoveIdentifierRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveIdentifierRequest {
    return new RemoveIdentifierRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RemoveIdentifierRequest | PlainMessage<RemoveIdentifierRequest> | undefined, b: RemoveIdentifierRequest | PlainMessage<RemoveIdentifierRequest> | undefined): boolean {
    return proto3.util.equals(RemoveIdentifierRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.RemoveIdentifierResponse
 */
export class RemoveIdentifierResponse extends Message<RemoveIdentifierResponse> {
  /**
   * Identifiers still bound to the user after removal — clients can
   * refresh their list view without a second round-trip.
   *
   * @generated from field: repeated iogrid.identity.v1.Identifier remaining = 1;
   */
  remaining: Identifier[] = [];

  constructor(data?: PartialMessage<RemoveIdentifierResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.RemoveIdentifierResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "remaining", kind: "message", T: Identifier, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveIdentifierResponse {
    return new RemoveIdentifierResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveIdentifierResponse {
    return new RemoveIdentifierResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveIdentifierResponse {
    return new RemoveIdentifierResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RemoveIdentifierResponse | PlainMessage<RemoveIdentifierResponse> | undefined, b: RemoveIdentifierResponse | PlainMessage<RemoveIdentifierResponse> | undefined): boolean {
    return proto3.util.equals(RemoveIdentifierResponse, a, b);
  }
}

/**
 * DeleteAccountRequest triggers the soft-delete cascade for the caller's
 * own account. The server:
 *   1. Flips users.deleted_at = now() (rows stay for audit references).
 *   2. Revokes every active session (refresh tokens become unusable).
 *   3. Hands a workspace-cascade notice to workloads-svc / providers-svc
 *      via the outbound events bus so downstream owners can purge.
 * The caller MUST present a valid bearer token AND a fresh step-up token
 * minted within the last five minutes via AuthService.RequestStepUp(
 * reason=STEP_UP_REASON_ACCOUNT_DELETE).
 *
 * @generated from message iogrid.identity.v1.DeleteAccountRequest
 */
export class DeleteAccountRequest extends Message<DeleteAccountRequest> {
  /**
   * Must equal the caller's user id; rejecting a mismatch keeps the
   * delete blast-radius scoped to the authed principal.
   *
   * @generated from field: iogrid.common.v1.UUID user_id = 1;
   */
  userId?: UUID;

  /**
   * @generated from field: string step_up_token = 2;
   */
  stepUpToken = "";

  /**
   * Free-form reason captured into the audit log. Optional.
   *
   * @generated from field: string reason = 3;
   */
  reason = "";

  constructor(data?: PartialMessage<DeleteAccountRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.DeleteAccountRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "message", T: UUID },
    { no: 2, name: "step_up_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteAccountRequest {
    return new DeleteAccountRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteAccountRequest {
    return new DeleteAccountRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteAccountRequest {
    return new DeleteAccountRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteAccountRequest | PlainMessage<DeleteAccountRequest> | undefined, b: DeleteAccountRequest | PlainMessage<DeleteAccountRequest> | undefined): boolean {
    return proto3.util.equals(DeleteAccountRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.DeleteAccountResponse
 */
export class DeleteAccountResponse extends Message<DeleteAccountResponse> {
  /**
   * Echo of the soft-delete timestamp written to users.deleted_at.
   *
   * @generated from field: google.protobuf.Timestamp deleted_at = 1;
   */
  deletedAt?: Timestamp;

  /**
   * Number of active sessions revoked as part of the cascade.
   *
   * @generated from field: uint32 sessions_revoked = 2;
   */
  sessionsRevoked = 0;

  constructor(data?: PartialMessage<DeleteAccountResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.DeleteAccountResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "deleted_at", kind: "message", T: Timestamp },
    { no: 2, name: "sessions_revoked", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteAccountResponse {
    return new DeleteAccountResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteAccountResponse {
    return new DeleteAccountResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteAccountResponse {
    return new DeleteAccountResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteAccountResponse | PlainMessage<DeleteAccountResponse> | undefined, b: DeleteAccountResponse | PlainMessage<DeleteAccountResponse> | undefined): boolean {
    return proto3.util.equals(DeleteAccountResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.MergeIdentitiesRequest
 */
export class MergeIdentitiesRequest extends Message<MergeIdentitiesRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID target_user_id = 1;
   */
  targetUserId?: UUID;

  /**
   * @generated from field: iogrid.common.v1.UUID source_user_id = 2;
   */
  sourceUserId?: UUID;

  /**
   * Fresh step-up token required.
   *
   * @generated from field: string step_up_token = 3;
   */
  stepUpToken = "";

  constructor(data?: PartialMessage<MergeIdentitiesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.MergeIdentitiesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "target_user_id", kind: "message", T: UUID },
    { no: 2, name: "source_user_id", kind: "message", T: UUID },
    { no: 3, name: "step_up_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MergeIdentitiesRequest {
    return new MergeIdentitiesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MergeIdentitiesRequest {
    return new MergeIdentitiesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MergeIdentitiesRequest {
    return new MergeIdentitiesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MergeIdentitiesRequest | PlainMessage<MergeIdentitiesRequest> | undefined, b: MergeIdentitiesRequest | PlainMessage<MergeIdentitiesRequest> | undefined): boolean {
    return proto3.util.equals(MergeIdentitiesRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.MergeIdentitiesResponse
 */
export class MergeIdentitiesResponse extends Message<MergeIdentitiesResponse> {
  /**
   * The surviving user after merge (always == target_user_id).
   *
   * @generated from field: iogrid.identity.v1.User user = 1;
   */
  user?: User;

  constructor(data?: PartialMessage<MergeIdentitiesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.MergeIdentitiesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user", kind: "message", T: User },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MergeIdentitiesResponse {
    return new MergeIdentitiesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MergeIdentitiesResponse {
    return new MergeIdentitiesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MergeIdentitiesResponse {
    return new MergeIdentitiesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MergeIdentitiesResponse | PlainMessage<MergeIdentitiesResponse> | undefined, b: MergeIdentitiesResponse | PlainMessage<MergeIdentitiesResponse> | undefined): boolean {
    return proto3.util.equals(MergeIdentitiesResponse, a, b);
  }
}

