// Workspace service: the bounded-context that links a User to billing
// + workloads + API keys. Every paid resource in iogrid is owned by a
// Workspace, not by a User directly; this gives us multi-tenant
// permission boundaries (one user can belong to many workspaces) and
// matches Stripe's "customer" granularity.
//
// On first authentication identity-svc auto-mints a "personal
// workspace" for the user with the user as OWNER. The user can rename
// it, invite collaborators, upgrade the plan, or create additional
// workspaces from the management plane.
//
// Authorization rules:
//   * GetWorkspace / ListMembers       — any member (OWNER, ADMIN, BILLING_ONLY, READ_ONLY)
//   * UpdateWorkspace                  — OWNER or ADMIN
//   * AddMember / RemoveMember /
//     UpdateMemberRole                 — OWNER or ADMIN
//   * DeleteWorkspace                  — OWNER only
//   * CreateWorkspace / ListWorkspaces — any authenticated user

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=js"
// @generated from file iogrid/identity/v1/workspace.proto (package iogrid.identity.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { PageRequest, PageResponse, UUID } from "../../common/v1/types_pbjs";

/**
 * WorkspacePlan is the billing tier the workspace is on. Mirrors the
 * commercial tiers in docs/PRICING.md; billing-svc joins on this enum
 * to resolve rate-limit ceilings + allowed_categories.
 *
 * @generated from enum iogrid.identity.v1.WorkspacePlan
 */
export enum WorkspacePlan {
  /**
   * @generated from enum value: WORKSPACE_PLAN_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * FREE: hobbyist tier, capped at 1 GB/month bandwidth, 1 CPU-hour.
   *
   * @generated from enum value: WORKSPACE_PLAN_FREE = 1;
   */
  FREE = 1,

  /**
   * STARTER: indie devs, 100 GB/month, 50 CPU-hours, monthly card.
   *
   * @generated from enum value: WORKSPACE_PLAN_STARTER = 2;
   */
  STARTER = 2,

  /**
   * GROWTH: SMB, 2 TB/month, 1000 CPU-hours, prepaid credits.
   *
   * @generated from enum value: WORKSPACE_PLAN_GROWTH = 3;
   */
  GROWTH = 3,

  /**
   * ENTERPRISE: contractual seat, no hard caps, invoicing.
   *
   * @generated from enum value: WORKSPACE_PLAN_ENTERPRISE = 4;
   */
  ENTERPRISE = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(WorkspacePlan)
proto3.util.setEnumType(WorkspacePlan, "iogrid.identity.v1.WorkspacePlan", [
  { no: 0, name: "WORKSPACE_PLAN_UNSPECIFIED" },
  { no: 1, name: "WORKSPACE_PLAN_FREE" },
  { no: 2, name: "WORKSPACE_PLAN_STARTER" },
  { no: 3, name: "WORKSPACE_PLAN_GROWTH" },
  { no: 4, name: "WORKSPACE_PLAN_ENTERPRISE" },
]);

/**
 * Role enumerates the per-membership role. We deliberately keep this
 * small — fine-grained per-resource ACLs are out of scope; if you can
 * see the workspace you can see every resource in it (with read/write
 * gated by the role rank below).
 *
 * Rank order (most → least privilege):
 *   OWNER > ADMIN > BILLING_ONLY ≈ READ_ONLY
 *
 * BILLING_ONLY and READ_ONLY have equal read access; BILLING_ONLY can
 * additionally view + change payment methods (so an external finance
 * person can pay invoices without seeing workloads).
 *
 * @generated from enum iogrid.identity.v1.Role
 */
export enum Role {
  /**
   * @generated from enum value: ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ROLE_OWNER = 1;
   */
  OWNER = 1,

  /**
   * @generated from enum value: ROLE_ADMIN = 2;
   */
  ADMIN = 2,

  /**
   * @generated from enum value: ROLE_BILLING_ONLY = 3;
   */
  BILLING_ONLY = 3,

  /**
   * @generated from enum value: ROLE_READ_ONLY = 4;
   */
  READ_ONLY = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(Role)
proto3.util.setEnumType(Role, "iogrid.identity.v1.Role", [
  { no: 0, name: "ROLE_UNSPECIFIED" },
  { no: 1, name: "ROLE_OWNER" },
  { no: 2, name: "ROLE_ADMIN" },
  { no: 3, name: "ROLE_BILLING_ONLY" },
  { no: 4, name: "ROLE_READ_ONLY" },
]);

/**
 * Workspace is the canonical record. Identifier columns
 * (billing_customer_id_stripe) come from external integrations and may
 * be empty until the user starts a Stripe checkout flow.
 *
 * @generated from message iogrid.identity.v1.Workspace
 */
export class Workspace extends Message<Workspace> {
  /**
   * @generated from field: iogrid.common.v1.UUID id = 1;
   */
  id?: UUID;

  /**
   * owner_user_id is denormalised here for convenience; it MUST also
   * appear as a Membership row with role=OWNER.
   *
   * @generated from field: iogrid.common.v1.UUID owner_user_id = 2;
   */
  ownerUserId?: UUID;

  /**
   * Human-readable display name. Defaults to "<email>'s workspace"
   * on auto-creation.
   *
   * @generated from field: string name = 3;
   */
  name = "";

  /**
   * @generated from field: iogrid.identity.v1.WorkspacePlan plan = 4;
   */
  plan = WorkspacePlan.UNSPECIFIED;

  /**
   * Stripe customer id once the workspace has subscribed; empty
   * before first checkout.
   *
   * @generated from field: string billing_customer_id_stripe = 5;
   */
  billingCustomerIdStripe = "";

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 7;
   */
  updatedAt?: Timestamp;

  constructor(data?: PartialMessage<Workspace>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.Workspace";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: UUID },
    { no: 2, name: "owner_user_id", kind: "message", T: UUID },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "plan", kind: "enum", T: proto3.getEnumType(WorkspacePlan) },
    { no: 5, name: "billing_customer_id_stripe", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "created_at", kind: "message", T: Timestamp },
    { no: 7, name: "updated_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Workspace {
    return new Workspace().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Workspace {
    return new Workspace().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Workspace {
    return new Workspace().fromJsonString(jsonString, options);
  }

  static equals(a: Workspace | PlainMessage<Workspace> | undefined, b: Workspace | PlainMessage<Workspace> | undefined): boolean {
    return proto3.util.equals(Workspace, a, b);
  }
}

/**
 * Membership joins User → Workspace. UNIQUE (workspace_id, user_id)
 * in the underlying table prevents duplicate rows.
 *
 * @generated from message iogrid.identity.v1.Membership
 */
export class Membership extends Message<Membership> {
  /**
   * @generated from field: iogrid.common.v1.UUID workspace_id = 1;
   */
  workspaceId?: UUID;

  /**
   * @generated from field: iogrid.common.v1.UUID user_id = 2;
   */
  userId?: UUID;

  /**
   * @generated from field: iogrid.identity.v1.Role role = 3;
   */
  role = Role.UNSPECIFIED;

  /**
   * @generated from field: google.protobuf.Timestamp joined_at = 4;
   */
  joinedAt?: Timestamp;

  constructor(data?: PartialMessage<Membership>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.Membership";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workspace_id", kind: "message", T: UUID },
    { no: 2, name: "user_id", kind: "message", T: UUID },
    { no: 3, name: "role", kind: "enum", T: proto3.getEnumType(Role) },
    { no: 4, name: "joined_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Membership {
    return new Membership().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Membership {
    return new Membership().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Membership {
    return new Membership().fromJsonString(jsonString, options);
  }

  static equals(a: Membership | PlainMessage<Membership> | undefined, b: Membership | PlainMessage<Membership> | undefined): boolean {
    return proto3.util.equals(Membership, a, b);
  }
}

/**
 * MemberDetail enriches a Membership with the joined User's primary
 * email + display name for the management-plane "Members" tab.
 *
 * @generated from message iogrid.identity.v1.MemberDetail
 */
export class MemberDetail extends Message<MemberDetail> {
  /**
   * @generated from field: iogrid.identity.v1.Membership membership = 1;
   */
  membership?: Membership;

  /**
   * Human-facing fields lifted from the linked User row. Empty when
   * the user has been hard-deleted.
   *
   * @generated from field: string primary_email = 2;
   */
  primaryEmail = "";

  /**
   * @generated from field: string display_name = 3;
   */
  displayName = "";

  constructor(data?: PartialMessage<MemberDetail>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.MemberDetail";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "membership", kind: "message", T: Membership },
    { no: 2, name: "primary_email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MemberDetail {
    return new MemberDetail().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MemberDetail {
    return new MemberDetail().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MemberDetail {
    return new MemberDetail().fromJsonString(jsonString, options);
  }

  static equals(a: MemberDetail | PlainMessage<MemberDetail> | undefined, b: MemberDetail | PlainMessage<MemberDetail> | undefined): boolean {
    return proto3.util.equals(MemberDetail, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.CreateWorkspaceRequest
 */
export class CreateWorkspaceRequest extends Message<CreateWorkspaceRequest> {
  /**
   * Free-form display name. Required. Trimmed; max 100 chars.
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * Optional. Defaults to WORKSPACE_PLAN_FREE for self-serve signups.
   *
   * @generated from field: iogrid.identity.v1.WorkspacePlan plan = 2;
   */
  plan = WorkspacePlan.UNSPECIFIED;

  constructor(data?: PartialMessage<CreateWorkspaceRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.CreateWorkspaceRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "plan", kind: "enum", T: proto3.getEnumType(WorkspacePlan) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateWorkspaceRequest {
    return new CreateWorkspaceRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateWorkspaceRequest {
    return new CreateWorkspaceRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateWorkspaceRequest {
    return new CreateWorkspaceRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateWorkspaceRequest | PlainMessage<CreateWorkspaceRequest> | undefined, b: CreateWorkspaceRequest | PlainMessage<CreateWorkspaceRequest> | undefined): boolean {
    return proto3.util.equals(CreateWorkspaceRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.CreateWorkspaceResponse
 */
export class CreateWorkspaceResponse extends Message<CreateWorkspaceResponse> {
  /**
   * @generated from field: iogrid.identity.v1.Workspace workspace = 1;
   */
  workspace?: Workspace;

  constructor(data?: PartialMessage<CreateWorkspaceResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.CreateWorkspaceResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workspace", kind: "message", T: Workspace },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateWorkspaceResponse {
    return new CreateWorkspaceResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateWorkspaceResponse {
    return new CreateWorkspaceResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateWorkspaceResponse {
    return new CreateWorkspaceResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateWorkspaceResponse | PlainMessage<CreateWorkspaceResponse> | undefined, b: CreateWorkspaceResponse | PlainMessage<CreateWorkspaceResponse> | undefined): boolean {
    return proto3.util.equals(CreateWorkspaceResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.GetWorkspaceRequest
 */
export class GetWorkspaceRequest extends Message<GetWorkspaceRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID id = 1;
   */
  id?: UUID;

  constructor(data?: PartialMessage<GetWorkspaceRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.GetWorkspaceRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: UUID },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetWorkspaceRequest {
    return new GetWorkspaceRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetWorkspaceRequest {
    return new GetWorkspaceRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetWorkspaceRequest {
    return new GetWorkspaceRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetWorkspaceRequest | PlainMessage<GetWorkspaceRequest> | undefined, b: GetWorkspaceRequest | PlainMessage<GetWorkspaceRequest> | undefined): boolean {
    return proto3.util.equals(GetWorkspaceRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.GetWorkspaceResponse
 */
export class GetWorkspaceResponse extends Message<GetWorkspaceResponse> {
  /**
   * @generated from field: iogrid.identity.v1.Workspace workspace = 1;
   */
  workspace?: Workspace;

  /**
   * The caller's role within this workspace — handy for the UI to
   * gate write affordances without a second RPC.
   *
   * @generated from field: iogrid.identity.v1.Role caller_role = 2;
   */
  callerRole = Role.UNSPECIFIED;

  constructor(data?: PartialMessage<GetWorkspaceResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.GetWorkspaceResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workspace", kind: "message", T: Workspace },
    { no: 2, name: "caller_role", kind: "enum", T: proto3.getEnumType(Role) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetWorkspaceResponse {
    return new GetWorkspaceResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetWorkspaceResponse {
    return new GetWorkspaceResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetWorkspaceResponse {
    return new GetWorkspaceResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetWorkspaceResponse | PlainMessage<GetWorkspaceResponse> | undefined, b: GetWorkspaceResponse | PlainMessage<GetWorkspaceResponse> | undefined): boolean {
    return proto3.util.equals(GetWorkspaceResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.ListWorkspacesRequest
 */
export class ListWorkspacesRequest extends Message<ListWorkspacesRequest> {
  /**
   * Optional. When empty the server uses the authenticated caller as
   * the user filter. Admin tooling can pass a different id (gated by
   * a separate role check upstream).
   *
   * @generated from field: iogrid.common.v1.UUID user_id = 1;
   */
  userId?: UUID;

  /**
   * @generated from field: iogrid.common.v1.PageRequest page = 2;
   */
  page?: PageRequest;

  constructor(data?: PartialMessage<ListWorkspacesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.ListWorkspacesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "message", T: UUID },
    { no: 2, name: "page", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListWorkspacesRequest {
    return new ListWorkspacesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListWorkspacesRequest {
    return new ListWorkspacesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListWorkspacesRequest {
    return new ListWorkspacesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListWorkspacesRequest | PlainMessage<ListWorkspacesRequest> | undefined, b: ListWorkspacesRequest | PlainMessage<ListWorkspacesRequest> | undefined): boolean {
    return proto3.util.equals(ListWorkspacesRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.ListWorkspacesResponse
 */
export class ListWorkspacesResponse extends Message<ListWorkspacesResponse> {
  /**
   * Each entry includes the caller's role, so the UI can render the
   * workspace selector without a second round-trip.
   *
   * @generated from field: repeated iogrid.identity.v1.Workspace workspaces = 1;
   */
  workspaces: Workspace[] = [];

  /**
   * @generated from field: repeated iogrid.identity.v1.Role roles = 2;
   */
  roles: Role[] = [];

  /**
   * @generated from field: iogrid.common.v1.PageResponse page = 3;
   */
  page?: PageResponse;

  constructor(data?: PartialMessage<ListWorkspacesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.ListWorkspacesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workspaces", kind: "message", T: Workspace, repeated: true },
    { no: 2, name: "roles", kind: "enum", T: proto3.getEnumType(Role), repeated: true },
    { no: 3, name: "page", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListWorkspacesResponse {
    return new ListWorkspacesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListWorkspacesResponse {
    return new ListWorkspacesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListWorkspacesResponse {
    return new ListWorkspacesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListWorkspacesResponse | PlainMessage<ListWorkspacesResponse> | undefined, b: ListWorkspacesResponse | PlainMessage<ListWorkspacesResponse> | undefined): boolean {
    return proto3.util.equals(ListWorkspacesResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.UpdateWorkspaceRequest
 */
export class UpdateWorkspaceRequest extends Message<UpdateWorkspaceRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID id = 1;
   */
  id?: UUID;

  /**
   * Empty fields are "do not change". Plan change is a privileged
   * operation in the proxy/billing tier — billing-svc reconciles the
   * Stripe subscription out-of-band.
   *
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: iogrid.identity.v1.WorkspacePlan plan = 3;
   */
  plan = WorkspacePlan.UNSPECIFIED;

  constructor(data?: PartialMessage<UpdateWorkspaceRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.UpdateWorkspaceRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: UUID },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "plan", kind: "enum", T: proto3.getEnumType(WorkspacePlan) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateWorkspaceRequest {
    return new UpdateWorkspaceRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateWorkspaceRequest {
    return new UpdateWorkspaceRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateWorkspaceRequest {
    return new UpdateWorkspaceRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateWorkspaceRequest | PlainMessage<UpdateWorkspaceRequest> | undefined, b: UpdateWorkspaceRequest | PlainMessage<UpdateWorkspaceRequest> | undefined): boolean {
    return proto3.util.equals(UpdateWorkspaceRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.UpdateWorkspaceResponse
 */
export class UpdateWorkspaceResponse extends Message<UpdateWorkspaceResponse> {
  /**
   * @generated from field: iogrid.identity.v1.Workspace workspace = 1;
   */
  workspace?: Workspace;

  constructor(data?: PartialMessage<UpdateWorkspaceResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.UpdateWorkspaceResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workspace", kind: "message", T: Workspace },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateWorkspaceResponse {
    return new UpdateWorkspaceResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateWorkspaceResponse {
    return new UpdateWorkspaceResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateWorkspaceResponse {
    return new UpdateWorkspaceResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateWorkspaceResponse | PlainMessage<UpdateWorkspaceResponse> | undefined, b: UpdateWorkspaceResponse | PlainMessage<UpdateWorkspaceResponse> | undefined): boolean {
    return proto3.util.equals(UpdateWorkspaceResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.DeleteWorkspaceRequest
 */
export class DeleteWorkspaceRequest extends Message<DeleteWorkspaceRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID id = 1;
   */
  id?: UUID;

  /**
   * Fresh step-up token required — destructive op.
   *
   * @generated from field: string step_up_token = 2;
   */
  stepUpToken = "";

  constructor(data?: PartialMessage<DeleteWorkspaceRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.DeleteWorkspaceRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: UUID },
    { no: 2, name: "step_up_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteWorkspaceRequest {
    return new DeleteWorkspaceRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteWorkspaceRequest {
    return new DeleteWorkspaceRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteWorkspaceRequest {
    return new DeleteWorkspaceRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteWorkspaceRequest | PlainMessage<DeleteWorkspaceRequest> | undefined, b: DeleteWorkspaceRequest | PlainMessage<DeleteWorkspaceRequest> | undefined): boolean {
    return proto3.util.equals(DeleteWorkspaceRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.DeleteWorkspaceResponse
 */
export class DeleteWorkspaceResponse extends Message<DeleteWorkspaceResponse> {
  constructor(data?: PartialMessage<DeleteWorkspaceResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.DeleteWorkspaceResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteWorkspaceResponse {
    return new DeleteWorkspaceResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteWorkspaceResponse {
    return new DeleteWorkspaceResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteWorkspaceResponse {
    return new DeleteWorkspaceResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteWorkspaceResponse | PlainMessage<DeleteWorkspaceResponse> | undefined, b: DeleteWorkspaceResponse | PlainMessage<DeleteWorkspaceResponse> | undefined): boolean {
    return proto3.util.equals(DeleteWorkspaceResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.AddMemberRequest
 */
export class AddMemberRequest extends Message<AddMemberRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID workspace_id = 1;
   */
  workspaceId?: UUID;

  /**
   * The invitee. We use email rather than user_id so admins can
   * invite people who haven't signed up yet — identity-svc creates a
   * pending magic-link bind once the invitee redeems an emailed link.
   *
   * @generated from field: string user_email = 2;
   */
  userEmail = "";

  /**
   * @generated from field: iogrid.identity.v1.Role role = 3;
   */
  role = Role.UNSPECIFIED;

  constructor(data?: PartialMessage<AddMemberRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.AddMemberRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workspace_id", kind: "message", T: UUID },
    { no: 2, name: "user_email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "role", kind: "enum", T: proto3.getEnumType(Role) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddMemberRequest {
    return new AddMemberRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddMemberRequest {
    return new AddMemberRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddMemberRequest {
    return new AddMemberRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AddMemberRequest | PlainMessage<AddMemberRequest> | undefined, b: AddMemberRequest | PlainMessage<AddMemberRequest> | undefined): boolean {
    return proto3.util.equals(AddMemberRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.AddMemberResponse
 */
export class AddMemberResponse extends Message<AddMemberResponse> {
  /**
   * @generated from field: iogrid.identity.v1.Membership membership = 1;
   */
  membership?: Membership;

  /**
   * True when the invitee didn't have a User yet and we created a
   * pending stub. UI surfaces "Pending — email sent" in that case.
   *
   * @generated from field: bool pending = 2;
   */
  pending = false;

  constructor(data?: PartialMessage<AddMemberResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.AddMemberResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "membership", kind: "message", T: Membership },
    { no: 2, name: "pending", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddMemberResponse {
    return new AddMemberResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddMemberResponse {
    return new AddMemberResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddMemberResponse {
    return new AddMemberResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AddMemberResponse | PlainMessage<AddMemberResponse> | undefined, b: AddMemberResponse | PlainMessage<AddMemberResponse> | undefined): boolean {
    return proto3.util.equals(AddMemberResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.RemoveMemberRequest
 */
export class RemoveMemberRequest extends Message<RemoveMemberRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID workspace_id = 1;
   */
  workspaceId?: UUID;

  /**
   * @generated from field: iogrid.common.v1.UUID user_id = 2;
   */
  userId?: UUID;

  constructor(data?: PartialMessage<RemoveMemberRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.RemoveMemberRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workspace_id", kind: "message", T: UUID },
    { no: 2, name: "user_id", kind: "message", T: UUID },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveMemberRequest {
    return new RemoveMemberRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveMemberRequest {
    return new RemoveMemberRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveMemberRequest {
    return new RemoveMemberRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RemoveMemberRequest | PlainMessage<RemoveMemberRequest> | undefined, b: RemoveMemberRequest | PlainMessage<RemoveMemberRequest> | undefined): boolean {
    return proto3.util.equals(RemoveMemberRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.RemoveMemberResponse
 */
export class RemoveMemberResponse extends Message<RemoveMemberResponse> {
  constructor(data?: PartialMessage<RemoveMemberResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.RemoveMemberResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveMemberResponse {
    return new RemoveMemberResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveMemberResponse {
    return new RemoveMemberResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveMemberResponse {
    return new RemoveMemberResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RemoveMemberResponse | PlainMessage<RemoveMemberResponse> | undefined, b: RemoveMemberResponse | PlainMessage<RemoveMemberResponse> | undefined): boolean {
    return proto3.util.equals(RemoveMemberResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.ListMembersRequest
 */
export class ListMembersRequest extends Message<ListMembersRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID workspace_id = 1;
   */
  workspaceId?: UUID;

  /**
   * @generated from field: iogrid.common.v1.PageRequest page = 2;
   */
  page?: PageRequest;

  constructor(data?: PartialMessage<ListMembersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.ListMembersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workspace_id", kind: "message", T: UUID },
    { no: 2, name: "page", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListMembersRequest {
    return new ListMembersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListMembersRequest {
    return new ListMembersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListMembersRequest {
    return new ListMembersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListMembersRequest | PlainMessage<ListMembersRequest> | undefined, b: ListMembersRequest | PlainMessage<ListMembersRequest> | undefined): boolean {
    return proto3.util.equals(ListMembersRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.ListMembersResponse
 */
export class ListMembersResponse extends Message<ListMembersResponse> {
  /**
   * @generated from field: repeated iogrid.identity.v1.MemberDetail members = 1;
   */
  members: MemberDetail[] = [];

  /**
   * @generated from field: iogrid.common.v1.PageResponse page = 2;
   */
  page?: PageResponse;

  constructor(data?: PartialMessage<ListMembersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.ListMembersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "members", kind: "message", T: MemberDetail, repeated: true },
    { no: 2, name: "page", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListMembersResponse {
    return new ListMembersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListMembersResponse {
    return new ListMembersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListMembersResponse {
    return new ListMembersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListMembersResponse | PlainMessage<ListMembersResponse> | undefined, b: ListMembersResponse | PlainMessage<ListMembersResponse> | undefined): boolean {
    return proto3.util.equals(ListMembersResponse, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.UpdateMemberRoleRequest
 */
export class UpdateMemberRoleRequest extends Message<UpdateMemberRoleRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID workspace_id = 1;
   */
  workspaceId?: UUID;

  /**
   * @generated from field: iogrid.common.v1.UUID user_id = 2;
   */
  userId?: UUID;

  /**
   * @generated from field: iogrid.identity.v1.Role role = 3;
   */
  role = Role.UNSPECIFIED;

  constructor(data?: PartialMessage<UpdateMemberRoleRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.UpdateMemberRoleRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workspace_id", kind: "message", T: UUID },
    { no: 2, name: "user_id", kind: "message", T: UUID },
    { no: 3, name: "role", kind: "enum", T: proto3.getEnumType(Role) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateMemberRoleRequest {
    return new UpdateMemberRoleRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateMemberRoleRequest {
    return new UpdateMemberRoleRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateMemberRoleRequest {
    return new UpdateMemberRoleRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateMemberRoleRequest | PlainMessage<UpdateMemberRoleRequest> | undefined, b: UpdateMemberRoleRequest | PlainMessage<UpdateMemberRoleRequest> | undefined): boolean {
    return proto3.util.equals(UpdateMemberRoleRequest, a, b);
  }
}

/**
 * @generated from message iogrid.identity.v1.UpdateMemberRoleResponse
 */
export class UpdateMemberRoleResponse extends Message<UpdateMemberRoleResponse> {
  /**
   * @generated from field: iogrid.identity.v1.Membership membership = 1;
   */
  membership?: Membership;

  constructor(data?: PartialMessage<UpdateMemberRoleResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.identity.v1.UpdateMemberRoleResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "membership", kind: "message", T: Membership },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateMemberRoleResponse {
    return new UpdateMemberRoleResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateMemberRoleResponse {
    return new UpdateMemberRoleResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateMemberRoleResponse {
    return new UpdateMemberRoleResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateMemberRoleResponse | PlainMessage<UpdateMemberRoleResponse> | undefined, b: UpdateMemberRoleResponse | PlainMessage<UpdateMemberRoleResponse> | undefined): boolean {
    return proto3.util.equals(UpdateMemberRoleResponse, a, b);
  }
}

