// Workspace service: the bounded-context that links a User to billing
// + workloads + API keys. Every paid resource in iogrid is owned by a
// Workspace, not by a User directly; this gives us multi-tenant
// permission boundaries (one user can belong to many workspaces) and
// matches Stripe's "customer" granularity.
//
// On first authentication identity-svc auto-mints a "personal
// workspace" for the user with the user as OWNER. The user can rename
// it, invite collaborators, upgrade the plan, or create additional
// workspaces from the management plane.
//
// Authorization rules:
//   * GetWorkspace / ListMembers       — any member (OWNER, ADMIN, BILLING_ONLY, READ_ONLY)
//   * UpdateWorkspace                  — OWNER or ADMIN
//   * AddMember / RemoveMember /
//     UpdateMemberRole                 — OWNER or ADMIN
//   * DeleteWorkspace                  — OWNER only
//   * CreateWorkspace / ListWorkspaces — any authenticated user

// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=js"
// @generated from file iogrid/identity/v1/workspace.proto (package iogrid.identity.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddMemberRequest, AddMemberResponse, CreateWorkspaceRequest, CreateWorkspaceResponse, DeleteWorkspaceRequest, DeleteWorkspaceResponse, GetWorkspaceRequest, GetWorkspaceResponse, ListMembersRequest, ListMembersResponse, ListWorkspacesRequest, ListWorkspacesResponse, RemoveMemberRequest, RemoveMemberResponse, UpdateMemberRoleRequest, UpdateMemberRoleResponse, UpdateWorkspaceRequest, UpdateWorkspaceResponse } from "./workspace_pbjs";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * WorkspaceService is the bounded-context's wire contract. Lives in
 * identity-svc alongside Users + Identifiers because Workspace ownership
 * follows from the User record and membership is checked on every auth.
 *
 * @generated from service iogrid.identity.v1.WorkspaceService
 */
export const WorkspaceService = {
  typeName: "iogrid.identity.v1.WorkspaceService",
  methods: {
    /**
     * @generated from rpc iogrid.identity.v1.WorkspaceService.CreateWorkspace
     */
    createWorkspace: {
      name: "CreateWorkspace",
      I: CreateWorkspaceRequest,
      O: CreateWorkspaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.identity.v1.WorkspaceService.GetWorkspace
     */
    getWorkspace: {
      name: "GetWorkspace",
      I: GetWorkspaceRequest,
      O: GetWorkspaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.identity.v1.WorkspaceService.ListWorkspaces
     */
    listWorkspaces: {
      name: "ListWorkspaces",
      I: ListWorkspacesRequest,
      O: ListWorkspacesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.identity.v1.WorkspaceService.UpdateWorkspace
     */
    updateWorkspace: {
      name: "UpdateWorkspace",
      I: UpdateWorkspaceRequest,
      O: UpdateWorkspaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.identity.v1.WorkspaceService.DeleteWorkspace
     */
    deleteWorkspace: {
      name: "DeleteWorkspace",
      I: DeleteWorkspaceRequest,
      O: DeleteWorkspaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.identity.v1.WorkspaceService.AddMember
     */
    addMember: {
      name: "AddMember",
      I: AddMemberRequest,
      O: AddMemberResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.identity.v1.WorkspaceService.RemoveMember
     */
    removeMember: {
      name: "RemoveMember",
      I: RemoveMemberRequest,
      O: RemoveMemberResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.identity.v1.WorkspaceService.ListMembers
     */
    listMembers: {
      name: "ListMembers",
      I: ListMembersRequest,
      O: ListMembersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.identity.v1.WorkspaceService.UpdateMemberRole
     */
    updateMemberRole: {
      name: "UpdateMemberRole",
      I: UpdateMemberRoleRequest,
      O: UpdateMemberRoleResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

