apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-bff
  namespace: iogrid
  labels:
    app.kubernetes.io/name: gateway-bff
    app.kubernetes.io/part-of: iogrid
    app.kubernetes.io/component: gateway
automountServiceAccountToken: true
