#!/usr/bin/env bash
# Generate a fresh GPG keypair for signing the iogrid Linux package
# repositories (apt / yum / apk). Used for:
#   - first-time setup of the iogrid-linux-repo-signing K8s Secret /
#     GitHub Actions secret IOGRID_LINUX_REPO_GPG_PRIVKEY_B64
#   - key rotation (see installer/linux/repo/README.md#rotating)
#
# Why GPG and not minisign/cosign:
#   - apt-secure REQUIRES OpenPGP signatures on Release files. dpkg won't
#     accept anything else — the entire trust model is wired to gpg.
#   - createrepo_c / yum / dnf use detached PGP signatures on repomd.xml
#     (`repo_gpgcheck=1` in the repo file, signed by gpg --detach-sign).
#   - Alpine's abuild-sign uses raw RSA, but we ALSO ship the GPG key for
#     consistency; the apk side uses a separate RSA key generated by
#     abuild-keygen (see comment in Makefile::apk target).
#
# Usage:
#   ./generate-keypair.sh <DEST_DIR>
#
# Output (under DEST_DIR/):
#   privkey.gpg.asc   — ASCII-armored private key. Put in OpenBao at
#                       kv/iogrid/linux-repo/privkey.gpg.asc + base64
#                       into the GitHub Actions secret
#                       IOGRID_LINUX_REPO_GPG_PRIVKEY_B64.
#                       NEVER commit this to the repo.
#   pubkey.gpg.asc    — ASCII-armored public key. Checked into repo at
#                       installer/linux/repo/pubkey.gpg.asc and shipped
#                       to clients via the repo bootstrap one-liners.
#   keyid.txt         — long-form key ID (16 hex chars). Used by CI to
#                       pass `--default-key` to gpg sign commands.
set -euo pipefail

DEST_DIR="${1:-}"
if [ -z "$DEST_DIR" ]; then
    echo "usage: $0 <DEST_DIR>" >&2
    exit 2
fi
mkdir -p "$DEST_DIR"

# Use a per-invocation GNUPGHOME so we don't pollute the user's keyring.
# gpg2 quirk: GNUPGHOME must be mode 0700 or it whines on every call.
WORK_HOME="$(mktemp -d -t iogrid-gpg-keygen.XXXXXX)"
chmod 0700 "$WORK_HOME"
trap 'rm -rf "$WORK_HOME"' EXIT
export GNUPGHOME="$WORK_HOME"

# Disable pinentry — we generate an unprotected key (CI runners can't
# enter a passphrase, and the private key itself is protected by being
# kept in OpenBao / GitHub Actions secret store).
cat > "$WORK_HOME/gpg-agent.conf" <<'EOF'
allow-loopback-pinentry
EOF
gpg-connect-agent reloadagent /bye >/dev/null 2>&1 || true

# Batch-mode key generation. ed25519 would be ideal but apt's older
# clients (Ubuntu 20.04 = gnupg 2.2.x) only added cv25519/ed25519
# support in 2.1.x; 4096-bit RSA is the safe-everywhere choice.
cat > "$WORK_HOME/keygen-params" <<'EOF'
%no-protection
Key-Type: RSA
Key-Length: 4096
Key-Usage: sign
Subkey-Type: RSA
Subkey-Length: 4096
Subkey-Usage: sign
Name-Real: iogrid Linux package signing
Name-Email: packages@iogrid.org
Name-Comment: Phase 2 repo signing key (apt/yum/apk)
Expire-Date: 5y
%commit
EOF

echo "[gpg-keygen] generating 4096-bit RSA keypair (this can take a minute)…"
gpg --batch --pinentry-mode loopback --generate-key "$WORK_HOME/keygen-params"

# Extract the long key ID (16 hex chars). `--list-secret-keys --with-colons`
# emits machine-parseable output; the `fpr` line in column 10 is the
# 40-hex fingerprint, of which the last 16 chars are the long key ID.
FPR="$(gpg --list-secret-keys --with-colons | awk -F: '/^fpr:/ { print $10; exit }')"
if [ -z "$FPR" ]; then
    echo "[gpg-keygen] FATAL: could not extract fingerprint after keygen" >&2
    gpg --list-secret-keys >&2 || true
    exit 1
fi
KEYID="${FPR: -16}"

echo "[gpg-keygen] fingerprint: $FPR"
echo "[gpg-keygen] long key id: $KEYID"

# Export ASCII-armored halves.
gpg --batch --pinentry-mode loopback --armor --export "$FPR"          > "$DEST_DIR/pubkey.gpg.asc"
gpg --batch --pinentry-mode loopback --armor --export-secret-keys "$FPR" > "$DEST_DIR/privkey.gpg.asc"
printf '%s\n' "$KEYID" > "$DEST_DIR/keyid.txt"
printf '%s\n' "$FPR"   > "$DEST_DIR/fingerprint.txt"

chmod 0600 "$DEST_DIR/privkey.gpg.asc"
chmod 0644 "$DEST_DIR/pubkey.gpg.asc"

echo ""
echo "[gpg-keygen] DONE."
echo "  public key  : $DEST_DIR/pubkey.gpg.asc  (commit to repo)"
echo "  private key : $DEST_DIR/privkey.gpg.asc (DO NOT commit; upload to OpenBao + GH secret)"
echo "  keyid       : $KEYID"
echo ""
echo "To upload the private key to GitHub Actions:"
echo "  base64 -w0 $DEST_DIR/privkey.gpg.asc | gh secret set IOGRID_LINUX_REPO_GPG_PRIVKEY_B64 --repo iogrid/iogrid"
echo ""
echo "To upload the key id (used by CI as gpg --default-key):"
echo "  gh secret set IOGRID_LINUX_REPO_GPG_KEYID --repo iogrid/iogrid --body '$KEYID'"
