---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: proxy-gateway-secrets
  namespace: iogrid
spec:
  encryptedData:
    DEV_API_KEYS: AgBDCsaJ9FfMzFyztdkDw4tW38yDha0FakDNCHyG60i+yUSCOrsNaG9U/A79ojWrJR+z0n7H0qEFfvlioP7jN0TN9fR/nffxlShc8ltm/BPAjKnHJhvVDWocMTlJrTu3u9LUv4wHxTJXHbz6FeNWU6kT72c2Sgf9Hfb2wsWT6B+k0UriGgRHswbmYwrbrw+f700P+KuDGjlAesaTx2Q1+5cTW2KGCew/9DRw4lEaJEI7FT7I6jtxHIb9Ag9Hk2F9U141lH9Ki+oVvzIs3QYOH/ugX5WZEbx+lM4Mb1z1Zam14is0vpICS93cCi3Xniq2zUJSwX7zW8YbHRAZ9+8uyTY0hEZEs7zs88e1EUKk8L+152XS7WslW92fQCDTWimoxbdIgqn7hhAJyIsMYIM0B4ROEfONVv/7g9fr9CnhTE0shDnwkPhCK26xkNKiaPfZO+rQIFwSShPMZqGyW2aw2pIQOj7of311YIJwOZsUf4Jl1uYYrQhvzPvRL+ToXczEMeA6V92GPu1soko94WNf1dxJL1rj3dJweAF7c6ua4agu3fCZa9xMVT+wC9wpX/2kNYRNON03REQdqW5vHksSCjcZZarowUUwiiiGK8lZiIpZSAS+0nqRRZBnsnXUt2bf+1RQS9v+YTiZRCZopldmxIKpubvQDylk7P7iHhcz/CSV/FnHxeHTECp6BzrtocXayQU4AUhs4Me7h3NgducihvLW5K/1XVkZj/JLAs30MfOOR5Vlr5kHmvEhIEsv7BV06A7PkwISUEbTnI3GsZcpC6wNxHd3w6W0U78y6sNBH5sLyTSqo7sFlrnSuhYN2+2H5buMoR+nXB35311XOLKI10qfVdD2R1iR8T79yCtLjwEhN1hraHqyN6cNibq0uHwr3bYTztTLIy/upJ/ibsJGRvF7VzJfP7gYhJw63yqGqli0zoLudiKFCPrGkiCOKW6c1FXEFZAPemvfFmn2AX2x7ostz6OOfkxJF1PQhKxfIJUY4lK6z31sbIRhgT8F+yN7v15Dvl//+GrqU3GLzztM98I7M9ouQwGWtaGssvDHlHQE6j0Tq+CuLf9p/AtFj0OFeHzumNEGx12Aw636T/BDjxvFTH5+CIqyogYw//n/mEjXho2uoY5PjMXq3MUW/SS6QpzBwY8WKrlOWS5+rarALrktxGGqPcG94rV9+XlM4EQbSQfECaxMg3viO7SjrbdG
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: proxy-gateway-secrets
      namespace: iogrid
