// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: iogrid/vpn/v1/regions.proto

package vpnv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProviderProbe is the per-provider payload returned by the
// top-N-providers-in-region endpoint. The iOS app (and any other mobile
// client) uses this to run client-side latency probes during the roaming
// flow (#572) — it picks the lowest-RTT host candidate from each
// candidate_set, races a few short STUN-like RTT measurements, and
// commits to whichever provider wins. The coordinator's median_rtt_ms
// is only a hint (server-side aggregate over the last hour of
// candidate-discovery RTT samples); the client's own probe is the
// authoritative signal.
type ProviderProbe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProviderId   string          `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`       // Provider UUID
	WgPublicKey  string          `protobuf:"bytes,2,opt,name=wg_public_key,json=wgPublicKey,proto3" json:"wg_public_key,omitempty"`  // Base64-encoded WireGuard public key (may be "" if daemon hasn't registered yet)
	CandidateSet []*IceCandidate `protobuf:"bytes,3,rep,name=candidate_set,json=candidateSet,proto3" json:"candidate_set,omitempty"` // Fresh (non-expired) host / srflx / relay candidates
	MedianRttMs  uint32          `protobuf:"varint,4,opt,name=median_rtt_ms,json=medianRttMs,proto3" json:"median_rtt_ms,omitempty"` // Server-side median over the last hour of candidate-discovery RTT samples; 0 if no samples
}

func (x *ProviderProbe) Reset() {
	*x = ProviderProbe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iogrid_vpn_v1_regions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderProbe) ProtoMessage() {}

func (x *ProviderProbe) ProtoReflect() protoreflect.Message {
	mi := &file_iogrid_vpn_v1_regions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderProbe.ProtoReflect.Descriptor instead.
func (*ProviderProbe) Descriptor() ([]byte, []int) {
	return file_iogrid_vpn_v1_regions_proto_rawDescGZIP(), []int{0}
}

func (x *ProviderProbe) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ProviderProbe) GetWgPublicKey() string {
	if x != nil {
		return x.WgPublicKey
	}
	return ""
}

func (x *ProviderProbe) GetCandidateSet() []*IceCandidate {
	if x != nil {
		return x.CandidateSet
	}
	return nil
}

func (x *ProviderProbe) GetMedianRttMs() uint32 {
	if x != nil {
		return x.MedianRttMs
	}
	return 0
}

// ListTopProvidersResponse is returned by
// GET /v1/vpn/regions/{region}/providers?limit=N. The providers list is
// ordered by ascending session_count (least-loaded first) — the same
// scoring the existing SelectProviderForSession uses — so clients that
// don't run their own RTT probes still get a reasonable fan-out.
type ListTopProvidersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region    string           `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Providers []*ProviderProbe `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
}

func (x *ListTopProvidersResponse) Reset() {
	*x = ListTopProvidersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iogrid_vpn_v1_regions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTopProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopProvidersResponse) ProtoMessage() {}

func (x *ListTopProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iogrid_vpn_v1_regions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListTopProvidersResponse) Descriptor() ([]byte, []int) {
	return file_iogrid_vpn_v1_regions_proto_rawDescGZIP(), []int{1}
}

func (x *ListTopProvidersResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ListTopProvidersResponse) GetProviders() []*ProviderProbe {
	if x != nil {
		return x.Providers
	}
	return nil
}

var File_iogrid_vpn_v1_regions_proto protoreflect.FileDescriptor

var file_iogrid_vpn_v1_regions_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x69, 0x6f, 0x67, 0x72, 0x69, 0x64, 0x2f, 0x76, 0x70, 0x6e, 0x2f, 0x76, 0x31, 0x2f,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x69,
	0x6f, 0x67, 0x72, 0x69, 0x64, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x69, 0x6f,
	0x67, 0x72, 0x69, 0x64, 0x2f, 0x76, 0x70, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xba, 0x01, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x77, 0x67, 0x5f, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x77, 0x67, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x40, 0x0a, 0x0d,
	0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x69, 0x6f, 0x67, 0x72, 0x69, 0x64, 0x2e, 0x76, 0x70, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x0c, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x12, 0x22,
	0x0a, 0x0d, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x5f, 0x72, 0x74, 0x74, 0x5f, 0x6d, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x52, 0x74, 0x74,
	0x4d, 0x73, 0x22, 0x6e, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x69, 0x6f, 0x67, 0x72,
	0x69, 0x64, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x73, 0x42, 0xbd, 0x01, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x6f, 0x67, 0x72, 0x69,
	0x64, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6f, 0x67, 0x72, 0x69, 0x64, 0x2f, 0x69, 0x6f, 0x67, 0x72,
	0x69, 0x64, 0x2f, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x69, 0x6f, 0x67, 0x72, 0x69,
	0x64, 0x2f, 0x76, 0x70, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x70, 0x6e, 0x76, 0x31, 0xa2, 0x02,
	0x03, 0x49, 0x56, 0x58, 0xaa, 0x02, 0x0d, 0x49, 0x6f, 0x67, 0x72, 0x69, 0x64, 0x2e, 0x56, 0x70,
	0x6e, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0d, 0x49, 0x6f, 0x67, 0x72, 0x69, 0x64, 0x5c, 0x56, 0x70,
	0x6e, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x19, 0x49, 0x6f, 0x67, 0x72, 0x69, 0x64, 0x5c, 0x56, 0x70,
	0x6e, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x0f, 0x49, 0x6f, 0x67, 0x72, 0x69, 0x64, 0x3a, 0x3a, 0x56, 0x70, 0x6e, 0x3a, 0x3a,
	0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_iogrid_vpn_v1_regions_proto_rawDescOnce sync.Once
	file_iogrid_vpn_v1_regions_proto_rawDescData = file_iogrid_vpn_v1_regions_proto_rawDesc
)

func file_iogrid_vpn_v1_regions_proto_rawDescGZIP() []byte {
	file_iogrid_vpn_v1_regions_proto_rawDescOnce.Do(func() {
		file_iogrid_vpn_v1_regions_proto_rawDescData = protoimpl.X.CompressGZIP(file_iogrid_vpn_v1_regions_proto_rawDescData)
	})
	return file_iogrid_vpn_v1_regions_proto_rawDescData
}

var file_iogrid_vpn_v1_regions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_iogrid_vpn_v1_regions_proto_goTypes = []any{
	(*ProviderProbe)(nil),            // 0: iogrid.vpn.v1.ProviderProbe
	(*ListTopProvidersResponse)(nil), // 1: iogrid.vpn.v1.ListTopProvidersResponse
	(*IceCandidate)(nil),             // 2: iogrid.vpn.v1.IceCandidate
}
var file_iogrid_vpn_v1_regions_proto_depIdxs = []int32{
	2, // 0: iogrid.vpn.v1.ProviderProbe.candidate_set:type_name -> iogrid.vpn.v1.IceCandidate
	0, // 1: iogrid.vpn.v1.ListTopProvidersResponse.providers:type_name -> iogrid.vpn.v1.ProviderProbe
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_iogrid_vpn_v1_regions_proto_init() }
func file_iogrid_vpn_v1_regions_proto_init() {
	if File_iogrid_vpn_v1_regions_proto != nil {
		return
	}
	file_iogrid_vpn_v1_ice_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_iogrid_vpn_v1_regions_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ProviderProbe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iogrid_vpn_v1_regions_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListTopProvidersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_iogrid_vpn_v1_regions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iogrid_vpn_v1_regions_proto_goTypes,
		DependencyIndexes: file_iogrid_vpn_v1_regions_proto_depIdxs,
		MessageInfos:      file_iogrid_vpn_v1_regions_proto_msgTypes,
	}.Build()
	File_iogrid_vpn_v1_regions_proto = out.File
	file_iogrid_vpn_v1_regions_proto_rawDesc = nil
	file_iogrid_vpn_v1_regions_proto_goTypes = nil
	file_iogrid_vpn_v1_regions_proto_depIdxs = nil
}
