apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy-gateway
  namespace: iogrid
  labels:
    app.kubernetes.io/name: proxy-gateway
    app.kubernetes.io/part-of: iogrid
    app.kubernetes.io/component: gateway
automountServiceAccountToken: true
