// Structured error model used across iogrid services. Connect/gRPC supplies
// the transport-level Status; this package adds richer domain context that
// can be returned via Connect error details.

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=js"
// @generated from file iogrid/common/v1/errors.proto (package iogrid.common.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * ErrorCode is a domain-level error taxonomy. It supplements (does not
 * replace) the gRPC canonical status codes. Every code MUST map to a
 * stable HTTP status server-side for Connect JSON fallback.
 *
 * @generated from enum iogrid.common.v1.ErrorCode
 */
export enum ErrorCode {
  /**
   * @generated from enum value: ERROR_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Caller-side problems.
   *
   * @generated from enum value: ERROR_CODE_INVALID_ARGUMENT = 1;
   */
  INVALID_ARGUMENT = 1,

  /**
   * @generated from enum value: ERROR_CODE_NOT_FOUND = 2;
   */
  NOT_FOUND = 2,

  /**
   * @generated from enum value: ERROR_CODE_ALREADY_EXISTS = 3;
   */
  ALREADY_EXISTS = 3,

  /**
   * @generated from enum value: ERROR_CODE_PERMISSION_DENIED = 4;
   */
  PERMISSION_DENIED = 4,

  /**
   * @generated from enum value: ERROR_CODE_UNAUTHENTICATED = 5;
   */
  UNAUTHENTICATED = 5,

  /**
   * @generated from enum value: ERROR_CODE_RESOURCE_EXHAUSTED = 6;
   */
  RESOURCE_EXHAUSTED = 6,

  /**
   * @generated from enum value: ERROR_CODE_FAILED_PRECONDITION = 7;
   */
  FAILED_PRECONDITION = 7,

  /**
   * @generated from enum value: ERROR_CODE_OUT_OF_RANGE = 8;
   */
  OUT_OF_RANGE = 8,

  /**
   * Server-side problems.
   *
   * @generated from enum value: ERROR_CODE_INTERNAL = 100;
   */
  INTERNAL = 100,

  /**
   * @generated from enum value: ERROR_CODE_UNAVAILABLE = 101;
   */
  UNAVAILABLE = 101,

  /**
   * @generated from enum value: ERROR_CODE_DEADLINE_EXCEEDED = 102;
   */
  DEADLINE_EXCEEDED = 102,

  /**
   * Anti-abuse refusals that need fine-grained reporting to the caller.
   *
   * @generated from enum value: ERROR_CODE_ABUSE_BLOCKED = 200;
   */
  ABUSE_BLOCKED = 200,

  /**
   * @generated from enum value: ERROR_CODE_ABUSE_RATE_LIMITED = 201;
   */
  ABUSE_RATE_LIMITED = 201,

  /**
   * @generated from enum value: ERROR_CODE_ABUSE_CATEGORY_DISALLOWED = 202;
   */
  ABUSE_CATEGORY_DISALLOWED = 202,

  /**
   * @generated from enum value: ERROR_CODE_ABUSE_DESTINATION_BLOCKED = 203;
   */
  ABUSE_DESTINATION_BLOCKED = 203,

  /**
   * Identity / step-up auth.
   *
   * @generated from enum value: ERROR_CODE_STEP_UP_REQUIRED = 300;
   */
  STEP_UP_REQUIRED = 300,

  /**
   * @generated from enum value: ERROR_CODE_IDENTITY_MERGE_AMBIGUOUS = 301;
   */
  IDENTITY_MERGE_AMBIGUOUS = 301,

  /**
   * Billing.
   *
   * @generated from enum value: ERROR_CODE_BILLING_PAST_DUE = 400;
   */
  BILLING_PAST_DUE = 400,

  /**
   * @generated from enum value: ERROR_CODE_BILLING_CARD_DECLINED = 401;
   */
  BILLING_CARD_DECLINED = 401,

  /**
   * @generated from enum value: ERROR_CODE_PAYOUT_NOT_ELIGIBLE = 402;
   */
  PAYOUT_NOT_ELIGIBLE = 402,
}
// Retrieve enum metadata with: proto3.getEnumType(ErrorCode)
proto3.util.setEnumType(ErrorCode, "iogrid.common.v1.ErrorCode", [
  { no: 0, name: "ERROR_CODE_UNSPECIFIED" },
  { no: 1, name: "ERROR_CODE_INVALID_ARGUMENT" },
  { no: 2, name: "ERROR_CODE_NOT_FOUND" },
  { no: 3, name: "ERROR_CODE_ALREADY_EXISTS" },
  { no: 4, name: "ERROR_CODE_PERMISSION_DENIED" },
  { no: 5, name: "ERROR_CODE_UNAUTHENTICATED" },
  { no: 6, name: "ERROR_CODE_RESOURCE_EXHAUSTED" },
  { no: 7, name: "ERROR_CODE_FAILED_PRECONDITION" },
  { no: 8, name: "ERROR_CODE_OUT_OF_RANGE" },
  { no: 100, name: "ERROR_CODE_INTERNAL" },
  { no: 101, name: "ERROR_CODE_UNAVAILABLE" },
  { no: 102, name: "ERROR_CODE_DEADLINE_EXCEEDED" },
  { no: 200, name: "ERROR_CODE_ABUSE_BLOCKED" },
  { no: 201, name: "ERROR_CODE_ABUSE_RATE_LIMITED" },
  { no: 202, name: "ERROR_CODE_ABUSE_CATEGORY_DISALLOWED" },
  { no: 203, name: "ERROR_CODE_ABUSE_DESTINATION_BLOCKED" },
  { no: 300, name: "ERROR_CODE_STEP_UP_REQUIRED" },
  { no: 301, name: "ERROR_CODE_IDENTITY_MERGE_AMBIGUOUS" },
  { no: 400, name: "ERROR_CODE_BILLING_PAST_DUE" },
  { no: 401, name: "ERROR_CODE_BILLING_CARD_DECLINED" },
  { no: 402, name: "ERROR_CODE_PAYOUT_NOT_ELIGIBLE" },
]);

/**
 * ErrorDetail is attached to gRPC/Connect error responses via the error
 * details mechanism. It encodes both a stable machine code and a human
 * message localized at the boundary (callers MUST NOT rely on string
 * content for control flow — use `code` only).
 *
 * @generated from message iogrid.common.v1.ErrorDetail
 */
export class ErrorDetail extends Message<ErrorDetail> {
  /**
   * @generated from field: iogrid.common.v1.ErrorCode code = 1;
   */
  code = ErrorCode.UNSPECIFIED;

  /**
   * Stable English message (callers MAY display verbatim to operators).
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * Optional pointer to the offending request field, in dotted form,
   * e.g. "workload.target.url". Empty when not field-specific.
   *
   * @generated from field: string field_path = 3;
   */
  fieldPath = "";

  /**
   * Free-form structured metadata, e.g. {"retry_after_seconds": "30"}.
   *
   * @generated from field: map<string, string> metadata = 4;
   */
  metadata: { [key: string]: string } = {};

  /**
   * Unique request id (matches the X-Request-Id header / OTel trace_id)
   * for support escalation.
   *
   * @generated from field: string request_id = 5;
   */
  requestId = "";

  constructor(data?: PartialMessage<ErrorDetail>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.common.v1.ErrorDetail";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "code", kind: "enum", T: proto3.getEnumType(ErrorCode) },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "field_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "metadata", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 5, name: "request_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ErrorDetail {
    return new ErrorDetail().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ErrorDetail {
    return new ErrorDetail().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ErrorDetail {
    return new ErrorDetail().fromJsonString(jsonString, options);
  }

  static equals(a: ErrorDetail | PlainMessage<ErrorDetail> | undefined, b: ErrorDetail | PlainMessage<ErrorDetail> | undefined): boolean {
    return proto3.util.equals(ErrorDetail, a, b);
  }
}

