apiVersion: v1
kind: ServiceAccount
metadata:
  name: marketing
  namespace: iogrid
  labels:
    app.kubernetes.io/name: marketing
    app.kubernetes.io/part-of: iogrid
    app.kubernetes.io/component: marketing
automountServiceAccountToken: false
