// Anti-abuse filters: pre-flight checks the daemon (and proxy-gateway)
// run before relaying customer traffic. The SAME filters run server-side
// in antiabuse-svc and locally in the Rust daemon (mirrored), so the
// provider can audit them via the local UI bridge.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: iogrid/antiabuse/v1/filters.proto

package antiabusev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/iogrid/iogrid/coordinator/internal/pb/iogrid/antiabuse/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AbuseFilterServiceName is the fully-qualified name of the AbuseFilterService service.
	AbuseFilterServiceName = "iogrid.antiabuse.v1.AbuseFilterService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AbuseFilterServiceCheckUrlProcedure is the fully-qualified name of the AbuseFilterService's
	// CheckUrl RPC.
	AbuseFilterServiceCheckUrlProcedure = "/iogrid.antiabuse.v1.AbuseFilterService/CheckUrl"
	// AbuseFilterServiceCheckDomainProcedure is the fully-qualified name of the AbuseFilterService's
	// CheckDomain RPC.
	AbuseFilterServiceCheckDomainProcedure = "/iogrid.antiabuse.v1.AbuseFilterService/CheckDomain"
	// AbuseFilterServiceCheckContainerImageProcedure is the fully-qualified name of the
	// AbuseFilterService's CheckContainerImage RPC.
	AbuseFilterServiceCheckContainerImageProcedure = "/iogrid.antiabuse.v1.AbuseFilterService/CheckContainerImage"
	// AbuseFilterServiceReportEventProcedure is the fully-qualified name of the AbuseFilterService's
	// ReportEvent RPC.
	AbuseFilterServiceReportEventProcedure = "/iogrid.antiabuse.v1.AbuseFilterService/ReportEvent"
	// AbuseFilterServiceListFiltersProcedure is the fully-qualified name of the AbuseFilterService's
	// ListFilters RPC.
	AbuseFilterServiceListFiltersProcedure = "/iogrid.antiabuse.v1.AbuseFilterService/ListFilters"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	abuseFilterServiceServiceDescriptor                   = v1.File_iogrid_antiabuse_v1_filters_proto.Services().ByName("AbuseFilterService")
	abuseFilterServiceCheckUrlMethodDescriptor            = abuseFilterServiceServiceDescriptor.Methods().ByName("CheckUrl")
	abuseFilterServiceCheckDomainMethodDescriptor         = abuseFilterServiceServiceDescriptor.Methods().ByName("CheckDomain")
	abuseFilterServiceCheckContainerImageMethodDescriptor = abuseFilterServiceServiceDescriptor.Methods().ByName("CheckContainerImage")
	abuseFilterServiceReportEventMethodDescriptor         = abuseFilterServiceServiceDescriptor.Methods().ByName("ReportEvent")
	abuseFilterServiceListFiltersMethodDescriptor         = abuseFilterServiceServiceDescriptor.Methods().ByName("ListFilters")
)

// AbuseFilterServiceClient is a client for the iogrid.antiabuse.v1.AbuseFilterService service.
type AbuseFilterServiceClient interface {
	CheckUrl(context.Context, *connect.Request[v1.CheckUrlRequest]) (*connect.Response[v1.CheckUrlResponse], error)
	CheckDomain(context.Context, *connect.Request[v1.CheckDomainRequest]) (*connect.Response[v1.CheckDomainResponse], error)
	CheckContainerImage(context.Context, *connect.Request[v1.CheckContainerImageRequest]) (*connect.Response[v1.CheckContainerImageResponse], error)
	ReportEvent(context.Context, *connect.Request[v1.ReportEventRequest]) (*connect.Response[v1.ReportEventResponse], error)
	ListFilters(context.Context, *connect.Request[v1.ListFiltersRequest]) (*connect.Response[v1.ListFiltersResponse], error)
}

// NewAbuseFilterServiceClient constructs a client for the iogrid.antiabuse.v1.AbuseFilterService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAbuseFilterServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AbuseFilterServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &abuseFilterServiceClient{
		checkUrl: connect.NewClient[v1.CheckUrlRequest, v1.CheckUrlResponse](
			httpClient,
			baseURL+AbuseFilterServiceCheckUrlProcedure,
			connect.WithSchema(abuseFilterServiceCheckUrlMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		checkDomain: connect.NewClient[v1.CheckDomainRequest, v1.CheckDomainResponse](
			httpClient,
			baseURL+AbuseFilterServiceCheckDomainProcedure,
			connect.WithSchema(abuseFilterServiceCheckDomainMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		checkContainerImage: connect.NewClient[v1.CheckContainerImageRequest, v1.CheckContainerImageResponse](
			httpClient,
			baseURL+AbuseFilterServiceCheckContainerImageProcedure,
			connect.WithSchema(abuseFilterServiceCheckContainerImageMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		reportEvent: connect.NewClient[v1.ReportEventRequest, v1.ReportEventResponse](
			httpClient,
			baseURL+AbuseFilterServiceReportEventProcedure,
			connect.WithSchema(abuseFilterServiceReportEventMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listFilters: connect.NewClient[v1.ListFiltersRequest, v1.ListFiltersResponse](
			httpClient,
			baseURL+AbuseFilterServiceListFiltersProcedure,
			connect.WithSchema(abuseFilterServiceListFiltersMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// abuseFilterServiceClient implements AbuseFilterServiceClient.
type abuseFilterServiceClient struct {
	checkUrl            *connect.Client[v1.CheckUrlRequest, v1.CheckUrlResponse]
	checkDomain         *connect.Client[v1.CheckDomainRequest, v1.CheckDomainResponse]
	checkContainerImage *connect.Client[v1.CheckContainerImageRequest, v1.CheckContainerImageResponse]
	reportEvent         *connect.Client[v1.ReportEventRequest, v1.ReportEventResponse]
	listFilters         *connect.Client[v1.ListFiltersRequest, v1.ListFiltersResponse]
}

// CheckUrl calls iogrid.antiabuse.v1.AbuseFilterService.CheckUrl.
func (c *abuseFilterServiceClient) CheckUrl(ctx context.Context, req *connect.Request[v1.CheckUrlRequest]) (*connect.Response[v1.CheckUrlResponse], error) {
	return c.checkUrl.CallUnary(ctx, req)
}

// CheckDomain calls iogrid.antiabuse.v1.AbuseFilterService.CheckDomain.
func (c *abuseFilterServiceClient) CheckDomain(ctx context.Context, req *connect.Request[v1.CheckDomainRequest]) (*connect.Response[v1.CheckDomainResponse], error) {
	return c.checkDomain.CallUnary(ctx, req)
}

// CheckContainerImage calls iogrid.antiabuse.v1.AbuseFilterService.CheckContainerImage.
func (c *abuseFilterServiceClient) CheckContainerImage(ctx context.Context, req *connect.Request[v1.CheckContainerImageRequest]) (*connect.Response[v1.CheckContainerImageResponse], error) {
	return c.checkContainerImage.CallUnary(ctx, req)
}

// ReportEvent calls iogrid.antiabuse.v1.AbuseFilterService.ReportEvent.
func (c *abuseFilterServiceClient) ReportEvent(ctx context.Context, req *connect.Request[v1.ReportEventRequest]) (*connect.Response[v1.ReportEventResponse], error) {
	return c.reportEvent.CallUnary(ctx, req)
}

// ListFilters calls iogrid.antiabuse.v1.AbuseFilterService.ListFilters.
func (c *abuseFilterServiceClient) ListFilters(ctx context.Context, req *connect.Request[v1.ListFiltersRequest]) (*connect.Response[v1.ListFiltersResponse], error) {
	return c.listFilters.CallUnary(ctx, req)
}

// AbuseFilterServiceHandler is an implementation of the iogrid.antiabuse.v1.AbuseFilterService
// service.
type AbuseFilterServiceHandler interface {
	CheckUrl(context.Context, *connect.Request[v1.CheckUrlRequest]) (*connect.Response[v1.CheckUrlResponse], error)
	CheckDomain(context.Context, *connect.Request[v1.CheckDomainRequest]) (*connect.Response[v1.CheckDomainResponse], error)
	CheckContainerImage(context.Context, *connect.Request[v1.CheckContainerImageRequest]) (*connect.Response[v1.CheckContainerImageResponse], error)
	ReportEvent(context.Context, *connect.Request[v1.ReportEventRequest]) (*connect.Response[v1.ReportEventResponse], error)
	ListFilters(context.Context, *connect.Request[v1.ListFiltersRequest]) (*connect.Response[v1.ListFiltersResponse], error)
}

// NewAbuseFilterServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAbuseFilterServiceHandler(svc AbuseFilterServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	abuseFilterServiceCheckUrlHandler := connect.NewUnaryHandler(
		AbuseFilterServiceCheckUrlProcedure,
		svc.CheckUrl,
		connect.WithSchema(abuseFilterServiceCheckUrlMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	abuseFilterServiceCheckDomainHandler := connect.NewUnaryHandler(
		AbuseFilterServiceCheckDomainProcedure,
		svc.CheckDomain,
		connect.WithSchema(abuseFilterServiceCheckDomainMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	abuseFilterServiceCheckContainerImageHandler := connect.NewUnaryHandler(
		AbuseFilterServiceCheckContainerImageProcedure,
		svc.CheckContainerImage,
		connect.WithSchema(abuseFilterServiceCheckContainerImageMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	abuseFilterServiceReportEventHandler := connect.NewUnaryHandler(
		AbuseFilterServiceReportEventProcedure,
		svc.ReportEvent,
		connect.WithSchema(abuseFilterServiceReportEventMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	abuseFilterServiceListFiltersHandler := connect.NewUnaryHandler(
		AbuseFilterServiceListFiltersProcedure,
		svc.ListFilters,
		connect.WithSchema(abuseFilterServiceListFiltersMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/iogrid.antiabuse.v1.AbuseFilterService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AbuseFilterServiceCheckUrlProcedure:
			abuseFilterServiceCheckUrlHandler.ServeHTTP(w, r)
		case AbuseFilterServiceCheckDomainProcedure:
			abuseFilterServiceCheckDomainHandler.ServeHTTP(w, r)
		case AbuseFilterServiceCheckContainerImageProcedure:
			abuseFilterServiceCheckContainerImageHandler.ServeHTTP(w, r)
		case AbuseFilterServiceReportEventProcedure:
			abuseFilterServiceReportEventHandler.ServeHTTP(w, r)
		case AbuseFilterServiceListFiltersProcedure:
			abuseFilterServiceListFiltersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAbuseFilterServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAbuseFilterServiceHandler struct{}

func (UnimplementedAbuseFilterServiceHandler) CheckUrl(context.Context, *connect.Request[v1.CheckUrlRequest]) (*connect.Response[v1.CheckUrlResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.antiabuse.v1.AbuseFilterService.CheckUrl is not implemented"))
}

func (UnimplementedAbuseFilterServiceHandler) CheckDomain(context.Context, *connect.Request[v1.CheckDomainRequest]) (*connect.Response[v1.CheckDomainResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.antiabuse.v1.AbuseFilterService.CheckDomain is not implemented"))
}

func (UnimplementedAbuseFilterServiceHandler) CheckContainerImage(context.Context, *connect.Request[v1.CheckContainerImageRequest]) (*connect.Response[v1.CheckContainerImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.antiabuse.v1.AbuseFilterService.CheckContainerImage is not implemented"))
}

func (UnimplementedAbuseFilterServiceHandler) ReportEvent(context.Context, *connect.Request[v1.ReportEventRequest]) (*connect.Response[v1.ReportEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.antiabuse.v1.AbuseFilterService.ReportEvent is not implemented"))
}

func (UnimplementedAbuseFilterServiceHandler) ListFilters(context.Context, *connect.Request[v1.ListFiltersRequest]) (*connect.Response[v1.ListFiltersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.antiabuse.v1.AbuseFilterService.ListFilters is not implemented"))
}
