// Provider earnings summary + payout-method preference for the
// /provider/earnings page. Lives in billing-svc (NOT providers-svc)
// because the canonical money state — including pending-payout balance,
// lifetime totals, and the user's preferred off-ramp variant — is owned
// by billing-svc's bounded context.
//
// providers-svc keeps its own GetEarningsSummary (proto: providers/v1/
// dashboard.proto) for the transparency feed: that one breaks revenue
// down by workload_type for a single TimeWindow. THIS service answers
// the headline-card shape the management UI shows (totals + rolling
// windows + payout method).

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=js"
// @generated from file iogrid/billing/v1/earnings.proto (package iogrid.billing.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";
import { Money, UUID } from "../../common/v1/types_pbjs";

/**
 * PayoutMethodKind is the user-visible payout election. Persisted as a
 * string in billing-svc's payout_methods table; new variants must be
 * appended (never renumbered).
 *
 * @generated from enum iogrid.billing.v1.PayoutMethodKind
 */
export enum PayoutMethodKind {
  /**
   * @generated from enum value: PAYOUT_METHOD_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Off-ramp $GRID → USDC on Solana, send to destination_address.
   *
   * @generated from enum value: PAYOUT_METHOD_KIND_CASH_USDC = 1;
   */
  CASH_USDC = 1,

  /**
   * Burn $GRID into the VPN credit pool — no token leaves the system.
   *
   * @generated from enum value: PAYOUT_METHOD_KIND_FREE_VPN = 2;
   */
  FREE_VPN = 2,

  /**
   * Off-ramp $GRID → USD and forward proceeds to charity_id.
   *
   * @generated from enum value: PAYOUT_METHOD_KIND_CHARITY = 3;
   */
  CHARITY = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(PayoutMethodKind)
proto3.util.setEnumType(PayoutMethodKind, "iogrid.billing.v1.PayoutMethodKind", [
  { no: 0, name: "PAYOUT_METHOD_KIND_UNSPECIFIED" },
  { no: 1, name: "PAYOUT_METHOD_KIND_CASH_USDC" },
  { no: 2, name: "PAYOUT_METHOD_KIND_FREE_VPN" },
  { no: 3, name: "PAYOUT_METHOD_KIND_CHARITY" },
]);

/**
 * EarningsSummary is the headline-card aggregation for /provider/earnings.
 * All Money fields default to currency="GRID" (#312 / #315 — the canonical
 * native ledger currency) when the provider has no recorded earnings yet.
 *
 * @generated from message iogrid.billing.v1.EarningsSummary
 */
export class EarningsSummary extends Message<EarningsSummary> {
  /**
   * @generated from field: iogrid.common.v1.UUID provider_id = 1;
   */
  providerId?: UUID;

  /**
   * Lifetime cumulative — never resets.
   *
   * @generated from field: iogrid.common.v1.Money total_earned = 2;
   */
  totalEarned?: Money;

  /**
   * Trailing 30-day window (start = now - 30d, end = now).
   *
   * @generated from field: iogrid.common.v1.Money last_30d = 3;
   */
  last30d?: Money;

  /**
   * Trailing 7-day window (start = now - 7d, end = now).
   *
   * @generated from field: iogrid.common.v1.Money last_7d = 4;
   */
  last7d?: Money;

  /**
   * Funds credited but not yet swept to the user's payout method.
   *
   * @generated from field: iogrid.common.v1.Money pending_payout = 5;
   */
  pendingPayout?: Money;

  /**
   * Count of distinct workloads served lifetime.
   *
   * @generated from field: int64 lifetime_workloads = 6;
   */
  lifetimeWorkloads = protoInt64.zero;

  /**
   * Server-side computation timestamp; clients use this for "as-of" labels.
   *
   * @generated from field: google.protobuf.Timestamp computed_at = 7;
   */
  computedAt?: Timestamp;

  /**
   * Count of settled iOS-build settlement rows (grid_build_settlement)
   * attributed to this provider — each is a build that ran AND paid the
   * provider on-chain in $GRID. Surfaced as the dashboard "builds" number
   * so a provider who ran real builds sees a non-zero count even when the
   * legacy usage_event metering basis was ~0. See #758/#748.
   *
   * @generated from field: int64 settled_builds = 8;
   */
  settledBuilds = protoInt64.zero;

  /**
   * The slice of total_earned that is settled on-chain $GRID provider_share
   * (build + session settlements), in the same Money currency/micros. Lets
   * the UI label "X of which confirmed on-chain". See #758.
   *
   * @generated from field: iogrid.common.v1.Money settled_grid = 9;
   */
  settledGrid?: Money;

  constructor(data?: PartialMessage<EarningsSummary>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.EarningsSummary";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "provider_id", kind: "message", T: UUID },
    { no: 2, name: "total_earned", kind: "message", T: Money },
    { no: 3, name: "last_30d", kind: "message", T: Money },
    { no: 4, name: "last_7d", kind: "message", T: Money },
    { no: 5, name: "pending_payout", kind: "message", T: Money },
    { no: 6, name: "lifetime_workloads", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "computed_at", kind: "message", T: Timestamp },
    { no: 8, name: "settled_builds", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "settled_grid", kind: "message", T: Money },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EarningsSummary {
    return new EarningsSummary().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EarningsSummary {
    return new EarningsSummary().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EarningsSummary {
    return new EarningsSummary().fromJsonString(jsonString, options);
  }

  static equals(a: EarningsSummary | PlainMessage<EarningsSummary> | undefined, b: EarningsSummary | PlainMessage<EarningsSummary> | undefined): boolean {
    return proto3.util.equals(EarningsSummary, a, b);
  }
}

/**
 * @generated from message iogrid.billing.v1.GetEarningsSummaryRequest
 */
export class GetEarningsSummaryRequest extends Message<GetEarningsSummaryRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID provider_id = 1;
   */
  providerId?: UUID;

  constructor(data?: PartialMessage<GetEarningsSummaryRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.GetEarningsSummaryRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "provider_id", kind: "message", T: UUID },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEarningsSummaryRequest {
    return new GetEarningsSummaryRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEarningsSummaryRequest {
    return new GetEarningsSummaryRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEarningsSummaryRequest {
    return new GetEarningsSummaryRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetEarningsSummaryRequest | PlainMessage<GetEarningsSummaryRequest> | undefined, b: GetEarningsSummaryRequest | PlainMessage<GetEarningsSummaryRequest> | undefined): boolean {
    return proto3.util.equals(GetEarningsSummaryRequest, a, b);
  }
}

/**
 * @generated from message iogrid.billing.v1.GetEarningsSummaryResponse
 */
export class GetEarningsSummaryResponse extends Message<GetEarningsSummaryResponse> {
  /**
   * @generated from field: iogrid.billing.v1.EarningsSummary summary = 1;
   */
  summary?: EarningsSummary;

  constructor(data?: PartialMessage<GetEarningsSummaryResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.GetEarningsSummaryResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "summary", kind: "message", T: EarningsSummary },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEarningsSummaryResponse {
    return new GetEarningsSummaryResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEarningsSummaryResponse {
    return new GetEarningsSummaryResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEarningsSummaryResponse {
    return new GetEarningsSummaryResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetEarningsSummaryResponse | PlainMessage<GetEarningsSummaryResponse> | undefined, b: GetEarningsSummaryResponse | PlainMessage<GetEarningsSummaryResponse> | undefined): boolean {
    return proto3.util.equals(GetEarningsSummaryResponse, a, b);
  }
}

/**
 * PayoutMethod is the per-user payout election. A user that has not yet
 * picked sees PAYOUT_METHOD_KIND_UNSPECIFIED — the web shell shows the
 * "Hold $GRID (default)" tile selected in that case.
 *
 * @generated from message iogrid.billing.v1.PayoutMethod
 */
export class PayoutMethod extends Message<PayoutMethod> {
  /**
   * @generated from field: iogrid.common.v1.UUID user_id = 1;
   */
  userId?: UUID;

  /**
   * @generated from field: iogrid.billing.v1.PayoutMethodKind kind = 2;
   */
  kind = PayoutMethodKind.UNSPECIFIED;

  /**
   * For CASH_USDC: Solana wallet address ($GRID/USDC live on the same
   * mint family). Empty for FREE_VPN / CHARITY / UNSPECIFIED.
   *
   * @generated from field: string destination_address = 3;
   */
  destinationAddress = "";

  /**
   * For CHARITY: opaque charity_id (resolved via charity catalog).
   * Empty for the other variants.
   *
   * @generated from field: string charity_id = 4;
   */
  charityId = "";

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 5;
   */
  updatedAt?: Timestamp;

  constructor(data?: PartialMessage<PayoutMethod>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.PayoutMethod";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "message", T: UUID },
    { no: 2, name: "kind", kind: "enum", T: proto3.getEnumType(PayoutMethodKind) },
    { no: 3, name: "destination_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "charity_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "updated_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PayoutMethod {
    return new PayoutMethod().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PayoutMethod {
    return new PayoutMethod().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PayoutMethod {
    return new PayoutMethod().fromJsonString(jsonString, options);
  }

  static equals(a: PayoutMethod | PlainMessage<PayoutMethod> | undefined, b: PayoutMethod | PlainMessage<PayoutMethod> | undefined): boolean {
    return proto3.util.equals(PayoutMethod, a, b);
  }
}

/**
 * @generated from message iogrid.billing.v1.GetPayoutMethodRequest
 */
export class GetPayoutMethodRequest extends Message<GetPayoutMethodRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID user_id = 1;
   */
  userId?: UUID;

  constructor(data?: PartialMessage<GetPayoutMethodRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.GetPayoutMethodRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "message", T: UUID },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPayoutMethodRequest {
    return new GetPayoutMethodRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPayoutMethodRequest {
    return new GetPayoutMethodRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPayoutMethodRequest {
    return new GetPayoutMethodRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetPayoutMethodRequest | PlainMessage<GetPayoutMethodRequest> | undefined, b: GetPayoutMethodRequest | PlainMessage<GetPayoutMethodRequest> | undefined): boolean {
    return proto3.util.equals(GetPayoutMethodRequest, a, b);
  }
}

/**
 * @generated from message iogrid.billing.v1.GetPayoutMethodResponse
 */
export class GetPayoutMethodResponse extends Message<GetPayoutMethodResponse> {
  /**
   * @generated from field: iogrid.billing.v1.PayoutMethod method = 1;
   */
  method?: PayoutMethod;

  constructor(data?: PartialMessage<GetPayoutMethodResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.GetPayoutMethodResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "method", kind: "message", T: PayoutMethod },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPayoutMethodResponse {
    return new GetPayoutMethodResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPayoutMethodResponse {
    return new GetPayoutMethodResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPayoutMethodResponse {
    return new GetPayoutMethodResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetPayoutMethodResponse | PlainMessage<GetPayoutMethodResponse> | undefined, b: GetPayoutMethodResponse | PlainMessage<GetPayoutMethodResponse> | undefined): boolean {
    return proto3.util.equals(GetPayoutMethodResponse, a, b);
  }
}

/**
 * @generated from message iogrid.billing.v1.SetPayoutMethodRequest
 */
export class SetPayoutMethodRequest extends Message<SetPayoutMethodRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID user_id = 1;
   */
  userId?: UUID;

  /**
   * @generated from field: iogrid.billing.v1.PayoutMethodKind kind = 2;
   */
  kind = PayoutMethodKind.UNSPECIFIED;

  /**
   * @generated from field: string destination_address = 3;
   */
  destinationAddress = "";

  /**
   * @generated from field: string charity_id = 4;
   */
  charityId = "";

  constructor(data?: PartialMessage<SetPayoutMethodRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.SetPayoutMethodRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "message", T: UUID },
    { no: 2, name: "kind", kind: "enum", T: proto3.getEnumType(PayoutMethodKind) },
    { no: 3, name: "destination_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "charity_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetPayoutMethodRequest {
    return new SetPayoutMethodRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetPayoutMethodRequest {
    return new SetPayoutMethodRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetPayoutMethodRequest {
    return new SetPayoutMethodRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SetPayoutMethodRequest | PlainMessage<SetPayoutMethodRequest> | undefined, b: SetPayoutMethodRequest | PlainMessage<SetPayoutMethodRequest> | undefined): boolean {
    return proto3.util.equals(SetPayoutMethodRequest, a, b);
  }
}

/**
 * @generated from message iogrid.billing.v1.SetPayoutMethodResponse
 */
export class SetPayoutMethodResponse extends Message<SetPayoutMethodResponse> {
  /**
   * @generated from field: iogrid.billing.v1.PayoutMethod method = 1;
   */
  method?: PayoutMethod;

  constructor(data?: PartialMessage<SetPayoutMethodResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.SetPayoutMethodResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "method", kind: "message", T: PayoutMethod },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetPayoutMethodResponse {
    return new SetPayoutMethodResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetPayoutMethodResponse {
    return new SetPayoutMethodResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetPayoutMethodResponse {
    return new SetPayoutMethodResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SetPayoutMethodResponse | PlainMessage<SetPayoutMethodResponse> | undefined, b: SetPayoutMethodResponse | PlainMessage<SetPayoutMethodResponse> | undefined): boolean {
    return proto3.util.equals(SetPayoutMethodResponse, a, b);
  }
}

