// Provider payouts via Stripe Connect: KYC onboarding, balance, payout
// history, eligibility checks. Mirrors customer-side subscription.proto.

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=js"
// @generated from file iogrid/billing/v1/payout.proto (package iogrid.billing.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { Money, PageRequest, PageResponse, TimeWindow, UUID } from "../../common/v1/types_pbjs";

/**
 * PayoutAccountStatus mirrors the Stripe Connect onboarding lifecycle.
 *
 * @generated from enum iogrid.billing.v1.PayoutAccountStatus
 */
export enum PayoutAccountStatus {
  /**
   * @generated from enum value: PAYOUT_ACCOUNT_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Not yet onboarded.
   *
   * @generated from enum value: PAYOUT_ACCOUNT_STATUS_NOT_STARTED = 1;
   */
  NOT_STARTED = 1,

  /**
   * Stripe Connect started but missing required fields (KYC, bank).
   *
   * @generated from enum value: PAYOUT_ACCOUNT_STATUS_PENDING_INFO = 2;
   */
  PENDING_INFO = 2,

  /**
   * Stripe says fully verified — payouts can be sent.
   *
   * @generated from enum value: PAYOUT_ACCOUNT_STATUS_ACTIVE = 3;
   */
  ACTIVE = 3,

  /**
   * Stripe restricted (KYC failed, sanctions, etc).
   *
   * @generated from enum value: PAYOUT_ACCOUNT_STATUS_RESTRICTED = 4;
   */
  RESTRICTED = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(PayoutAccountStatus)
proto3.util.setEnumType(PayoutAccountStatus, "iogrid.billing.v1.PayoutAccountStatus", [
  { no: 0, name: "PAYOUT_ACCOUNT_STATUS_UNSPECIFIED" },
  { no: 1, name: "PAYOUT_ACCOUNT_STATUS_NOT_STARTED" },
  { no: 2, name: "PAYOUT_ACCOUNT_STATUS_PENDING_INFO" },
  { no: 3, name: "PAYOUT_ACCOUNT_STATUS_ACTIVE" },
  { no: 4, name: "PAYOUT_ACCOUNT_STATUS_RESTRICTED" },
]);

/**
 * PayoutStatus is the per-payout lifecycle.
 *
 * @generated from enum iogrid.billing.v1.PayoutStatus
 */
export enum PayoutStatus {
  /**
   * @generated from enum value: PAYOUT_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PAYOUT_STATUS_PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: PAYOUT_STATUS_IN_TRANSIT = 2;
   */
  IN_TRANSIT = 2,

  /**
   * @generated from enum value: PAYOUT_STATUS_PAID = 3;
   */
  PAID = 3,

  /**
   * @generated from enum value: PAYOUT_STATUS_FAILED = 4;
   */
  FAILED = 4,

  /**
   * @generated from enum value: PAYOUT_STATUS_CANCELLED = 5;
   */
  CANCELLED = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(PayoutStatus)
proto3.util.setEnumType(PayoutStatus, "iogrid.billing.v1.PayoutStatus", [
  { no: 0, name: "PAYOUT_STATUS_UNSPECIFIED" },
  { no: 1, name: "PAYOUT_STATUS_PENDING" },
  { no: 2, name: "PAYOUT_STATUS_IN_TRANSIT" },
  { no: 3, name: "PAYOUT_STATUS_PAID" },
  { no: 4, name: "PAYOUT_STATUS_FAILED" },
  { no: 5, name: "PAYOUT_STATUS_CANCELLED" },
]);

/**
 * PayoutAccount is the user-level (NOT provider-level) payout binding —
 * a user can own multiple provider machines but receives one consolidated
 * payout per supported currency.
 *
 * @generated from message iogrid.billing.v1.PayoutAccount
 */
export class PayoutAccount extends Message<PayoutAccount> {
  /**
   * @generated from field: iogrid.common.v1.UUID id = 1;
   */
  id?: UUID;

  /**
   * @generated from field: iogrid.common.v1.UUID user_id = 2;
   */
  userId?: UUID;

  /**
   * @generated from field: string stripe_connect_account_id = 3;
   */
  stripeConnectAccountId = "";

  /**
   * @generated from field: iogrid.billing.v1.PayoutAccountStatus status = 4;
   */
  status = PayoutAccountStatus.UNSPECIFIED;

  /**
   * ISO 3166-1 alpha-2 country of the bank account.
   *
   * @generated from field: string country_code = 5;
   */
  countryCode = "";

  /**
   * Default payout currency for this account (ISO 4217).
   *
   * @generated from field: string default_currency = 6;
   */
  defaultCurrency = "";

  /**
   * @generated from field: google.protobuf.Timestamp onboarded_at = 7;
   */
  onboardedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp last_payout_at = 8;
   */
  lastPayoutAt?: Timestamp;

  constructor(data?: PartialMessage<PayoutAccount>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.PayoutAccount";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: UUID },
    { no: 2, name: "user_id", kind: "message", T: UUID },
    { no: 3, name: "stripe_connect_account_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "status", kind: "enum", T: proto3.getEnumType(PayoutAccountStatus) },
    { no: 5, name: "country_code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "default_currency", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "onboarded_at", kind: "message", T: Timestamp },
    { no: 8, name: "last_payout_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PayoutAccount {
    return new PayoutAccount().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PayoutAccount {
    return new PayoutAccount().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PayoutAccount {
    return new PayoutAccount().fromJsonString(jsonString, options);
  }

  static equals(a: PayoutAccount | PlainMessage<PayoutAccount> | undefined, b: PayoutAccount | PlainMessage<PayoutAccount> | undefined): boolean {
    return proto3.util.equals(PayoutAccount, a, b);
  }
}

/**
 * BalanceLedger summarises a user's pending and available balance.
 *
 * @generated from message iogrid.billing.v1.BalanceLedger
 */
export class BalanceLedger extends Message<BalanceLedger> {
  /**
   * @generated from field: iogrid.common.v1.UUID user_id = 1;
   */
  userId?: UUID;

  /**
   * Funds earned but not yet through clearing (held for the dispute
   * window after the workload settled).
   *
   * @generated from field: iogrid.common.v1.Money pending = 2;
   */
  pending?: Money;

  /**
   * Funds eligible for next payout.
   *
   * @generated from field: iogrid.common.v1.Money available = 3;
   */
  available?: Money;

  /**
   * Funds reserved against open disputes / chargebacks.
   *
   * @generated from field: iogrid.common.v1.Money reserved = 4;
   */
  reserved?: Money;

  /**
   * @generated from field: google.protobuf.Timestamp last_updated_at = 5;
   */
  lastUpdatedAt?: Timestamp;

  constructor(data?: PartialMessage<BalanceLedger>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.BalanceLedger";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "message", T: UUID },
    { no: 2, name: "pending", kind: "message", T: Money },
    { no: 3, name: "available", kind: "message", T: Money },
    { no: 4, name: "reserved", kind: "message", T: Money },
    { no: 5, name: "last_updated_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BalanceLedger {
    return new BalanceLedger().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BalanceLedger {
    return new BalanceLedger().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BalanceLedger {
    return new BalanceLedger().fromJsonString(jsonString, options);
  }

  static equals(a: BalanceLedger | PlainMessage<BalanceLedger> | undefined, b: BalanceLedger | PlainMessage<BalanceLedger> | undefined): boolean {
    return proto3.util.equals(BalanceLedger, a, b);
  }
}

/**
 * Payout is the per-period record sent to the provider's bank.
 *
 * @generated from message iogrid.billing.v1.Payout
 */
export class Payout extends Message<Payout> {
  /**
   * @generated from field: iogrid.common.v1.UUID id = 1;
   */
  id?: UUID;

  /**
   * @generated from field: iogrid.common.v1.UUID user_id = 2;
   */
  userId?: UUID;

  /**
   * @generated from field: iogrid.common.v1.UUID payout_account_id = 3;
   */
  payoutAccountId?: UUID;

  /**
   * @generated from field: iogrid.common.v1.Money amount = 4;
   */
  amount?: Money;

  /**
   * @generated from field: iogrid.billing.v1.PayoutStatus status = 5;
   */
  status = PayoutStatus.UNSPECIFIED;

  /**
   * Stripe payout id for cross-reference.
   *
   * @generated from field: string stripe_payout_id = 6;
   */
  stripePayoutId = "";

  /**
   * Period this payout covers.
   *
   * @generated from field: iogrid.common.v1.TimeWindow period = 7;
   */
  period?: TimeWindow;

  /**
   * @generated from field: google.protobuf.Timestamp initiated_at = 8;
   */
  initiatedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp settled_at = 9;
   */
  settledAt?: Timestamp;

  /**
   * For FAILED status: machine-readable Stripe reason.
   *
   * @generated from field: string failure_reason = 10;
   */
  failureReason = "";

  constructor(data?: PartialMessage<Payout>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.Payout";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: UUID },
    { no: 2, name: "user_id", kind: "message", T: UUID },
    { no: 3, name: "payout_account_id", kind: "message", T: UUID },
    { no: 4, name: "amount", kind: "message", T: Money },
    { no: 5, name: "status", kind: "enum", T: proto3.getEnumType(PayoutStatus) },
    { no: 6, name: "stripe_payout_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "period", kind: "message", T: TimeWindow },
    { no: 8, name: "initiated_at", kind: "message", T: Timestamp },
    { no: 9, name: "settled_at", kind: "message", T: Timestamp },
    { no: 10, name: "failure_reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Payout {
    return new Payout().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Payout {
    return new Payout().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Payout {
    return new Payout().fromJsonString(jsonString, options);
  }

  static equals(a: Payout | PlainMessage<Payout> | undefined, b: Payout | PlainMessage<Payout> | undefined): boolean {
    return proto3.util.equals(Payout, a, b);
  }
}

/**
 * @generated from message iogrid.billing.v1.GetPayoutAccountRequest
 */
export class GetPayoutAccountRequest extends Message<GetPayoutAccountRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID user_id = 1;
   */
  userId?: UUID;

  constructor(data?: PartialMessage<GetPayoutAccountRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.GetPayoutAccountRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "message", T: UUID },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPayoutAccountRequest {
    return new GetPayoutAccountRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPayoutAccountRequest {
    return new GetPayoutAccountRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPayoutAccountRequest {
    return new GetPayoutAccountRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetPayoutAccountRequest | PlainMessage<GetPayoutAccountRequest> | undefined, b: GetPayoutAccountRequest | PlainMessage<GetPayoutAccountRequest> | undefined): boolean {
    return proto3.util.equals(GetPayoutAccountRequest, a, b);
  }
}

/**
 * @generated from message iogrid.billing.v1.GetPayoutAccountResponse
 */
export class GetPayoutAccountResponse extends Message<GetPayoutAccountResponse> {
  /**
   * @generated from field: iogrid.billing.v1.PayoutAccount account = 1;
   */
  account?: PayoutAccount;

  constructor(data?: PartialMessage<GetPayoutAccountResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.GetPayoutAccountResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "account", kind: "message", T: PayoutAccount },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPayoutAccountResponse {
    return new GetPayoutAccountResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPayoutAccountResponse {
    return new GetPayoutAccountResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPayoutAccountResponse {
    return new GetPayoutAccountResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetPayoutAccountResponse | PlainMessage<GetPayoutAccountResponse> | undefined, b: GetPayoutAccountResponse | PlainMessage<GetPayoutAccountResponse> | undefined): boolean {
    return proto3.util.equals(GetPayoutAccountResponse, a, b);
  }
}

/**
 * @generated from message iogrid.billing.v1.StartPayoutOnboardingRequest
 */
export class StartPayoutOnboardingRequest extends Message<StartPayoutOnboardingRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID user_id = 1;
   */
  userId?: UUID;

  /**
   * Where Stripe should redirect the browser after onboarding.
   *
   * @generated from field: string return_url = 2;
   */
  returnUrl = "";

  /**
   * Where Stripe should redirect on user-cancel.
   *
   * @generated from field: string refresh_url = 3;
   */
  refreshUrl = "";

  constructor(data?: PartialMessage<StartPayoutOnboardingRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.StartPayoutOnboardingRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "message", T: UUID },
    { no: 2, name: "return_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "refresh_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartPayoutOnboardingRequest {
    return new StartPayoutOnboardingRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartPayoutOnboardingRequest {
    return new StartPayoutOnboardingRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartPayoutOnboardingRequest {
    return new StartPayoutOnboardingRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StartPayoutOnboardingRequest | PlainMessage<StartPayoutOnboardingRequest> | undefined, b: StartPayoutOnboardingRequest | PlainMessage<StartPayoutOnboardingRequest> | undefined): boolean {
    return proto3.util.equals(StartPayoutOnboardingRequest, a, b);
  }
}

/**
 * @generated from message iogrid.billing.v1.StartPayoutOnboardingResponse
 */
export class StartPayoutOnboardingResponse extends Message<StartPayoutOnboardingResponse> {
  /**
   * Stripe Connect onboarding URL.
   *
   * @generated from field: string onboarding_url = 1;
   */
  onboardingUrl = "";

  constructor(data?: PartialMessage<StartPayoutOnboardingResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.StartPayoutOnboardingResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "onboarding_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartPayoutOnboardingResponse {
    return new StartPayoutOnboardingResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartPayoutOnboardingResponse {
    return new StartPayoutOnboardingResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartPayoutOnboardingResponse {
    return new StartPayoutOnboardingResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StartPayoutOnboardingResponse | PlainMessage<StartPayoutOnboardingResponse> | undefined, b: StartPayoutOnboardingResponse | PlainMessage<StartPayoutOnboardingResponse> | undefined): boolean {
    return proto3.util.equals(StartPayoutOnboardingResponse, a, b);
  }
}

/**
 * @generated from message iogrid.billing.v1.GetBalanceRequest
 */
export class GetBalanceRequest extends Message<GetBalanceRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID user_id = 1;
   */
  userId?: UUID;

  constructor(data?: PartialMessage<GetBalanceRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.GetBalanceRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "message", T: UUID },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBalanceRequest {
    return new GetBalanceRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBalanceRequest {
    return new GetBalanceRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBalanceRequest {
    return new GetBalanceRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetBalanceRequest | PlainMessage<GetBalanceRequest> | undefined, b: GetBalanceRequest | PlainMessage<GetBalanceRequest> | undefined): boolean {
    return proto3.util.equals(GetBalanceRequest, a, b);
  }
}

/**
 * @generated from message iogrid.billing.v1.GetBalanceResponse
 */
export class GetBalanceResponse extends Message<GetBalanceResponse> {
  /**
   * @generated from field: iogrid.billing.v1.BalanceLedger ledger = 1;
   */
  ledger?: BalanceLedger;

  constructor(data?: PartialMessage<GetBalanceResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.GetBalanceResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ledger", kind: "message", T: BalanceLedger },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBalanceResponse {
    return new GetBalanceResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBalanceResponse {
    return new GetBalanceResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBalanceResponse {
    return new GetBalanceResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetBalanceResponse | PlainMessage<GetBalanceResponse> | undefined, b: GetBalanceResponse | PlainMessage<GetBalanceResponse> | undefined): boolean {
    return proto3.util.equals(GetBalanceResponse, a, b);
  }
}

/**
 * @generated from message iogrid.billing.v1.ListPayoutsRequest
 */
export class ListPayoutsRequest extends Message<ListPayoutsRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID user_id = 1;
   */
  userId?: UUID;

  /**
   * @generated from field: iogrid.common.v1.PageRequest page = 2;
   */
  page?: PageRequest;

  /**
   * @generated from field: iogrid.common.v1.TimeWindow window = 3;
   */
  window?: TimeWindow;

  constructor(data?: PartialMessage<ListPayoutsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.ListPayoutsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "message", T: UUID },
    { no: 2, name: "page", kind: "message", T: PageRequest },
    { no: 3, name: "window", kind: "message", T: TimeWindow },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListPayoutsRequest {
    return new ListPayoutsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListPayoutsRequest {
    return new ListPayoutsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListPayoutsRequest {
    return new ListPayoutsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListPayoutsRequest | PlainMessage<ListPayoutsRequest> | undefined, b: ListPayoutsRequest | PlainMessage<ListPayoutsRequest> | undefined): boolean {
    return proto3.util.equals(ListPayoutsRequest, a, b);
  }
}

/**
 * @generated from message iogrid.billing.v1.ListPayoutsResponse
 */
export class ListPayoutsResponse extends Message<ListPayoutsResponse> {
  /**
   * @generated from field: repeated iogrid.billing.v1.Payout payouts = 1;
   */
  payouts: Payout[] = [];

  /**
   * @generated from field: iogrid.common.v1.PageResponse page = 2;
   */
  page?: PageResponse;

  constructor(data?: PartialMessage<ListPayoutsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.ListPayoutsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "payouts", kind: "message", T: Payout, repeated: true },
    { no: 2, name: "page", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListPayoutsResponse {
    return new ListPayoutsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListPayoutsResponse {
    return new ListPayoutsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListPayoutsResponse {
    return new ListPayoutsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListPayoutsResponse | PlainMessage<ListPayoutsResponse> | undefined, b: ListPayoutsResponse | PlainMessage<ListPayoutsResponse> | undefined): boolean {
    return proto3.util.equals(ListPayoutsResponse, a, b);
  }
}

/**
 * @generated from message iogrid.billing.v1.RequestInstantPayoutRequest
 */
export class RequestInstantPayoutRequest extends Message<RequestInstantPayoutRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID user_id = 1;
   */
  userId?: UUID;

  /**
   * Caller MUST have a fresh step-up token from identity-svc.
   *
   * @generated from field: string step_up_token = 2;
   */
  stepUpToken = "";

  constructor(data?: PartialMessage<RequestInstantPayoutRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.RequestInstantPayoutRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "message", T: UUID },
    { no: 2, name: "step_up_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestInstantPayoutRequest {
    return new RequestInstantPayoutRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestInstantPayoutRequest {
    return new RequestInstantPayoutRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestInstantPayoutRequest {
    return new RequestInstantPayoutRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RequestInstantPayoutRequest | PlainMessage<RequestInstantPayoutRequest> | undefined, b: RequestInstantPayoutRequest | PlainMessage<RequestInstantPayoutRequest> | undefined): boolean {
    return proto3.util.equals(RequestInstantPayoutRequest, a, b);
  }
}

/**
 * @generated from message iogrid.billing.v1.RequestInstantPayoutResponse
 */
export class RequestInstantPayoutResponse extends Message<RequestInstantPayoutResponse> {
  /**
   * @generated from field: iogrid.billing.v1.Payout payout = 1;
   */
  payout?: Payout;

  constructor(data?: PartialMessage<RequestInstantPayoutResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.billing.v1.RequestInstantPayoutResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "payout", kind: "message", T: Payout },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestInstantPayoutResponse {
    return new RequestInstantPayoutResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestInstantPayoutResponse {
    return new RequestInstantPayoutResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestInstantPayoutResponse {
    return new RequestInstantPayoutResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RequestInstantPayoutResponse | PlainMessage<RequestInstantPayoutResponse> | undefined, b: RequestInstantPayoutResponse | PlainMessage<RequestInstantPayoutResponse> | undefined): boolean {
    return proto3.util.equals(RequestInstantPayoutResponse, a, b);
  }
}

