// Provider payouts via Stripe Connect: KYC onboarding, balance, payout
// history, eligibility checks. Mirrors customer-side subscription.proto.

// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=js"
// @generated from file iogrid/billing/v1/payout.proto (package iogrid.billing.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetBalanceRequest, GetBalanceResponse, GetPayoutAccountRequest, GetPayoutAccountResponse, ListPayoutsRequest, ListPayoutsResponse, RequestInstantPayoutRequest, RequestInstantPayoutResponse, StartPayoutOnboardingRequest, StartPayoutOnboardingResponse } from "./payout_pbjs";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * PayoutService backs the `/provider/payout` page in the management
 * plane plus internal cron jobs that issue periodic payouts.
 *
 * @generated from service iogrid.billing.v1.PayoutService
 */
export const PayoutService = {
  typeName: "iogrid.billing.v1.PayoutService",
  methods: {
    /**
     * @generated from rpc iogrid.billing.v1.PayoutService.GetPayoutAccount
     */
    getPayoutAccount: {
      name: "GetPayoutAccount",
      I: GetPayoutAccountRequest,
      O: GetPayoutAccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.billing.v1.PayoutService.StartPayoutOnboarding
     */
    startPayoutOnboarding: {
      name: "StartPayoutOnboarding",
      I: StartPayoutOnboardingRequest,
      O: StartPayoutOnboardingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.billing.v1.PayoutService.GetBalance
     */
    getBalance: {
      name: "GetBalance",
      I: GetBalanceRequest,
      O: GetBalanceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.billing.v1.PayoutService.ListPayouts
     */
    listPayouts: {
      name: "ListPayouts",
      I: ListPayoutsRequest,
      O: ListPayoutsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.billing.v1.PayoutService.RequestInstantPayout
     */
    requestInstantPayout: {
      name: "RequestInstantPayout",
      I: RequestInstantPayoutRequest,
      O: RequestInstantPayoutResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

