// Package tokens centralises every random-number / cryptographic-hash /
// JWT operation in identity-svc. Keeping these primitives in one place
// makes them easy to audit and stub out in tests.
package tokens

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"fmt"
	"os"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
)

// Random32 returns 32 cryptographically random bytes encoded as a URL-safe
// base64 string (no padding). Used for refresh tokens and magic-link
// tokens — both are opaque blobs, never re-derivable from the public DB.
func Random32() (string, error) {
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("crypto/rand: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}

// SHA256Hex returns hex-encoded SHA-256 of the input. Used to hash refresh
// tokens and magic-link tokens before storage so a DB compromise cannot
// replay outstanding credentials.
func SHA256Hex(in string) string {
	sum := sha256.Sum256([]byte(in))
	return hex.EncodeToString(sum[:])
}

// PKCEVerifier returns a 32-byte URL-safe random string suitable as a PKCE
// `code_verifier` per RFC 7636 §4.1.
func PKCEVerifier() (string, error) {
	return Random32()
}

// PKCEChallengeS256 derives the S256 PKCE challenge from a verifier
// (base64-url(sha256(verifier))).
func PKCEChallengeS256(verifier string) string {
	sum := sha256.Sum256([]byte(verifier))
	return base64.RawURLEncoding.EncodeToString(sum[:])
}

// --- JWT signer -----------------------------------------------------------

// Signer wraps an RSA private key + key id for signing access tokens.
// Public key is exposed for verification by downstream services
// (gateway-bff, proxy-gateway) without needing the secret.
type Signer struct {
	priv      *rsa.PrivateKey
	pub       *rsa.PublicKey
	keyID     string
	issuer    string
	audience  []string
	ttlAccess time.Duration
}

// SignerConfig captures everything Signer needs at boot.
type SignerConfig struct {
	PrivateKeyPath string
	PublicKeyPath  string
	KeyID          string
	Issuer         string
	Audience       []string
	AccessTokenTTL time.Duration
}

// NewSigner loads the RSA keypair from disk and returns a ready signer.
// The keys must be PEM-encoded. In CI, a fresh keypair is generated by
// the testdata bootstrap helper; in prod, k8s mounts a sealed Secret.
func NewSigner(cfg SignerConfig) (*Signer, error) {
	if cfg.PrivateKeyPath == "" || cfg.PublicKeyPath == "" {
		return nil, fmt.Errorf("tokens: JWT key paths must be set")
	}
	privBytes, err := os.ReadFile(cfg.PrivateKeyPath)
	if err != nil {
		return nil, fmt.Errorf("read private key %q: %w", cfg.PrivateKeyPath, err)
	}
	pubBytes, err := os.ReadFile(cfg.PublicKeyPath)
	if err != nil {
		return nil, fmt.Errorf("read public key %q: %w", cfg.PublicKeyPath, err)
	}
	priv, err := jwt.ParseRSAPrivateKeyFromPEM(privBytes)
	if err != nil {
		return nil, fmt.Errorf("parse private key: %w", err)
	}
	pub, err := jwt.ParseRSAPublicKeyFromPEM(pubBytes)
	if err != nil {
		return nil, fmt.Errorf("parse public key: %w", err)
	}
	return &Signer{
		priv:      priv,
		pub:       pub,
		keyID:     cfg.KeyID,
		issuer:    cfg.Issuer,
		audience:  cfg.Audience,
		ttlAccess: cfg.AccessTokenTTL,
	}, nil
}

// NewSignerFromKeys is the test-friendly constructor that accepts an
// in-memory RSA key instead of disk paths.
func NewSignerFromKeys(priv *rsa.PrivateKey, keyID, issuer string, audience []string, ttl time.Duration) *Signer {
	return &Signer{
		priv:      priv,
		pub:       &priv.PublicKey,
		keyID:     keyID,
		issuer:    issuer,
		audience:  audience,
		ttlAccess: ttl,
	}
}

// AccessClaims is the structured payload for our RS256 access token.
// Mirrors the JwtClaims proto so downstream services can deserialize
// uniformly.
type AccessClaims struct {
	jwt.RegisteredClaims
	Identifiers  []string `json:"identifiers,omitempty"`
	PrimaryEmail string   `json:"primary_email,omitempty"`
	Roles        []string `json:"roles,omitempty"`
	StepUp       bool     `json:"step_up,omitempty"`
}

// IssueAccessToken signs a fresh access token for the given user/session.
func (s *Signer) IssueAccessToken(userID, sessionID uuid.UUID, primaryEmail string, roles, identifiers []string, stepUp bool) (string, time.Time, error) {
	now := time.Now().UTC()
	exp := now.Add(s.ttlAccess)
	claims := AccessClaims{
		RegisteredClaims: jwt.RegisteredClaims{
			Subject:   userID.String(),
			Issuer:    s.issuer,
			Audience:  jwt.ClaimStrings(s.audience),
			IssuedAt:  jwt.NewNumericDate(now),
			ExpiresAt: jwt.NewNumericDate(exp),
			ID:        sessionID.String(),
		},
		Identifiers:  identifiers,
		PrimaryEmail: primaryEmail,
		Roles:        roles,
		StepUp:       stepUp,
	}
	t := jwt.NewWithClaims(jwt.SigningMethodRS256, claims)
	t.Header["kid"] = s.keyID
	tok, err := t.SignedString(s.priv)
	if err != nil {
		return "", time.Time{}, fmt.Errorf("sign access token: %w", err)
	}
	return tok, exp, nil
}

// Verify validates the token and returns the parsed claims. Returns an
// error if the signature is invalid, the token is expired, or the
// issuer/audience do not match.
func (s *Signer) Verify(token string) (*AccessClaims, error) {
	claims := &AccessClaims{}
	tok, err := jwt.ParseWithClaims(token, claims, func(t *jwt.Token) (any, error) {
		if t.Method.Alg() != jwt.SigningMethodRS256.Alg() {
			return nil, fmt.Errorf("unexpected alg: %v", t.Method.Alg())
		}
		return s.pub, nil
	}, jwt.WithIssuer(s.issuer))
	if err != nil {
		return nil, err
	}
	if !tok.Valid {
		return nil, errors.New("token invalid")
	}
	return claims, nil
}

// PublicKeyPEM returns the PEM-encoded public key for distribution to
// downstream verifiers (gateway-bff JWKS endpoint).
func (s *Signer) PublicKeyPEM() ([]byte, error) {
	der, err := x509.MarshalPKIXPublicKey(s.pub)
	if err != nil {
		return nil, err
	}
	return pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: der}), nil
}

// KeyID exposes the kid header used when signing.
func (s *Signer) KeyID() string { return s.keyID }
