// Provider registration and capability inventory. Called by the Rust
// daemon during first-run pairing and on every reconnect to refresh its
// advertised capabilities.

// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=js"
// @generated from file iogrid/providers/v1/registration.proto (package iogrid.providers.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeactivateProviderRequest, DeactivateProviderResponse, GetProviderRequest, GetProviderResponse, IssuePairingTokenRequest, IssuePairingTokenResponse, ListProvidersRequest, ListProvidersResponse, PairDaemonRequest, PairDaemonResponse, UpdateCapabilityInventoryRequest, UpdateCapabilityInventoryResponse, UpdateHostInfoRequest, UpdateHostInfoResponse } from "./registration_pbjs";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ProviderRegistrationService is called by the Rust daemon (pair, update)
 * and by the management plane (token issuance, read, deactivate).
 *
 * @generated from service iogrid.providers.v1.ProviderRegistrationService
 */
export const ProviderRegistrationService = {
  typeName: "iogrid.providers.v1.ProviderRegistrationService",
  methods: {
    /**
     * @generated from rpc iogrid.providers.v1.ProviderRegistrationService.IssuePairingToken
     */
    issuePairingToken: {
      name: "IssuePairingToken",
      I: IssuePairingTokenRequest,
      O: IssuePairingTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.providers.v1.ProviderRegistrationService.PairDaemon
     */
    pairDaemon: {
      name: "PairDaemon",
      I: PairDaemonRequest,
      O: PairDaemonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.providers.v1.ProviderRegistrationService.UpdateHostInfo
     */
    updateHostInfo: {
      name: "UpdateHostInfo",
      I: UpdateHostInfoRequest,
      O: UpdateHostInfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.providers.v1.ProviderRegistrationService.UpdateCapabilityInventory
     */
    updateCapabilityInventory: {
      name: "UpdateCapabilityInventory",
      I: UpdateCapabilityInventoryRequest,
      O: UpdateCapabilityInventoryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.providers.v1.ProviderRegistrationService.GetProvider
     */
    getProvider: {
      name: "GetProvider",
      I: GetProviderRequest,
      O: GetProviderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.providers.v1.ProviderRegistrationService.ListProviders
     */
    listProviders: {
      name: "ListProviders",
      I: ListProvidersRequest,
      O: ListProvidersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.providers.v1.ProviderRegistrationService.DeactivateProvider
     */
    deactivateProvider: {
      name: "DeactivateProvider",
      I: DeactivateProviderRequest,
      O: DeactivateProviderResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

