// Scheduling: combined cap + calendar + idle-only state machine.
//
// Three independent signals AND together to gate workload acceptance,
// mirroring the Rust enum in daemon/crates/scheduler. The coordinator
// stores the desired config; the daemon evaluates it locally and reports
// its computed state back via streaming heartbeats.

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=js"
// @generated from file iogrid/providers/v1/scheduling.proto (package iogrid.providers.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";
import { UUID } from "../../common/v1/types_pbjs";

/**
 * SchedulerState is the daemon's computed gate. Reported on every
 * heartbeat; mirrors the SchedulerState enum in the Rust daemon.
 *
 * @generated from enum iogrid.providers.v1.SchedulerState
 */
export enum SchedulerState {
  /**
   * @generated from enum value: SCHEDULER_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SCHEDULER_STATE_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: SCHEDULER_STATE_PAUSED_BANDWIDTH_CAP = 2;
   */
  PAUSED_BANDWIDTH_CAP = 2,

  /**
   * @generated from enum value: SCHEDULER_STATE_PAUSED_CPU_CAP = 3;
   */
  PAUSED_CPU_CAP = 3,

  /**
   * @generated from enum value: SCHEDULER_STATE_PAUSED_MEMORY_CAP = 4;
   */
  PAUSED_MEMORY_CAP = 4,

  /**
   * @generated from enum value: SCHEDULER_STATE_PAUSED_OUTSIDE_CALENDAR = 5;
   */
  PAUSED_OUTSIDE_CALENDAR = 5,

  /**
   * @generated from enum value: SCHEDULER_STATE_PAUSED_USER_ACTIVE = 6;
   */
  PAUSED_USER_ACTIVE = 6,

  /**
   * manual override by staff
   *
   * @generated from enum value: SCHEDULER_STATE_PAUSED_OPERATIONS = 7;
   */
  PAUSED_OPERATIONS = 7,
}
// Retrieve enum metadata with: proto3.getEnumType(SchedulerState)
proto3.util.setEnumType(SchedulerState, "iogrid.providers.v1.SchedulerState", [
  { no: 0, name: "SCHEDULER_STATE_UNSPECIFIED" },
  { no: 1, name: "SCHEDULER_STATE_ACTIVE" },
  { no: 2, name: "SCHEDULER_STATE_PAUSED_BANDWIDTH_CAP" },
  { no: 3, name: "SCHEDULER_STATE_PAUSED_CPU_CAP" },
  { no: 4, name: "SCHEDULER_STATE_PAUSED_MEMORY_CAP" },
  { no: 5, name: "SCHEDULER_STATE_PAUSED_OUTSIDE_CALENDAR" },
  { no: 6, name: "SCHEDULER_STATE_PAUSED_USER_ACTIVE" },
  { no: 7, name: "SCHEDULER_STATE_PAUSED_OPERATIONS" },
]);

/**
 * ResourceCaps bounds bandwidth / CPU / RAM / GPU usage. The daemon
 * enforces these locally; the coordinator uses them as input to the
 * metering pipeline (also publishes "approaching cap" warnings).
 *
 * @generated from message iogrid.providers.v1.ResourceCaps
 */
export class ResourceCaps extends Message<ResourceCaps> {
  /**
   * Monthly bandwidth budget in gigabytes (default 50).
   *
   * @generated from field: uint32 bandwidth_cap_gb_per_month = 1;
   */
  bandwidthCapGbPerMonth = 0;

  /**
   * Hard ceiling for sustained CPU usage as percent (0-100, default 30).
   *
   * @generated from field: uint32 cpu_cap_percent = 2;
   */
  cpuCapPercent = 0;

  /**
   * Hard ceiling for RAM usage as percent of system RAM (default 25).
   *
   * @generated from field: uint32 memory_cap_percent = 3;
   */
  memoryCapPercent = 0;

  /**
   * GPU usage ceiling as percent when system is idle (default 100).
   *
   * @generated from field: uint32 gpu_cap_percent_when_idle = 4;
   */
  gpuCapPercentWhenIdle = 0;

  /**
   * GPU usage ceiling as percent when user is active (default 0).
   *
   * @generated from field: uint32 gpu_cap_percent_when_active = 5;
   */
  gpuCapPercentWhenActive = 0;

  constructor(data?: PartialMessage<ResourceCaps>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.providers.v1.ResourceCaps";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "bandwidth_cap_gb_per_month", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "cpu_cap_percent", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "memory_cap_percent", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "gpu_cap_percent_when_idle", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 5, name: "gpu_cap_percent_when_active", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResourceCaps {
    return new ResourceCaps().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResourceCaps {
    return new ResourceCaps().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResourceCaps {
    return new ResourceCaps().fromJsonString(jsonString, options);
  }

  static equals(a: ResourceCaps | PlainMessage<ResourceCaps> | undefined, b: ResourceCaps | PlainMessage<ResourceCaps> | undefined): boolean {
    return proto3.util.equals(ResourceCaps, a, b);
  }
}

/**
 * CalendarWindow is a recurring weekly active interval, e.g. "weeknights
 * 22:00–07:00". Days-of-week are bit-set; times are 24h local clock.
 *
 * @generated from message iogrid.providers.v1.CalendarWindow
 */
export class CalendarWindow extends Message<CalendarWindow> {
  /**
   * ISO 8601 weekday set (Monday=1 ... Sunday=7) when the window applies.
   *
   * @generated from field: repeated uint32 days_of_week = 1;
   */
  daysOfWeek: number[] = [];

  /**
   * Start local time in HH:MM (24h) form, e.g. "22:00".
   *
   * @generated from field: string start_local_time = 2;
   */
  startLocalTime = "";

  /**
   * End local time in HH:MM form. If end < start, window wraps midnight.
   *
   * @generated from field: string end_local_time = 3;
   */
  endLocalTime = "";

  /**
   * IANA timezone, e.g. "America/New_York".
   *
   * @generated from field: string timezone = 4;
   */
  timezone = "";

  constructor(data?: PartialMessage<CalendarWindow>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.providers.v1.CalendarWindow";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "days_of_week", kind: "scalar", T: 13 /* ScalarType.UINT32 */, repeated: true },
    { no: 2, name: "start_local_time", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "end_local_time", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "timezone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CalendarWindow {
    return new CalendarWindow().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CalendarWindow {
    return new CalendarWindow().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CalendarWindow {
    return new CalendarWindow().fromJsonString(jsonString, options);
  }

  static equals(a: CalendarWindow | PlainMessage<CalendarWindow> | undefined, b: CalendarWindow | PlainMessage<CalendarWindow> | undefined): boolean {
    return proto3.util.equals(CalendarWindow, a, b);
  }
}

/**
 * CalendarSchedule is the full calendar setting. Empty windows array
 * means "always active" (the default).
 *
 * @generated from message iogrid.providers.v1.CalendarSchedule
 */
export class CalendarSchedule extends Message<CalendarSchedule> {
  /**
   * @generated from field: repeated iogrid.providers.v1.CalendarWindow windows = 1;
   */
  windows: CalendarWindow[] = [];

  constructor(data?: PartialMessage<CalendarSchedule>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.providers.v1.CalendarSchedule";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "windows", kind: "message", T: CalendarWindow, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CalendarSchedule {
    return new CalendarSchedule().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CalendarSchedule {
    return new CalendarSchedule().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CalendarSchedule {
    return new CalendarSchedule().fromJsonString(jsonString, options);
  }

  static equals(a: CalendarSchedule | PlainMessage<CalendarSchedule> | undefined, b: CalendarSchedule | PlainMessage<CalendarSchedule> | undefined): boolean {
    return proto3.util.equals(CalendarSchedule, a, b);
  }
}

/**
 * IdleDetection configures the "only run when user is away" gate.
 *
 * @generated from message iogrid.providers.v1.IdleDetection
 */
export class IdleDetection extends Message<IdleDetection> {
  /**
   * True when this gate is enabled (default true).
   *
   * @generated from field: bool enabled = 1;
   */
  enabled = false;

  /**
   * How many seconds of input inactivity count as "idle" (default 300).
   *
   * @generated from field: uint32 idle_threshold_seconds = 2;
   */
  idleThresholdSeconds = 0;

  constructor(data?: PartialMessage<IdleDetection>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.providers.v1.IdleDetection";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "idle_threshold_seconds", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdleDetection {
    return new IdleDetection().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdleDetection {
    return new IdleDetection().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdleDetection {
    return new IdleDetection().fromJsonString(jsonString, options);
  }

  static equals(a: IdleDetection | PlainMessage<IdleDetection> | undefined, b: IdleDetection | PlainMessage<IdleDetection> | undefined): boolean {
    return proto3.util.equals(IdleDetection, a, b);
  }
}

/**
 * CategoryOptIn lists workload categories the provider has opted into.
 * (See antiabuse/v1/filters.proto for the full category enum.) Empty
 * list means "use platform defaults" (e-commerce/SEO/ad-verif/etc).
 *
 * @generated from message iogrid.providers.v1.CategoryOptIn
 */
export class CategoryOptIn extends Message<CategoryOptIn> {
  /**
   * Canonical category slugs, e.g. "e_commerce", "seo", "ad_verification".
   *
   * @generated from field: repeated string allowed_categories = 1;
   */
  allowedCategories: string[] = [];

  /**
   * Categories explicitly disallowed even if added to the defaults later.
   *
   * @generated from field: repeated string disallowed_categories = 2;
   */
  disallowedCategories: string[] = [];

  constructor(data?: PartialMessage<CategoryOptIn>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.providers.v1.CategoryOptIn";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "allowed_categories", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "disallowed_categories", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CategoryOptIn {
    return new CategoryOptIn().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CategoryOptIn {
    return new CategoryOptIn().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CategoryOptIn {
    return new CategoryOptIn().fromJsonString(jsonString, options);
  }

  static equals(a: CategoryOptIn | PlainMessage<CategoryOptIn> | undefined, b: CategoryOptIn | PlainMessage<CategoryOptIn> | undefined): boolean {
    return proto3.util.equals(CategoryOptIn, a, b);
  }
}

/**
 * DestinationPolicy: per-host blocklist + per-customer rate limit.
 *
 * @generated from message iogrid.providers.v1.DestinationPolicy
 */
export class DestinationPolicy extends Message<DestinationPolicy> {
  /**
   * Domain patterns the provider refuses to relay to (e.g. "*.chase.com",
   * "*.linkedin.com"). Matches via glob, case-insensitive.
   *
   * @generated from field: repeated string destination_blocklist = 1;
   */
  destinationBlocklist: string[] = [];

  /**
   * Max consecutive minutes a single customer can hold this provider's
   * IP before auto-rotation. 0 means unlimited.
   *
   * @generated from field: uint32 per_customer_minutes_cap = 2;
   */
  perCustomerMinutesCap = 0;

  constructor(data?: PartialMessage<DestinationPolicy>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.providers.v1.DestinationPolicy";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "destination_blocklist", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "per_customer_minutes_cap", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DestinationPolicy {
    return new DestinationPolicy().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DestinationPolicy {
    return new DestinationPolicy().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DestinationPolicy {
    return new DestinationPolicy().fromJsonString(jsonString, options);
  }

  static equals(a: DestinationPolicy | PlainMessage<DestinationPolicy> | undefined, b: DestinationPolicy | PlainMessage<DestinationPolicy> | undefined): boolean {
    return proto3.util.equals(DestinationPolicy, a, b);
  }
}

/**
 * SchedulingConfig is the desired-state for a single provider.
 *
 * @generated from message iogrid.providers.v1.SchedulingConfig
 */
export class SchedulingConfig extends Message<SchedulingConfig> {
  /**
   * @generated from field: iogrid.common.v1.UUID provider_id = 1;
   */
  providerId?: UUID;

  /**
   * @generated from field: iogrid.providers.v1.ResourceCaps caps = 2;
   */
  caps?: ResourceCaps;

  /**
   * @generated from field: iogrid.providers.v1.CalendarSchedule calendar = 3;
   */
  calendar?: CalendarSchedule;

  /**
   * @generated from field: iogrid.providers.v1.IdleDetection idle = 4;
   */
  idle?: IdleDetection;

  /**
   * @generated from field: iogrid.providers.v1.CategoryOptIn category_opt_in = 5;
   */
  categoryOptIn?: CategoryOptIn;

  /**
   * @generated from field: iogrid.providers.v1.DestinationPolicy destination_policy = 6;
   */
  destinationPolicy?: DestinationPolicy;

  /**
   * Server-side audit fields.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 7;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: iogrid.common.v1.UUID updated_by_user_id = 8;
   */
  updatedByUserId?: UUID;

  constructor(data?: PartialMessage<SchedulingConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.providers.v1.SchedulingConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "provider_id", kind: "message", T: UUID },
    { no: 2, name: "caps", kind: "message", T: ResourceCaps },
    { no: 3, name: "calendar", kind: "message", T: CalendarSchedule },
    { no: 4, name: "idle", kind: "message", T: IdleDetection },
    { no: 5, name: "category_opt_in", kind: "message", T: CategoryOptIn },
    { no: 6, name: "destination_policy", kind: "message", T: DestinationPolicy },
    { no: 7, name: "updated_at", kind: "message", T: Timestamp },
    { no: 8, name: "updated_by_user_id", kind: "message", T: UUID },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SchedulingConfig {
    return new SchedulingConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SchedulingConfig {
    return new SchedulingConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SchedulingConfig {
    return new SchedulingConfig().fromJsonString(jsonString, options);
  }

  static equals(a: SchedulingConfig | PlainMessage<SchedulingConfig> | undefined, b: SchedulingConfig | PlainMessage<SchedulingConfig> | undefined): boolean {
    return proto3.util.equals(SchedulingConfig, a, b);
  }
}

/**
 * CurrentUsageSnapshot is the daemon's latest measured usage. Used by
 * the management plane to render the cap progress bars.
 *
 * @generated from message iogrid.providers.v1.CurrentUsageSnapshot
 */
export class CurrentUsageSnapshot extends Message<CurrentUsageSnapshot> {
  /**
   * @generated from field: uint64 bandwidth_used_bytes_this_month = 1;
   */
  bandwidthUsedBytesThisMonth = protoInt64.zero;

  /**
   * @generated from field: uint32 cpu_percent = 2;
   */
  cpuPercent = 0;

  /**
   * @generated from field: uint32 memory_percent = 3;
   */
  memoryPercent = 0;

  /**
   * @generated from field: uint32 gpu_percent = 4;
   */
  gpuPercent = 0;

  /**
   * Seconds since last detected user input (0 if active).
   *
   * @generated from field: uint32 idle_seconds = 5;
   */
  idleSeconds = 0;

  /**
   * @generated from field: google.protobuf.Timestamp observed_at = 6;
   */
  observedAt?: Timestamp;

  constructor(data?: PartialMessage<CurrentUsageSnapshot>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.providers.v1.CurrentUsageSnapshot";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "bandwidth_used_bytes_this_month", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "cpu_percent", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "memory_percent", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "gpu_percent", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 5, name: "idle_seconds", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 6, name: "observed_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CurrentUsageSnapshot {
    return new CurrentUsageSnapshot().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CurrentUsageSnapshot {
    return new CurrentUsageSnapshot().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CurrentUsageSnapshot {
    return new CurrentUsageSnapshot().fromJsonString(jsonString, options);
  }

  static equals(a: CurrentUsageSnapshot | PlainMessage<CurrentUsageSnapshot> | undefined, b: CurrentUsageSnapshot | PlainMessage<CurrentUsageSnapshot> | undefined): boolean {
    return proto3.util.equals(CurrentUsageSnapshot, a, b);
  }
}

/**
 * @generated from message iogrid.providers.v1.GetSchedulingConfigRequest
 */
export class GetSchedulingConfigRequest extends Message<GetSchedulingConfigRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID provider_id = 1;
   */
  providerId?: UUID;

  constructor(data?: PartialMessage<GetSchedulingConfigRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.providers.v1.GetSchedulingConfigRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "provider_id", kind: "message", T: UUID },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSchedulingConfigRequest {
    return new GetSchedulingConfigRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSchedulingConfigRequest {
    return new GetSchedulingConfigRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSchedulingConfigRequest {
    return new GetSchedulingConfigRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetSchedulingConfigRequest | PlainMessage<GetSchedulingConfigRequest> | undefined, b: GetSchedulingConfigRequest | PlainMessage<GetSchedulingConfigRequest> | undefined): boolean {
    return proto3.util.equals(GetSchedulingConfigRequest, a, b);
  }
}

/**
 * @generated from message iogrid.providers.v1.GetSchedulingConfigResponse
 */
export class GetSchedulingConfigResponse extends Message<GetSchedulingConfigResponse> {
  /**
   * @generated from field: iogrid.providers.v1.SchedulingConfig config = 1;
   */
  config?: SchedulingConfig;

  constructor(data?: PartialMessage<GetSchedulingConfigResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.providers.v1.GetSchedulingConfigResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "config", kind: "message", T: SchedulingConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSchedulingConfigResponse {
    return new GetSchedulingConfigResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSchedulingConfigResponse {
    return new GetSchedulingConfigResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSchedulingConfigResponse {
    return new GetSchedulingConfigResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetSchedulingConfigResponse | PlainMessage<GetSchedulingConfigResponse> | undefined, b: GetSchedulingConfigResponse | PlainMessage<GetSchedulingConfigResponse> | undefined): boolean {
    return proto3.util.equals(GetSchedulingConfigResponse, a, b);
  }
}

/**
 * @generated from message iogrid.providers.v1.UpdateSchedulingConfigRequest
 */
export class UpdateSchedulingConfigRequest extends Message<UpdateSchedulingConfigRequest> {
  /**
   * Full replacement semantics — caller must read-modify-write. Server
   * rejects with FAILED_PRECONDITION if updated_at doesn't match.
   *
   * @generated from field: iogrid.providers.v1.SchedulingConfig config = 1;
   */
  config?: SchedulingConfig;

  constructor(data?: PartialMessage<UpdateSchedulingConfigRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.providers.v1.UpdateSchedulingConfigRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "config", kind: "message", T: SchedulingConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateSchedulingConfigRequest {
    return new UpdateSchedulingConfigRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateSchedulingConfigRequest {
    return new UpdateSchedulingConfigRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateSchedulingConfigRequest {
    return new UpdateSchedulingConfigRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateSchedulingConfigRequest | PlainMessage<UpdateSchedulingConfigRequest> | undefined, b: UpdateSchedulingConfigRequest | PlainMessage<UpdateSchedulingConfigRequest> | undefined): boolean {
    return proto3.util.equals(UpdateSchedulingConfigRequest, a, b);
  }
}

/**
 * @generated from message iogrid.providers.v1.UpdateSchedulingConfigResponse
 */
export class UpdateSchedulingConfigResponse extends Message<UpdateSchedulingConfigResponse> {
  /**
   * @generated from field: iogrid.providers.v1.SchedulingConfig config = 1;
   */
  config?: SchedulingConfig;

  constructor(data?: PartialMessage<UpdateSchedulingConfigResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.providers.v1.UpdateSchedulingConfigResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "config", kind: "message", T: SchedulingConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateSchedulingConfigResponse {
    return new UpdateSchedulingConfigResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateSchedulingConfigResponse {
    return new UpdateSchedulingConfigResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateSchedulingConfigResponse {
    return new UpdateSchedulingConfigResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateSchedulingConfigResponse | PlainMessage<UpdateSchedulingConfigResponse> | undefined, b: UpdateSchedulingConfigResponse | PlainMessage<UpdateSchedulingConfigResponse> | undefined): boolean {
    return proto3.util.equals(UpdateSchedulingConfigResponse, a, b);
  }
}

/**
 * @generated from message iogrid.providers.v1.GetCurrentStateRequest
 */
export class GetCurrentStateRequest extends Message<GetCurrentStateRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID provider_id = 1;
   */
  providerId?: UUID;

  constructor(data?: PartialMessage<GetCurrentStateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.providers.v1.GetCurrentStateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "provider_id", kind: "message", T: UUID },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCurrentStateRequest {
    return new GetCurrentStateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCurrentStateRequest {
    return new GetCurrentStateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCurrentStateRequest {
    return new GetCurrentStateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetCurrentStateRequest | PlainMessage<GetCurrentStateRequest> | undefined, b: GetCurrentStateRequest | PlainMessage<GetCurrentStateRequest> | undefined): boolean {
    return proto3.util.equals(GetCurrentStateRequest, a, b);
  }
}

/**
 * @generated from message iogrid.providers.v1.GetCurrentStateResponse
 */
export class GetCurrentStateResponse extends Message<GetCurrentStateResponse> {
  /**
   * @generated from field: iogrid.providers.v1.SchedulerState state = 1;
   */
  state = SchedulerState.UNSPECIFIED;

  /**
   * @generated from field: iogrid.providers.v1.CurrentUsageSnapshot usage = 2;
   */
  usage?: CurrentUsageSnapshot;

  /**
   * When the next scheduled transition is expected (e.g. when the
   * calendar window opens / closes). Unset when no transition is known.
   *
   * @generated from field: google.protobuf.Timestamp next_transition_at = 3;
   */
  nextTransitionAt?: Timestamp;

  constructor(data?: PartialMessage<GetCurrentStateResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.providers.v1.GetCurrentStateResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "state", kind: "enum", T: proto3.getEnumType(SchedulerState) },
    { no: 2, name: "usage", kind: "message", T: CurrentUsageSnapshot },
    { no: 3, name: "next_transition_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCurrentStateResponse {
    return new GetCurrentStateResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCurrentStateResponse {
    return new GetCurrentStateResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCurrentStateResponse {
    return new GetCurrentStateResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetCurrentStateResponse | PlainMessage<GetCurrentStateResponse> | undefined, b: GetCurrentStateResponse | PlainMessage<GetCurrentStateResponse> | undefined): boolean {
    return proto3.util.equals(GetCurrentStateResponse, a, b);
  }
}

/**
 * Heartbeat is streamed from daemon → coordinator at ~5s intervals.
 *
 * @generated from message iogrid.providers.v1.Heartbeat
 */
export class Heartbeat extends Message<Heartbeat> {
  /**
   * @generated from field: iogrid.common.v1.UUID provider_id = 1;
   */
  providerId?: UUID;

  /**
   * @generated from field: iogrid.providers.v1.SchedulerState state = 2;
   */
  state = SchedulerState.UNSPECIFIED;

  /**
   * @generated from field: iogrid.providers.v1.CurrentUsageSnapshot usage = 3;
   */
  usage?: CurrentUsageSnapshot;

  /**
   * Monotonic counter for ordering, since timestamps can skew.
   *
   * @generated from field: uint64 sequence = 4;
   */
  sequence = protoInt64.zero;

  /**
   * Time spent processing workloads since last heartbeat.
   *
   * @generated from field: google.protobuf.Duration active_duration = 5;
   */
  activeDuration?: Duration;

  constructor(data?: PartialMessage<Heartbeat>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.providers.v1.Heartbeat";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "provider_id", kind: "message", T: UUID },
    { no: 2, name: "state", kind: "enum", T: proto3.getEnumType(SchedulerState) },
    { no: 3, name: "usage", kind: "message", T: CurrentUsageSnapshot },
    { no: 4, name: "sequence", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "active_duration", kind: "message", T: Duration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Heartbeat {
    return new Heartbeat().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Heartbeat {
    return new Heartbeat().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Heartbeat {
    return new Heartbeat().fromJsonString(jsonString, options);
  }

  static equals(a: Heartbeat | PlainMessage<Heartbeat> | undefined, b: Heartbeat | PlainMessage<Heartbeat> | undefined): boolean {
    return proto3.util.equals(Heartbeat, a, b);
  }
}

/**
 * @generated from message iogrid.providers.v1.HeartbeatAck
 */
export class HeartbeatAck extends Message<HeartbeatAck> {
  /**
   * Server may push an immediate config refresh on top of the ack.
   *
   * @generated from field: bool config_changed = 1;
   */
  configChanged = false;

  /**
   * Server-side directive to pause for operations reasons.
   *
   * @generated from field: bool operations_pause = 2;
   */
  operationsPause = false;

  constructor(data?: PartialMessage<HeartbeatAck>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.providers.v1.HeartbeatAck";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "config_changed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "operations_pause", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HeartbeatAck {
    return new HeartbeatAck().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HeartbeatAck {
    return new HeartbeatAck().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HeartbeatAck {
    return new HeartbeatAck().fromJsonString(jsonString, options);
  }

  static equals(a: HeartbeatAck | PlainMessage<HeartbeatAck> | undefined, b: HeartbeatAck | PlainMessage<HeartbeatAck> | undefined): boolean {
    return proto3.util.equals(HeartbeatAck, a, b);
  }
}

