// Scheduling: combined cap + calendar + idle-only state machine.
//
// Three independent signals AND together to gate workload acceptance,
// mirroring the Rust enum in daemon/crates/scheduler. The coordinator
// stores the desired config; the daemon evaluates it locally and reports
// its computed state back via streaming heartbeats.

// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=js"
// @generated from file iogrid/providers/v1/scheduling.proto (package iogrid.providers.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetCurrentStateRequest, GetCurrentStateResponse, GetSchedulingConfigRequest, GetSchedulingConfigResponse, Heartbeat, HeartbeatAck, UpdateSchedulingConfigRequest, UpdateSchedulingConfigResponse } from "./scheduling_pbjs";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * SchedulingService manages the desired-state config plus the live
 * state-stream from each daemon.
 *
 * @generated from service iogrid.providers.v1.SchedulingService
 */
export const SchedulingService = {
  typeName: "iogrid.providers.v1.SchedulingService",
  methods: {
    /**
     * @generated from rpc iogrid.providers.v1.SchedulingService.GetSchedulingConfig
     */
    getSchedulingConfig: {
      name: "GetSchedulingConfig",
      I: GetSchedulingConfigRequest,
      O: GetSchedulingConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.providers.v1.SchedulingService.UpdateSchedulingConfig
     */
    updateSchedulingConfig: {
      name: "UpdateSchedulingConfig",
      I: UpdateSchedulingConfigRequest,
      O: UpdateSchedulingConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc iogrid.providers.v1.SchedulingService.GetCurrentState
     */
    getCurrentState: {
      name: "GetCurrentState",
      I: GetCurrentStateRequest,
      O: GetCurrentStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Bidirectional heartbeat stream. Daemon sends Heartbeat; server
     * replies with HeartbeatAck (may include config-change flags).
     *
     * @generated from rpc iogrid.providers.v1.SchedulingService.StreamHeartbeats
     */
    streamHeartbeats: {
      name: "StreamHeartbeats",
      I: Heartbeat,
      O: HeartbeatAck,
      kind: MethodKind.BiDiStreaming,
    },
  }
} as const;

