apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iogrid
resources:
  - statefulset.yaml
  - service.yaml
  - bootstrap-job.yaml
commonLabels:
  app.kubernetes.io/part-of: iogrid
  app.kubernetes.io/component: solana-test-validator
