// Transparency dashboard: real-time + historical event feed of what is
// happening through the provider's IP. Backed server-side by NATS
// JetStream → SSE. Clients (web management plane + daemon-local UI) can
// either pull historical pages or subscribe to the live stream.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: iogrid/providers/v1/dashboard.proto

package providersv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/iogrid/iogrid/coordinator/internal/pb/iogrid/providers/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DashboardServiceName is the fully-qualified name of the DashboardService service.
	DashboardServiceName = "iogrid.providers.v1.DashboardService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DashboardServiceListAuditEventsProcedure is the fully-qualified name of the DashboardService's
	// ListAuditEvents RPC.
	DashboardServiceListAuditEventsProcedure = "/iogrid.providers.v1.DashboardService/ListAuditEvents"
	// DashboardServiceStreamAuditEventsProcedure is the fully-qualified name of the DashboardService's
	// StreamAuditEvents RPC.
	DashboardServiceStreamAuditEventsProcedure = "/iogrid.providers.v1.DashboardService/StreamAuditEvents"
	// DashboardServiceGetEarningsSummaryProcedure is the fully-qualified name of the DashboardService's
	// GetEarningsSummary RPC.
	DashboardServiceGetEarningsSummaryProcedure = "/iogrid.providers.v1.DashboardService/GetEarningsSummary"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	dashboardServiceServiceDescriptor                  = v1.File_iogrid_providers_v1_dashboard_proto.Services().ByName("DashboardService")
	dashboardServiceListAuditEventsMethodDescriptor    = dashboardServiceServiceDescriptor.Methods().ByName("ListAuditEvents")
	dashboardServiceStreamAuditEventsMethodDescriptor  = dashboardServiceServiceDescriptor.Methods().ByName("StreamAuditEvents")
	dashboardServiceGetEarningsSummaryMethodDescriptor = dashboardServiceServiceDescriptor.Methods().ByName("GetEarningsSummary")
)

// DashboardServiceClient is a client for the iogrid.providers.v1.DashboardService service.
type DashboardServiceClient interface {
	ListAuditEvents(context.Context, *connect.Request[v1.ListAuditEventsRequest]) (*connect.Response[v1.ListAuditEventsResponse], error)
	StreamAuditEvents(context.Context, *connect.Request[v1.StreamAuditEventsRequest]) (*connect.ServerStreamForClient[v1.AuditEvent], error)
	GetEarningsSummary(context.Context, *connect.Request[v1.GetEarningsSummaryRequest]) (*connect.Response[v1.GetEarningsSummaryResponse], error)
}

// NewDashboardServiceClient constructs a client for the iogrid.providers.v1.DashboardService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDashboardServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DashboardServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &dashboardServiceClient{
		listAuditEvents: connect.NewClient[v1.ListAuditEventsRequest, v1.ListAuditEventsResponse](
			httpClient,
			baseURL+DashboardServiceListAuditEventsProcedure,
			connect.WithSchema(dashboardServiceListAuditEventsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		streamAuditEvents: connect.NewClient[v1.StreamAuditEventsRequest, v1.AuditEvent](
			httpClient,
			baseURL+DashboardServiceStreamAuditEventsProcedure,
			connect.WithSchema(dashboardServiceStreamAuditEventsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getEarningsSummary: connect.NewClient[v1.GetEarningsSummaryRequest, v1.GetEarningsSummaryResponse](
			httpClient,
			baseURL+DashboardServiceGetEarningsSummaryProcedure,
			connect.WithSchema(dashboardServiceGetEarningsSummaryMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// dashboardServiceClient implements DashboardServiceClient.
type dashboardServiceClient struct {
	listAuditEvents    *connect.Client[v1.ListAuditEventsRequest, v1.ListAuditEventsResponse]
	streamAuditEvents  *connect.Client[v1.StreamAuditEventsRequest, v1.AuditEvent]
	getEarningsSummary *connect.Client[v1.GetEarningsSummaryRequest, v1.GetEarningsSummaryResponse]
}

// ListAuditEvents calls iogrid.providers.v1.DashboardService.ListAuditEvents.
func (c *dashboardServiceClient) ListAuditEvents(ctx context.Context, req *connect.Request[v1.ListAuditEventsRequest]) (*connect.Response[v1.ListAuditEventsResponse], error) {
	return c.listAuditEvents.CallUnary(ctx, req)
}

// StreamAuditEvents calls iogrid.providers.v1.DashboardService.StreamAuditEvents.
func (c *dashboardServiceClient) StreamAuditEvents(ctx context.Context, req *connect.Request[v1.StreamAuditEventsRequest]) (*connect.ServerStreamForClient[v1.AuditEvent], error) {
	return c.streamAuditEvents.CallServerStream(ctx, req)
}

// GetEarningsSummary calls iogrid.providers.v1.DashboardService.GetEarningsSummary.
func (c *dashboardServiceClient) GetEarningsSummary(ctx context.Context, req *connect.Request[v1.GetEarningsSummaryRequest]) (*connect.Response[v1.GetEarningsSummaryResponse], error) {
	return c.getEarningsSummary.CallUnary(ctx, req)
}

// DashboardServiceHandler is an implementation of the iogrid.providers.v1.DashboardService service.
type DashboardServiceHandler interface {
	ListAuditEvents(context.Context, *connect.Request[v1.ListAuditEventsRequest]) (*connect.Response[v1.ListAuditEventsResponse], error)
	StreamAuditEvents(context.Context, *connect.Request[v1.StreamAuditEventsRequest], *connect.ServerStream[v1.AuditEvent]) error
	GetEarningsSummary(context.Context, *connect.Request[v1.GetEarningsSummaryRequest]) (*connect.Response[v1.GetEarningsSummaryResponse], error)
}

// NewDashboardServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDashboardServiceHandler(svc DashboardServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	dashboardServiceListAuditEventsHandler := connect.NewUnaryHandler(
		DashboardServiceListAuditEventsProcedure,
		svc.ListAuditEvents,
		connect.WithSchema(dashboardServiceListAuditEventsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	dashboardServiceStreamAuditEventsHandler := connect.NewServerStreamHandler(
		DashboardServiceStreamAuditEventsProcedure,
		svc.StreamAuditEvents,
		connect.WithSchema(dashboardServiceStreamAuditEventsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	dashboardServiceGetEarningsSummaryHandler := connect.NewUnaryHandler(
		DashboardServiceGetEarningsSummaryProcedure,
		svc.GetEarningsSummary,
		connect.WithSchema(dashboardServiceGetEarningsSummaryMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/iogrid.providers.v1.DashboardService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DashboardServiceListAuditEventsProcedure:
			dashboardServiceListAuditEventsHandler.ServeHTTP(w, r)
		case DashboardServiceStreamAuditEventsProcedure:
			dashboardServiceStreamAuditEventsHandler.ServeHTTP(w, r)
		case DashboardServiceGetEarningsSummaryProcedure:
			dashboardServiceGetEarningsSummaryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDashboardServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDashboardServiceHandler struct{}

func (UnimplementedDashboardServiceHandler) ListAuditEvents(context.Context, *connect.Request[v1.ListAuditEventsRequest]) (*connect.Response[v1.ListAuditEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.providers.v1.DashboardService.ListAuditEvents is not implemented"))
}

func (UnimplementedDashboardServiceHandler) StreamAuditEvents(context.Context, *connect.Request[v1.StreamAuditEventsRequest], *connect.ServerStream[v1.AuditEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.providers.v1.DashboardService.StreamAuditEvents is not implemented"))
}

func (UnimplementedDashboardServiceHandler) GetEarningsSummary(context.Context, *connect.Request[v1.GetEarningsSummaryRequest]) (*connect.Response[v1.GetEarningsSummaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.providers.v1.DashboardService.GetEarningsSummary is not implemented"))
}
