// Provider registration and capability inventory. Called by the Rust
// daemon during first-run pairing and on every reconnect to refresh its
// advertised capabilities.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: iogrid/providers/v1/registration.proto

package providersv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/iogrid/iogrid/coordinator/internal/pb/iogrid/providers/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProviderRegistrationServiceName is the fully-qualified name of the ProviderRegistrationService
	// service.
	ProviderRegistrationServiceName = "iogrid.providers.v1.ProviderRegistrationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProviderRegistrationServiceIssuePairingTokenProcedure is the fully-qualified name of the
	// ProviderRegistrationService's IssuePairingToken RPC.
	ProviderRegistrationServiceIssuePairingTokenProcedure = "/iogrid.providers.v1.ProviderRegistrationService/IssuePairingToken"
	// ProviderRegistrationServicePairDaemonProcedure is the fully-qualified name of the
	// ProviderRegistrationService's PairDaemon RPC.
	ProviderRegistrationServicePairDaemonProcedure = "/iogrid.providers.v1.ProviderRegistrationService/PairDaemon"
	// ProviderRegistrationServiceUpdateHostInfoProcedure is the fully-qualified name of the
	// ProviderRegistrationService's UpdateHostInfo RPC.
	ProviderRegistrationServiceUpdateHostInfoProcedure = "/iogrid.providers.v1.ProviderRegistrationService/UpdateHostInfo"
	// ProviderRegistrationServiceUpdateCapabilityInventoryProcedure is the fully-qualified name of the
	// ProviderRegistrationService's UpdateCapabilityInventory RPC.
	ProviderRegistrationServiceUpdateCapabilityInventoryProcedure = "/iogrid.providers.v1.ProviderRegistrationService/UpdateCapabilityInventory"
	// ProviderRegistrationServiceGetProviderProcedure is the fully-qualified name of the
	// ProviderRegistrationService's GetProvider RPC.
	ProviderRegistrationServiceGetProviderProcedure = "/iogrid.providers.v1.ProviderRegistrationService/GetProvider"
	// ProviderRegistrationServiceListProvidersProcedure is the fully-qualified name of the
	// ProviderRegistrationService's ListProviders RPC.
	ProviderRegistrationServiceListProvidersProcedure = "/iogrid.providers.v1.ProviderRegistrationService/ListProviders"
	// ProviderRegistrationServiceDeactivateProviderProcedure is the fully-qualified name of the
	// ProviderRegistrationService's DeactivateProvider RPC.
	ProviderRegistrationServiceDeactivateProviderProcedure = "/iogrid.providers.v1.ProviderRegistrationService/DeactivateProvider"
	// ProviderRegistrationServiceSetPrimaryProviderProcedure is the fully-qualified name of the
	// ProviderRegistrationService's SetPrimaryProvider RPC.
	ProviderRegistrationServiceSetPrimaryProviderProcedure = "/iogrid.providers.v1.ProviderRegistrationService/SetPrimaryProvider"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	providerRegistrationServiceServiceDescriptor                         = v1.File_iogrid_providers_v1_registration_proto.Services().ByName("ProviderRegistrationService")
	providerRegistrationServiceIssuePairingTokenMethodDescriptor         = providerRegistrationServiceServiceDescriptor.Methods().ByName("IssuePairingToken")
	providerRegistrationServicePairDaemonMethodDescriptor                = providerRegistrationServiceServiceDescriptor.Methods().ByName("PairDaemon")
	providerRegistrationServiceUpdateHostInfoMethodDescriptor            = providerRegistrationServiceServiceDescriptor.Methods().ByName("UpdateHostInfo")
	providerRegistrationServiceUpdateCapabilityInventoryMethodDescriptor = providerRegistrationServiceServiceDescriptor.Methods().ByName("UpdateCapabilityInventory")
	providerRegistrationServiceGetProviderMethodDescriptor               = providerRegistrationServiceServiceDescriptor.Methods().ByName("GetProvider")
	providerRegistrationServiceListProvidersMethodDescriptor             = providerRegistrationServiceServiceDescriptor.Methods().ByName("ListProviders")
	providerRegistrationServiceDeactivateProviderMethodDescriptor        = providerRegistrationServiceServiceDescriptor.Methods().ByName("DeactivateProvider")
	providerRegistrationServiceSetPrimaryProviderMethodDescriptor        = providerRegistrationServiceServiceDescriptor.Methods().ByName("SetPrimaryProvider")
)

// ProviderRegistrationServiceClient is a client for the
// iogrid.providers.v1.ProviderRegistrationService service.
type ProviderRegistrationServiceClient interface {
	IssuePairingToken(context.Context, *connect.Request[v1.IssuePairingTokenRequest]) (*connect.Response[v1.IssuePairingTokenResponse], error)
	PairDaemon(context.Context, *connect.Request[v1.PairDaemonRequest]) (*connect.Response[v1.PairDaemonResponse], error)
	UpdateHostInfo(context.Context, *connect.Request[v1.UpdateHostInfoRequest]) (*connect.Response[v1.UpdateHostInfoResponse], error)
	UpdateCapabilityInventory(context.Context, *connect.Request[v1.UpdateCapabilityInventoryRequest]) (*connect.Response[v1.UpdateCapabilityInventoryResponse], error)
	GetProvider(context.Context, *connect.Request[v1.GetProviderRequest]) (*connect.Response[v1.GetProviderResponse], error)
	ListProviders(context.Context, *connect.Request[v1.ListProvidersRequest]) (*connect.Response[v1.ListProvidersResponse], error)
	DeactivateProvider(context.Context, *connect.Request[v1.DeactivateProviderRequest]) (*connect.Response[v1.DeactivateProviderResponse], error)
	// SetPrimaryProvider promotes one owned provider to the per-owner
	// primary slot. Atomic swap. Issue #325.
	SetPrimaryProvider(context.Context, *connect.Request[v1.SetPrimaryProviderRequest]) (*connect.Response[v1.SetPrimaryProviderResponse], error)
}

// NewProviderRegistrationServiceClient constructs a client for the
// iogrid.providers.v1.ProviderRegistrationService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProviderRegistrationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProviderRegistrationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &providerRegistrationServiceClient{
		issuePairingToken: connect.NewClient[v1.IssuePairingTokenRequest, v1.IssuePairingTokenResponse](
			httpClient,
			baseURL+ProviderRegistrationServiceIssuePairingTokenProcedure,
			connect.WithSchema(providerRegistrationServiceIssuePairingTokenMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		pairDaemon: connect.NewClient[v1.PairDaemonRequest, v1.PairDaemonResponse](
			httpClient,
			baseURL+ProviderRegistrationServicePairDaemonProcedure,
			connect.WithSchema(providerRegistrationServicePairDaemonMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateHostInfo: connect.NewClient[v1.UpdateHostInfoRequest, v1.UpdateHostInfoResponse](
			httpClient,
			baseURL+ProviderRegistrationServiceUpdateHostInfoProcedure,
			connect.WithSchema(providerRegistrationServiceUpdateHostInfoMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateCapabilityInventory: connect.NewClient[v1.UpdateCapabilityInventoryRequest, v1.UpdateCapabilityInventoryResponse](
			httpClient,
			baseURL+ProviderRegistrationServiceUpdateCapabilityInventoryProcedure,
			connect.WithSchema(providerRegistrationServiceUpdateCapabilityInventoryMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getProvider: connect.NewClient[v1.GetProviderRequest, v1.GetProviderResponse](
			httpClient,
			baseURL+ProviderRegistrationServiceGetProviderProcedure,
			connect.WithSchema(providerRegistrationServiceGetProviderMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listProviders: connect.NewClient[v1.ListProvidersRequest, v1.ListProvidersResponse](
			httpClient,
			baseURL+ProviderRegistrationServiceListProvidersProcedure,
			connect.WithSchema(providerRegistrationServiceListProvidersMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deactivateProvider: connect.NewClient[v1.DeactivateProviderRequest, v1.DeactivateProviderResponse](
			httpClient,
			baseURL+ProviderRegistrationServiceDeactivateProviderProcedure,
			connect.WithSchema(providerRegistrationServiceDeactivateProviderMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		setPrimaryProvider: connect.NewClient[v1.SetPrimaryProviderRequest, v1.SetPrimaryProviderResponse](
			httpClient,
			baseURL+ProviderRegistrationServiceSetPrimaryProviderProcedure,
			connect.WithSchema(providerRegistrationServiceSetPrimaryProviderMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// providerRegistrationServiceClient implements ProviderRegistrationServiceClient.
type providerRegistrationServiceClient struct {
	issuePairingToken         *connect.Client[v1.IssuePairingTokenRequest, v1.IssuePairingTokenResponse]
	pairDaemon                *connect.Client[v1.PairDaemonRequest, v1.PairDaemonResponse]
	updateHostInfo            *connect.Client[v1.UpdateHostInfoRequest, v1.UpdateHostInfoResponse]
	updateCapabilityInventory *connect.Client[v1.UpdateCapabilityInventoryRequest, v1.UpdateCapabilityInventoryResponse]
	getProvider               *connect.Client[v1.GetProviderRequest, v1.GetProviderResponse]
	listProviders             *connect.Client[v1.ListProvidersRequest, v1.ListProvidersResponse]
	deactivateProvider        *connect.Client[v1.DeactivateProviderRequest, v1.DeactivateProviderResponse]
	setPrimaryProvider        *connect.Client[v1.SetPrimaryProviderRequest, v1.SetPrimaryProviderResponse]
}

// IssuePairingToken calls iogrid.providers.v1.ProviderRegistrationService.IssuePairingToken.
func (c *providerRegistrationServiceClient) IssuePairingToken(ctx context.Context, req *connect.Request[v1.IssuePairingTokenRequest]) (*connect.Response[v1.IssuePairingTokenResponse], error) {
	return c.issuePairingToken.CallUnary(ctx, req)
}

// PairDaemon calls iogrid.providers.v1.ProviderRegistrationService.PairDaemon.
func (c *providerRegistrationServiceClient) PairDaemon(ctx context.Context, req *connect.Request[v1.PairDaemonRequest]) (*connect.Response[v1.PairDaemonResponse], error) {
	return c.pairDaemon.CallUnary(ctx, req)
}

// UpdateHostInfo calls iogrid.providers.v1.ProviderRegistrationService.UpdateHostInfo.
func (c *providerRegistrationServiceClient) UpdateHostInfo(ctx context.Context, req *connect.Request[v1.UpdateHostInfoRequest]) (*connect.Response[v1.UpdateHostInfoResponse], error) {
	return c.updateHostInfo.CallUnary(ctx, req)
}

// UpdateCapabilityInventory calls
// iogrid.providers.v1.ProviderRegistrationService.UpdateCapabilityInventory.
func (c *providerRegistrationServiceClient) UpdateCapabilityInventory(ctx context.Context, req *connect.Request[v1.UpdateCapabilityInventoryRequest]) (*connect.Response[v1.UpdateCapabilityInventoryResponse], error) {
	return c.updateCapabilityInventory.CallUnary(ctx, req)
}

// GetProvider calls iogrid.providers.v1.ProviderRegistrationService.GetProvider.
func (c *providerRegistrationServiceClient) GetProvider(ctx context.Context, req *connect.Request[v1.GetProviderRequest]) (*connect.Response[v1.GetProviderResponse], error) {
	return c.getProvider.CallUnary(ctx, req)
}

// ListProviders calls iogrid.providers.v1.ProviderRegistrationService.ListProviders.
func (c *providerRegistrationServiceClient) ListProviders(ctx context.Context, req *connect.Request[v1.ListProvidersRequest]) (*connect.Response[v1.ListProvidersResponse], error) {
	return c.listProviders.CallUnary(ctx, req)
}

// DeactivateProvider calls iogrid.providers.v1.ProviderRegistrationService.DeactivateProvider.
func (c *providerRegistrationServiceClient) DeactivateProvider(ctx context.Context, req *connect.Request[v1.DeactivateProviderRequest]) (*connect.Response[v1.DeactivateProviderResponse], error) {
	return c.deactivateProvider.CallUnary(ctx, req)
}

// SetPrimaryProvider calls iogrid.providers.v1.ProviderRegistrationService.SetPrimaryProvider.
func (c *providerRegistrationServiceClient) SetPrimaryProvider(ctx context.Context, req *connect.Request[v1.SetPrimaryProviderRequest]) (*connect.Response[v1.SetPrimaryProviderResponse], error) {
	return c.setPrimaryProvider.CallUnary(ctx, req)
}

// ProviderRegistrationServiceHandler is an implementation of the
// iogrid.providers.v1.ProviderRegistrationService service.
type ProviderRegistrationServiceHandler interface {
	IssuePairingToken(context.Context, *connect.Request[v1.IssuePairingTokenRequest]) (*connect.Response[v1.IssuePairingTokenResponse], error)
	PairDaemon(context.Context, *connect.Request[v1.PairDaemonRequest]) (*connect.Response[v1.PairDaemonResponse], error)
	UpdateHostInfo(context.Context, *connect.Request[v1.UpdateHostInfoRequest]) (*connect.Response[v1.UpdateHostInfoResponse], error)
	UpdateCapabilityInventory(context.Context, *connect.Request[v1.UpdateCapabilityInventoryRequest]) (*connect.Response[v1.UpdateCapabilityInventoryResponse], error)
	GetProvider(context.Context, *connect.Request[v1.GetProviderRequest]) (*connect.Response[v1.GetProviderResponse], error)
	ListProviders(context.Context, *connect.Request[v1.ListProvidersRequest]) (*connect.Response[v1.ListProvidersResponse], error)
	DeactivateProvider(context.Context, *connect.Request[v1.DeactivateProviderRequest]) (*connect.Response[v1.DeactivateProviderResponse], error)
	// SetPrimaryProvider promotes one owned provider to the per-owner
	// primary slot. Atomic swap. Issue #325.
	SetPrimaryProvider(context.Context, *connect.Request[v1.SetPrimaryProviderRequest]) (*connect.Response[v1.SetPrimaryProviderResponse], error)
}

// NewProviderRegistrationServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProviderRegistrationServiceHandler(svc ProviderRegistrationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	providerRegistrationServiceIssuePairingTokenHandler := connect.NewUnaryHandler(
		ProviderRegistrationServiceIssuePairingTokenProcedure,
		svc.IssuePairingToken,
		connect.WithSchema(providerRegistrationServiceIssuePairingTokenMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	providerRegistrationServicePairDaemonHandler := connect.NewUnaryHandler(
		ProviderRegistrationServicePairDaemonProcedure,
		svc.PairDaemon,
		connect.WithSchema(providerRegistrationServicePairDaemonMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	providerRegistrationServiceUpdateHostInfoHandler := connect.NewUnaryHandler(
		ProviderRegistrationServiceUpdateHostInfoProcedure,
		svc.UpdateHostInfo,
		connect.WithSchema(providerRegistrationServiceUpdateHostInfoMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	providerRegistrationServiceUpdateCapabilityInventoryHandler := connect.NewUnaryHandler(
		ProviderRegistrationServiceUpdateCapabilityInventoryProcedure,
		svc.UpdateCapabilityInventory,
		connect.WithSchema(providerRegistrationServiceUpdateCapabilityInventoryMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	providerRegistrationServiceGetProviderHandler := connect.NewUnaryHandler(
		ProviderRegistrationServiceGetProviderProcedure,
		svc.GetProvider,
		connect.WithSchema(providerRegistrationServiceGetProviderMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	providerRegistrationServiceListProvidersHandler := connect.NewUnaryHandler(
		ProviderRegistrationServiceListProvidersProcedure,
		svc.ListProviders,
		connect.WithSchema(providerRegistrationServiceListProvidersMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	providerRegistrationServiceDeactivateProviderHandler := connect.NewUnaryHandler(
		ProviderRegistrationServiceDeactivateProviderProcedure,
		svc.DeactivateProvider,
		connect.WithSchema(providerRegistrationServiceDeactivateProviderMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	providerRegistrationServiceSetPrimaryProviderHandler := connect.NewUnaryHandler(
		ProviderRegistrationServiceSetPrimaryProviderProcedure,
		svc.SetPrimaryProvider,
		connect.WithSchema(providerRegistrationServiceSetPrimaryProviderMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/iogrid.providers.v1.ProviderRegistrationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProviderRegistrationServiceIssuePairingTokenProcedure:
			providerRegistrationServiceIssuePairingTokenHandler.ServeHTTP(w, r)
		case ProviderRegistrationServicePairDaemonProcedure:
			providerRegistrationServicePairDaemonHandler.ServeHTTP(w, r)
		case ProviderRegistrationServiceUpdateHostInfoProcedure:
			providerRegistrationServiceUpdateHostInfoHandler.ServeHTTP(w, r)
		case ProviderRegistrationServiceUpdateCapabilityInventoryProcedure:
			providerRegistrationServiceUpdateCapabilityInventoryHandler.ServeHTTP(w, r)
		case ProviderRegistrationServiceGetProviderProcedure:
			providerRegistrationServiceGetProviderHandler.ServeHTTP(w, r)
		case ProviderRegistrationServiceListProvidersProcedure:
			providerRegistrationServiceListProvidersHandler.ServeHTTP(w, r)
		case ProviderRegistrationServiceDeactivateProviderProcedure:
			providerRegistrationServiceDeactivateProviderHandler.ServeHTTP(w, r)
		case ProviderRegistrationServiceSetPrimaryProviderProcedure:
			providerRegistrationServiceSetPrimaryProviderHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProviderRegistrationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProviderRegistrationServiceHandler struct{}

func (UnimplementedProviderRegistrationServiceHandler) IssuePairingToken(context.Context, *connect.Request[v1.IssuePairingTokenRequest]) (*connect.Response[v1.IssuePairingTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.providers.v1.ProviderRegistrationService.IssuePairingToken is not implemented"))
}

func (UnimplementedProviderRegistrationServiceHandler) PairDaemon(context.Context, *connect.Request[v1.PairDaemonRequest]) (*connect.Response[v1.PairDaemonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.providers.v1.ProviderRegistrationService.PairDaemon is not implemented"))
}

func (UnimplementedProviderRegistrationServiceHandler) UpdateHostInfo(context.Context, *connect.Request[v1.UpdateHostInfoRequest]) (*connect.Response[v1.UpdateHostInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.providers.v1.ProviderRegistrationService.UpdateHostInfo is not implemented"))
}

func (UnimplementedProviderRegistrationServiceHandler) UpdateCapabilityInventory(context.Context, *connect.Request[v1.UpdateCapabilityInventoryRequest]) (*connect.Response[v1.UpdateCapabilityInventoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.providers.v1.ProviderRegistrationService.UpdateCapabilityInventory is not implemented"))
}

func (UnimplementedProviderRegistrationServiceHandler) GetProvider(context.Context, *connect.Request[v1.GetProviderRequest]) (*connect.Response[v1.GetProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.providers.v1.ProviderRegistrationService.GetProvider is not implemented"))
}

func (UnimplementedProviderRegistrationServiceHandler) ListProviders(context.Context, *connect.Request[v1.ListProvidersRequest]) (*connect.Response[v1.ListProvidersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.providers.v1.ProviderRegistrationService.ListProviders is not implemented"))
}

func (UnimplementedProviderRegistrationServiceHandler) DeactivateProvider(context.Context, *connect.Request[v1.DeactivateProviderRequest]) (*connect.Response[v1.DeactivateProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.providers.v1.ProviderRegistrationService.DeactivateProvider is not implemented"))
}

func (UnimplementedProviderRegistrationServiceHandler) SetPrimaryProvider(context.Context, *connect.Request[v1.SetPrimaryProviderRequest]) (*connect.Response[v1.SetPrimaryProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.providers.v1.ProviderRegistrationService.SetPrimaryProvider is not implemented"))
}
