apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-svc
  namespace: iogrid
  labels:
    app.kubernetes.io/name: identity-svc
    app.kubernetes.io/part-of: iogrid
    app.kubernetes.io/component: backend
automountServiceAccountToken: true
