// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=js"
// @generated from file iogrid/vpn/v1/wireguard.proto (package iogrid.vpn.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * WireGuard peer configuration
 *
 * @generated from message iogrid.vpn.v1.WireGuardPeer
 */
export class WireGuardPeer extends Message<WireGuardPeer> {
  /**
   * Base64-encoded WireGuard public key (33 bytes)
   *
   * @generated from field: string public_key = 1;
   */
  publicKey = "";

  /**
   * IP:port of the peer (from chosen ICE candidate)
   *
   * @generated from field: string endpoint = 2;
   */
  endpoint = "";

  /**
   * CIDR ranges for this peer (e.g., "10.64.0.1/32")
   *
   * @generated from field: string allowed_ips = 3;
   */
  allowedIps = "";

  /**
   * Seconds between keepalive packets (0 = disabled)
   *
   * @generated from field: int64 persistent_keepalive = 4;
   */
  persistentKeepalive = protoInt64.zero;

  /**
   * Last successful handshake timestamp
   *
   * @generated from field: int64 last_handshake_unix_ms = 5;
   */
  lastHandshakeUnixMs = protoInt64.zero;

  /**
   * Data bytes received from peer
   *
   * @generated from field: uint64 bytes_received = 6;
   */
  bytesReceived = protoInt64.zero;

  /**
   * Data bytes sent to peer
   *
   * @generated from field: uint64 bytes_sent = 7;
   */
  bytesSent = protoInt64.zero;

  constructor(data?: PartialMessage<WireGuardPeer>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.vpn.v1.WireGuardPeer";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "public_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "endpoint", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "allowed_ips", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "persistent_keepalive", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "last_handshake_unix_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "bytes_received", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 7, name: "bytes_sent", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WireGuardPeer {
    return new WireGuardPeer().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WireGuardPeer {
    return new WireGuardPeer().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WireGuardPeer {
    return new WireGuardPeer().fromJsonString(jsonString, options);
  }

  static equals(a: WireGuardPeer | PlainMessage<WireGuardPeer> | undefined, b: WireGuardPeer | PlainMessage<WireGuardPeer> | undefined): boolean {
    return proto3.util.equals(WireGuardPeer, a, b);
  }
}

/**
 * Tunnel establishment request (customer → coordinator, after ICE done)
 *
 * @generated from message iogrid.vpn.v1.EstablishWireGuardTunnel
 */
export class EstablishWireGuardTunnel extends Message<EstablishWireGuardTunnel> {
  /**
   * Which session
   *
   * @generated from field: string session_id = 1;
   */
  sessionId = "";

  /**
   * Customer UUID
   *
   * @generated from field: string customer_id = 2;
   */
  customerId = "";

  /**
   * Provider UUID
   *
   * @generated from field: string provider_id = 3;
   */
  providerId = "";

  /**
   * Customer's WireGuard public key (base64)
   *
   * @generated from field: string customer_wg_public_key = 4;
   */
  customerWgPublicKey = "";

  /**
   * Customer's chosen endpoint (from ICE candidate)
   *
   * @generated from field: string endpoint = 5;
   */
  endpoint = "";

  /**
   * Request timestamp
   *
   * @generated from field: int64 requested_at_unix_ms = 6;
   */
  requestedAtUnixMs = protoInt64.zero;

  constructor(data?: PartialMessage<EstablishWireGuardTunnel>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.vpn.v1.EstablishWireGuardTunnel";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "customer_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "provider_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "customer_wg_public_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "endpoint", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "requested_at_unix_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EstablishWireGuardTunnel {
    return new EstablishWireGuardTunnel().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EstablishWireGuardTunnel {
    return new EstablishWireGuardTunnel().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EstablishWireGuardTunnel {
    return new EstablishWireGuardTunnel().fromJsonString(jsonString, options);
  }

  static equals(a: EstablishWireGuardTunnel | PlainMessage<EstablishWireGuardTunnel> | undefined, b: EstablishWireGuardTunnel | PlainMessage<EstablishWireGuardTunnel> | undefined): boolean {
    return proto3.util.equals(EstablishWireGuardTunnel, a, b);
  }
}

/**
 * Tunnel established acknowledgement (provider → coordinator → customer)
 *
 * @generated from message iogrid.vpn.v1.WireGuardTunnelEstablished
 */
export class WireGuardTunnelEstablished extends Message<WireGuardTunnelEstablished> {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId = "";

  /**
   * @generated from field: string provider_id = 2;
   */
  providerId = "";

  /**
   * Provider's WireGuard public key (echoed)
   *
   * @generated from field: string provider_wg_public_key = 3;
   */
  providerWgPublicKey = "";

  /**
   * Provider's tunnel IP (e.g., "10.64.0.1/32")
   *
   * @generated from field: string tunnel_ipv4 = 4;
   */
  tunnelIpv4 = "";

  /**
   * Customer's tunnel IP (e.g., "10.64.0.2/32")
   *
   * @generated from field: string customer_tunnel_ipv4 = 5;
   */
  customerTunnelIpv4 = "";

  /**
   * Provider's tunnel IPv6 (if available)
   *
   * @generated from field: string tunnel_ipv6 = 6;
   */
  tunnelIpv6 = "";

  /**
   * Customer's tunnel IPv6 (if available)
   *
   * @generated from field: string customer_tunnel_ipv6 = 7;
   */
  customerTunnelIpv6 = "";

  /**
   * Handshake completion timestamp
   *
   * @generated from field: int64 established_at_unix_ms = 8;
   */
  establishedAtUnixMs = protoInt64.zero;

  /**
   * MTU for this tunnel (typically 1420)
   *
   * @generated from field: int32 mtu = 9;
   */
  mtu = 0;

  constructor(data?: PartialMessage<WireGuardTunnelEstablished>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.vpn.v1.WireGuardTunnelEstablished";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "provider_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "provider_wg_public_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "tunnel_ipv4", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "customer_tunnel_ipv4", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "tunnel_ipv6", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "customer_tunnel_ipv6", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "established_at_unix_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "mtu", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WireGuardTunnelEstablished {
    return new WireGuardTunnelEstablished().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WireGuardTunnelEstablished {
    return new WireGuardTunnelEstablished().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WireGuardTunnelEstablished {
    return new WireGuardTunnelEstablished().fromJsonString(jsonString, options);
  }

  static equals(a: WireGuardTunnelEstablished | PlainMessage<WireGuardTunnelEstablished> | undefined, b: WireGuardTunnelEstablished | PlainMessage<WireGuardTunnelEstablished> | undefined): boolean {
    return proto3.util.equals(WireGuardTunnelEstablished, a, b);
  }
}

/**
 * Tunnel down/error (either side → coordinator)
 *
 * @generated from message iogrid.vpn.v1.WireGuardTunnelDown
 */
export class WireGuardTunnelDown extends Message<WireGuardTunnelDown> {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId = "";

  /**
   * @generated from field: string provider_id = 2;
   */
  providerId = "";

  /**
   * "peer_unreachable", "handshake_failed", "user_initiated", etc.
   *
   * @generated from field: string reason = 3;
   */
  reason = "";

  /**
   * @generated from field: int64 down_at_unix_ms = 4;
   */
  downAtUnixMs = protoInt64.zero;

  /**
   * Total bytes that flowed through tunnel
   *
   * @generated from field: uint64 bytes_transferred = 5;
   */
  bytesTransferred = protoInt64.zero;

  constructor(data?: PartialMessage<WireGuardTunnelDown>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.vpn.v1.WireGuardTunnelDown";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "provider_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "down_at_unix_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "bytes_transferred", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WireGuardTunnelDown {
    return new WireGuardTunnelDown().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WireGuardTunnelDown {
    return new WireGuardTunnelDown().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WireGuardTunnelDown {
    return new WireGuardTunnelDown().fromJsonString(jsonString, options);
  }

  static equals(a: WireGuardTunnelDown | PlainMessage<WireGuardTunnelDown> | undefined, b: WireGuardTunnelDown | PlainMessage<WireGuardTunnelDown> | undefined): boolean {
    return proto3.util.equals(WireGuardTunnelDown, a, b);
  }
}

/**
 * Health check: provider probes customer for keepalive
 *
 * @generated from message iogrid.vpn.v1.KeepAliveProbe
 */
export class KeepAliveProbe extends Message<KeepAliveProbe> {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId = "";

  /**
   * @generated from field: string provider_id = 2;
   */
  providerId = "";

  /**
   * Timestamp when probe sent
   *
   * @generated from field: int64 sent_at_unix_ms = 3;
   */
  sentAtUnixMs = protoInt64.zero;

  /**
   * Probe sequence number
   *
   * @generated from field: uint32 sequence = 4;
   */
  sequence = 0;

  constructor(data?: PartialMessage<KeepAliveProbe>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.vpn.v1.KeepAliveProbe";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "provider_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "sent_at_unix_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "sequence", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): KeepAliveProbe {
    return new KeepAliveProbe().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): KeepAliveProbe {
    return new KeepAliveProbe().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): KeepAliveProbe {
    return new KeepAliveProbe().fromJsonString(jsonString, options);
  }

  static equals(a: KeepAliveProbe | PlainMessage<KeepAliveProbe> | undefined, b: KeepAliveProbe | PlainMessage<KeepAliveProbe> | undefined): boolean {
    return proto3.util.equals(KeepAliveProbe, a, b);
  }
}

/**
 * Health check: customer acknowledges probe
 *
 * @generated from message iogrid.vpn.v1.KeepAliveAck
 */
export class KeepAliveAck extends Message<KeepAliveAck> {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId = "";

  /**
   * @generated from field: string provider_id = 2;
   */
  providerId = "";

  /**
   * Which probe this acks
   *
   * @generated from field: uint32 sequence = 3;
   */
  sequence = 0;

  /**
   * Customer's ack timestamp
   *
   * @generated from field: int64 acked_at_unix_ms = 4;
   */
  ackedAtUnixMs = protoInt64.zero;

  constructor(data?: PartialMessage<KeepAliveAck>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.vpn.v1.KeepAliveAck";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "provider_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "sequence", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "acked_at_unix_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): KeepAliveAck {
    return new KeepAliveAck().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): KeepAliveAck {
    return new KeepAliveAck().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): KeepAliveAck {
    return new KeepAliveAck().fromJsonString(jsonString, options);
  }

  static equals(a: KeepAliveAck | PlainMessage<KeepAliveAck> | undefined, b: KeepAliveAck | PlainMessage<KeepAliveAck> | undefined): boolean {
    return proto3.util.equals(KeepAliveAck, a, b);
  }
}

/**
 * Endpoint update during roaming (customer → coordinator)
 *
 * @generated from message iogrid.vpn.v1.UpdateWireGuardEndpoint
 */
export class UpdateWireGuardEndpoint extends Message<UpdateWireGuardEndpoint> {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId = "";

  /**
   * @generated from field: string provider_id = 2;
   */
  providerId = "";

  /**
   * New IP:port (from new ICE candidate)
   *
   * @generated from field: string new_endpoint = 3;
   */
  newEndpoint = "";

  /**
   * May have regenerated local WG key
   *
   * @generated from field: string new_customer_wg_public_key = 4;
   */
  newCustomerWgPublicKey = "";

  /**
   * @generated from field: int64 updated_at_unix_ms = 5;
   */
  updatedAtUnixMs = protoInt64.zero;

  constructor(data?: PartialMessage<UpdateWireGuardEndpoint>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.vpn.v1.UpdateWireGuardEndpoint";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "provider_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "new_endpoint", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "new_customer_wg_public_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "updated_at_unix_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateWireGuardEndpoint {
    return new UpdateWireGuardEndpoint().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateWireGuardEndpoint {
    return new UpdateWireGuardEndpoint().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateWireGuardEndpoint {
    return new UpdateWireGuardEndpoint().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateWireGuardEndpoint | PlainMessage<UpdateWireGuardEndpoint> | undefined, b: UpdateWireGuardEndpoint | PlainMessage<UpdateWireGuardEndpoint> | undefined): boolean {
    return proto3.util.equals(UpdateWireGuardEndpoint, a, b);
  }
}

/**
 * Tunnel metrics snapshot (for monitoring)
 *
 * @generated from message iogrid.vpn.v1.TunnelMetrics
 */
export class TunnelMetrics extends Message<TunnelMetrics> {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId = "";

  /**
   * @generated from field: string provider_id = 2;
   */
  providerId = "";

  /**
   * @generated from field: uint64 bytes_in = 3;
   */
  bytesIn = protoInt64.zero;

  /**
   * @generated from field: uint64 bytes_out = 4;
   */
  bytesOut = protoInt64.zero;

  /**
   * Estimated packet loss %
   *
   * @generated from field: uint32 packet_loss_percent = 5;
   */
  packetLossPercent = 0;

  /**
   * Median latency
   *
   * @generated from field: uint32 latency_p50_ms = 6;
   */
  latencyP50Ms = 0;

  /**
   * P99 latency
   *
   * @generated from field: uint32 latency_p99_ms = 7;
   */
  latencyP99Ms = 0;

  /**
   * @generated from field: int64 measured_at_unix_ms = 8;
   */
  measuredAtUnixMs = protoInt64.zero;

  constructor(data?: PartialMessage<TunnelMetrics>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.vpn.v1.TunnelMetrics";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "provider_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "bytes_in", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "bytes_out", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "packet_loss_percent", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 6, name: "latency_p50_ms", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 7, name: "latency_p99_ms", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 8, name: "measured_at_unix_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TunnelMetrics {
    return new TunnelMetrics().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TunnelMetrics {
    return new TunnelMetrics().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TunnelMetrics {
    return new TunnelMetrics().fromJsonString(jsonString, options);
  }

  static equals(a: TunnelMetrics | PlainMessage<TunnelMetrics> | undefined, b: TunnelMetrics | PlainMessage<TunnelMetrics> | undefined): boolean {
    return proto3.util.equals(TunnelMetrics, a, b);
  }
}

