package collector

// collectorTemplate is the OpenTelemetry Collector gateway configuration.
//
// Layout:
//
//	receivers: OTLP (gRPC + HTTP), prometheus (auto-discover via k8s)
//	processors:
//	  memory_limiter — first, refuses load when heap above limit (drops
//	                   incoming, never OOM-kills the collector)
//	  attributes     — stamp cluster_id + region on every record
//	  filter         — drop the noisiest spans (health checks, /metrics)
//	  tail_sampling  — 1% baseline, 100% on errors, 100% on slow
//	  batch          — last, micro-batches before exporters
//	exporters: otlp/tempo, prometheusremotewrite/mimir, loki
//	service.pipelines: traces / metrics / logs — only include an exporter
//	                   when the corresponding *Enabled flag is true.
//
// The template uses Go text/template's `{{- ... -}}` whitespace trimming
// to keep the rendered YAML compact and diffable. Indentation is
// significant in YAML; do NOT reformat without re-validating the result
// with `otelcol-contrib validate --config=<path>`.
const collectorTemplate = `# Generated by telemetry-svc. DO NOT EDIT MANUALLY.
# Regenerate via the telemetry-svc /admin/reload endpoint or restart the
# telemetry-svc Pod. The collector container watches this file for
# changes and hot-reloads its pipelines.
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: {{ .GRPCEndpoint }}
        max_recv_msg_size_mib: 16
      http:
        endpoint: {{ .HTTPEndpoint }}
        cors:
          allowed_origins:
            - https://*.iogrid.org
            - https://iogrid.org
  prometheus:
    config:
      scrape_configs:
        - job_name: iogrid-services
          scrape_interval: 30s
          kubernetes_sd_configs:
{{- range .ScrapeNamespaces }}
            - role: pod
              namespaces:
                names: [{{ . }}]
{{- end }}
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: "true"
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
              action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $$1:$$2
              target_label: __address__
            - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
              action: replace
              target_label: service
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: namespace

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: {{ .MemoryLimitMiB }}
    spike_limit_mib: 100
  attributes/iogrid_tags:
    actions:
      - key: cluster_id
        value: {{ .ClusterID }}
        action: upsert
      - key: region
        value: {{ .Region }}
        action: upsert
      - key: telemetry.gateway
        value: iogrid-otelcol
        action: upsert
  filter/drop_noisy:
    error_mode: ignore
    traces:
      span:
        - attributes["http.target"] == "/healthz"
        - attributes["http.target"] == "/readyz"
        - attributes["http.target"] == "/metrics"
        - attributes["url.path"] == "/healthz"
        - attributes["url.path"] == "/readyz"
        - attributes["url.path"] == "/metrics"
  tail_sampling:
    decision_wait: 10s
    num_traces: 50000
    expected_new_traces_per_sec: 1000
    policies:
      - name: errors-always
        type: status_code
        status_code:
          status_codes: [ERROR]
      - name: slow-always
        type: latency
        latency:
          threshold_ms: {{ .SlowTraceThresholdMS }}
      - name: flagged-abuse-always
        type: string_attribute
        string_attribute:
          key: iogrid.flagged_abuse
          values: ["true"]
      - name: baseline-probabilistic
        type: probabilistic
        probabilistic:
          sampling_percentage: {{ .BaselineSamplingPercent }}
  batch:
    timeout: {{ .BatchTimeoutSeconds }}s
    send_batch_size: {{ .BatchMaxSize }}
    send_batch_max_size: {{ .BatchMaxSize }}

exporters:
  # debug is ALWAYS defined: each pipeline falls back to it when its real
  # backend is disabled. With no backend configured at all the previous
  # render produced an empty exporters block + empty pipeline exporter
  # lists, which otelcol rejects ("no exporter configuration specified")
  # — the sidecar crashlooped and the Pod never went Ready, taking
  # /status (and everything else on telemetry-svc) down with it (#682
  # fallout, found during the #674 live walk).
  debug:
    verbosity: basic
{{- if .TempoEnabled }}
  otlp/tempo:
    endpoint: {{ .TempoEndpoint }}
    {{- if .TempoInsecure }}
    tls:
      insecure: true
    {{- end }}
    {{- if .TempoHeaders }}
    headers:
      {{- range $k, $v := .TempoHeaders }}
      {{ $k }}: {{ $v | printf "%q" }}
      {{- end }}
    {{- end }}
    sending_queue:
      enabled: true
      num_consumers: 4
      queue_size: 1000
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
{{- end }}
{{- if .MimirEnabled }}
  prometheusremotewrite/mimir:
    endpoint: {{ .MimirURL }}
    {{- if .MimirHeaders }}
    headers:
      {{- range $k, $v := .MimirHeaders }}
      {{ $k }}: {{ $v | printf "%q" }}
      {{- end }}
    {{- end }}
    resource_to_telemetry_conversion:
      enabled: true
    remote_write_queue:
      enabled: true
      queue_size: 10000
      num_consumers: 5
{{- end }}
{{- if .LokiEnabled }}
  loki:
    endpoint: {{ .LokiURL }}
    {{- if .LokiHeaders }}
    headers:
      {{- range $k, $v := .LokiHeaders }}
      {{ $k }}: {{ $v | printf "%q" }}
      {{- end }}
    {{- end }}
    sending_queue:
      enabled: true
      queue_size: 1000
{{- end }}

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, attributes/iogrid_tags, filter/drop_noisy, tail_sampling, batch]
      exporters: [{{- if .TempoEnabled }}otlp/tempo{{- else }}debug{{- end }}]
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, attributes/iogrid_tags, batch]
      exporters: [{{- if .MimirEnabled }}prometheusremotewrite/mimir{{- else }}debug{{- end }}]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, attributes/iogrid_tags, batch]
      exporters: [{{- if .LokiEnabled }}loki{{- else }}debug{{- end }}]
  telemetry:
    metrics:
      address: 0.0.0.0:8888
    logs:
      level: info
      encoding: json
`
