apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpn-gateway
  namespace: iogrid
  labels:
    app.kubernetes.io/name: vpn-gateway
    app.kubernetes.io/part-of: iogrid
    app.kubernetes.io/component: vpn
automountServiceAccountToken: true
