// Internal coordinator → daemon dispatch protocol. The daemon holds a
// long-lived bidirectional stream open against the coordinator; the
// coordinator pushes WorkloadAssignments down the wire, the daemon pushes
// WorkloadStatusUpdates back.

// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=js"
// @generated from file iogrid/workloads/v1/dispatch.proto (package iogrid.workloads.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AckAssignmentRequest, AckAssignmentResponse, DispatchFrame, GetAssignmentRequest, GetAssignmentResponse } from "./dispatch_pbjs";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * WorkloadDispatchService is the internal RPC surface that workloads-svc
 * exposes to the daemon. Production traffic flows on the bidi stream.
 *
 * @generated from service iogrid.workloads.v1.WorkloadDispatchService
 */
export const WorkloadDispatchService = {
  typeName: "iogrid.workloads.v1.WorkloadDispatchService",
  methods: {
    /**
     * Long-lived bidi stream — the canonical path for production traffic.
     *
     * @generated from rpc iogrid.workloads.v1.WorkloadDispatchService.Dispatch
     */
    dispatch: {
      name: "Dispatch",
      I: DispatchFrame,
      O: DispatchFrame,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * Side-band acknowledgement used for replay/debug paths only.
     *
     * @generated from rpc iogrid.workloads.v1.WorkloadDispatchService.AckAssignment
     */
    ackAssignment: {
      name: "AckAssignment",
      I: AckAssignmentRequest,
      O: AckAssignmentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Inspect a single attempt — used by ops tooling.
     *
     * @generated from rpc iogrid.workloads.v1.WorkloadDispatchService.GetAssignment
     */
    getAssignment: {
      name: "GetAssignment",
      I: GetAssignmentRequest,
      O: GetAssignmentResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

