// Customer-facing workload submission. Customers POST workloads here
// (via gateway-bff); workloads-svc validates, queues, then hands off to
// the dispatcher (see dispatch.proto).

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=js"
// @generated from file iogrid/workloads/v1/submit.proto (package iogrid.workloads.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";
import { Money, PageRequest, PageResponse, Region, TimeWindow, UUID, WorkloadType } from "../../common/v1/types_pbjs";

/**
 * WorkloadPriority hints at scheduler urgency. Has no SLA force on its
 * own — used as a tie-breaker among queued jobs.
 *
 * @generated from enum iogrid.workloads.v1.WorkloadPriority
 */
export enum WorkloadPriority {
  /**
   * @generated from enum value: WORKLOAD_PRIORITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: WORKLOAD_PRIORITY_LOW = 1;
   */
  LOW = 1,

  /**
   * @generated from enum value: WORKLOAD_PRIORITY_NORMAL = 2;
   */
  NORMAL = 2,

  /**
   * @generated from enum value: WORKLOAD_PRIORITY_HIGH = 3;
   */
  HIGH = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(WorkloadPriority)
proto3.util.setEnumType(WorkloadPriority, "iogrid.workloads.v1.WorkloadPriority", [
  { no: 0, name: "WORKLOAD_PRIORITY_UNSPECIFIED" },
  { no: 1, name: "WORKLOAD_PRIORITY_LOW" },
  { no: 2, name: "WORKLOAD_PRIORITY_NORMAL" },
  { no: 3, name: "WORKLOAD_PRIORITY_HIGH" },
]);

/**
 * BandwidthRequest: HTTPS proxy / SOCKS5 relay job.
 *
 * @generated from message iogrid.workloads.v1.BandwidthRequest
 */
export class BandwidthRequest extends Message<BandwidthRequest> {
  /**
   * The URL the customer wants fetched / proxied (full request URL).
   *
   * @generated from field: string target_url = 1;
   */
  targetUrl = "";

  /**
   * Allowed HTTP method (GET, POST, ...). Empty == "any".
   *
   * @generated from field: string method = 2;
   */
  method = "";

  /**
   * Sticky-session id — if set, dispatcher tries to reuse the same
   * provider IP for subsequent requests with the same id.
   *
   * @generated from field: string session_id = 3;
   */
  sessionId = "";

  /**
   * Desired egress region (server matches best-effort).
   *
   * @generated from field: iogrid.common.v1.Region preferred_region = 4;
   */
  preferredRegion?: Region;

  /**
   * Desired category slug (e.g. "e_commerce").
   *
   * @generated from field: string category = 5;
   */
  category = "";

  /**
   * Per-request budget; dispatcher refuses if no eligible provider.
   *
   * @generated from field: iogrid.common.v1.Money max_spend = 6;
   */
  maxSpend?: Money;

  constructor(data?: PartialMessage<BandwidthRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.workloads.v1.BandwidthRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "target_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "method", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "preferred_region", kind: "message", T: Region },
    { no: 5, name: "category", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "max_spend", kind: "message", T: Money },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BandwidthRequest {
    return new BandwidthRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BandwidthRequest {
    return new BandwidthRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BandwidthRequest {
    return new BandwidthRequest().fromJsonString(jsonString, options);
  }

  static equals(a: BandwidthRequest | PlainMessage<BandwidthRequest> | undefined, b: BandwidthRequest | PlainMessage<BandwidthRequest> | undefined): boolean {
    return proto3.util.equals(BandwidthRequest, a, b);
  }
}

/**
 * DockerRequest: ephemeral container workload.
 *
 * @generated from message iogrid.workloads.v1.DockerRequest
 */
export class DockerRequest extends Message<DockerRequest> {
  /**
   * Image reference, including digest if the customer pinned it
   * (e.g. "ghcr.io/example/scraper@sha256:abc..."). Plain tags accepted
   * but digest is recommended for reproducibility.
   *
   * @generated from field: string image = 1;
   */
  image = "";

  /**
   * Container command and args (overrides image's CMD).
   *
   * @generated from field: repeated string command = 2;
   */
  command: string[] = [];

  /**
   * Environment variables passed to the container.
   *
   * @generated from field: map<string, string> env = 3;
   */
  env: { [key: string]: string } = {};

  /**
   * Per-job hard wall-clock budget.
   *
   * @generated from field: google.protobuf.Duration timeout = 4;
   */
  timeout?: Duration;

  /**
   * Required vCPU / RAM. Dispatcher won't pick providers below these.
   *
   * @generated from field: uint32 min_cpu_cores = 5;
   */
  minCpuCores = 0;

  /**
   * @generated from field: uint64 min_memory_mib = 6;
   */
  minMemoryMib = protoInt64.zero;

  /**
   * Optional GPU minimum (vRAM MiB). 0 = "no GPU required".
   *
   * @generated from field: uint64 min_gpu_memory_mib = 7;
   */
  minGpuMemoryMib = protoInt64.zero;

  constructor(data?: PartialMessage<DockerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.workloads.v1.DockerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "image", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "command", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "env", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 4, name: "timeout", kind: "message", T: Duration },
    { no: 5, name: "min_cpu_cores", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 6, name: "min_memory_mib", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 7, name: "min_gpu_memory_mib", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DockerRequest {
    return new DockerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DockerRequest {
    return new DockerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DockerRequest {
    return new DockerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DockerRequest | PlainMessage<DockerRequest> | undefined, b: DockerRequest | PlainMessage<DockerRequest> | undefined): boolean {
    return proto3.util.equals(DockerRequest, a, b);
  }
}

/**
 * IosBuildRequest: macOS / iOS CI job.
 *
 * Two source modes are supported and the daemon picks whichever is set:
 *   1. git-based (preferred) — the VM `git clone`s `repo_url` and checks out
 *      `git_ref`, then runs `build_command`. This is what the Tart driver
 *      (daemon/crates/workload-ios) actually executes today.
 *   2. tarball-based (legacy) — the VM mounts the source tarball uploaded to
 *      `source_tarball_s3_key` and runs `build_commands[]`.
 * Submissions must set EITHER `repo_url` OR `source_tarball_s3_key`.
 *
 * @generated from message iogrid.workloads.v1.IosBuildRequest
 */
export class IosBuildRequest extends Message<IosBuildRequest> {
  /**
   * S3 object key for the uploaded source tarball (legacy tarball mode).
   *
   * @generated from field: string source_tarball_s3_key = 1;
   */
  sourceTarballS3Key = "";

  /**
   * Tart image slug (e.g. "ghcr.io/cirruslabs/macos-sequoia-xcode:latest").
   *
   * @generated from field: string tart_image = 2;
   */
  tartImage = "";

  /**
   * Shell command(s) executed inside the VM (legacy tarball mode).
   *
   * @generated from field: repeated string build_commands = 3;
   */
  buildCommands: string[] = [];

  /**
   * Where build artifacts should be uploaded after success.
   *
   * @generated from field: string artifact_s3_bucket = 4;
   */
  artifactS3Bucket = "";

  /**
   * @generated from field: string artifact_s3_prefix = 5;
   */
  artifactS3Prefix = "";

  /**
   * --- git-based dispatch (preferred, drives the Tart driver) -------------
   * Customer git repo URL the VM should `git clone`.
   *
   * @generated from field: string repo_url = 6;
   */
  repoUrl = "";

  /**
   * Branch or commit SHA to check out.
   *
   * @generated from field: string git_ref = 7;
   */
  gitRef = "";

  /**
   * Single shell/`xcodebuild` command run after clone+checkout. The customer
   * is responsible for any signing-disable flags.
   *
   * @generated from field: string build_command = 8;
   */
  buildCommand = "";

  /**
   * Pre-signed PUT URL for artifact upload after a successful build.
   *
   * @generated from field: string upload_url = 9;
   */
  uploadUrl = "";

  /**
   * Path inside the VM holding the produced `.ipa` / `.xcarchive`. Empty
   * means the daemon default (`/Users/admin/build/output.ipa`).
   *
   * @generated from field: string artifact_guest_path = 10;
   */
  artifactGuestPath = "";

  /**
   * VM CPU cores (daemon clamps to >=1).
   *
   * @generated from field: uint32 cpu = 11;
   */
  cpu = 0;

  /**
   * VM memory in MiB (daemon clamps to >=2048).
   *
   * @generated from field: uint32 memory_mib = 12;
   */
  memoryMib = 0;

  /**
   * How long to poll `tart ip` before giving up on VM boot (seconds).
   *
   * @generated from field: uint32 boot_timeout_secs = 13;
   */
  bootTimeoutSecs = 0;

  constructor(data?: PartialMessage<IosBuildRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.workloads.v1.IosBuildRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "source_tarball_s3_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "tart_image", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "build_commands", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "artifact_s3_bucket", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "artifact_s3_prefix", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "repo_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "git_ref", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "build_command", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "upload_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "artifact_guest_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "cpu", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 12, name: "memory_mib", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 13, name: "boot_timeout_secs", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IosBuildRequest {
    return new IosBuildRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IosBuildRequest {
    return new IosBuildRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IosBuildRequest {
    return new IosBuildRequest().fromJsonString(jsonString, options);
  }

  static equals(a: IosBuildRequest | PlainMessage<IosBuildRequest> | undefined, b: IosBuildRequest | PlainMessage<IosBuildRequest> | undefined): boolean {
    return proto3.util.equals(IosBuildRequest, a, b);
  }
}

/**
 * GpuRequest: compute-heavy GPU workload (CUDA, MLX, ROCm).
 *
 * @generated from message iogrid.workloads.v1.GpuRequest
 */
export class GpuRequest extends Message<GpuRequest> {
  /**
   * @generated from field: string image = 1;
   */
  image = "";

  /**
   * @generated from field: repeated string command = 2;
   */
  command: string[] = [];

  /**
   * @generated from field: map<string, string> env = 3;
   */
  env: { [key: string]: string } = {};

  /**
   * @generated from field: google.protobuf.Duration timeout = 4;
   */
  timeout?: Duration;

  /**
   * vRAM minimum the workload needs.
   *
   * @generated from field: uint64 min_vram_mib = 5;
   */
  minVramMib = protoInt64.zero;

  /**
   * Allowed GPU vendors (empty = any).
   *
   * @generated from field: repeated string allowed_vendors = 6;
   */
  allowedVendors: string[] = [];

  constructor(data?: PartialMessage<GpuRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.workloads.v1.GpuRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "image", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "command", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "env", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 4, name: "timeout", kind: "message", T: Duration },
    { no: 5, name: "min_vram_mib", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 6, name: "allowed_vendors", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GpuRequest {
    return new GpuRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GpuRequest {
    return new GpuRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GpuRequest {
    return new GpuRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GpuRequest | PlainMessage<GpuRequest> | undefined, b: GpuRequest | PlainMessage<GpuRequest> | undefined): boolean {
    return proto3.util.equals(GpuRequest, a, b);
  }
}

/**
 * Workload is the customer submission envelope. Exactly ONE of the
 * payload oneofs is set.
 *
 * @generated from message iogrid.workloads.v1.Workload
 */
export class Workload extends Message<Workload> {
  /**
   * @generated from field: iogrid.common.v1.UUID id = 1;
   */
  id?: UUID;

  /**
   * Owning customer/workspace.
   *
   * @generated from field: iogrid.common.v1.UUID workspace_id = 2;
   */
  workspaceId?: UUID;

  /**
   * @generated from field: iogrid.common.v1.UUID submitted_by_user_id = 3;
   */
  submittedByUserId?: UUID;

  /**
   * @generated from field: iogrid.common.v1.WorkloadType type = 4;
   */
  type = WorkloadType.UNSPECIFIED;

  /**
   * @generated from field: iogrid.workloads.v1.WorkloadPriority priority = 5;
   */
  priority = WorkloadPriority.UNSPECIFIED;

  /**
   * Latest known status (mirrors WorkloadStatus, see dispatch.proto).
   *
   * @generated from field: string status = 6;
   */
  status = "";

  /**
   * @generated from field: google.protobuf.Timestamp submitted_at = 7;
   */
  submittedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp started_at = 8;
   */
  startedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp finished_at = 9;
   */
  finishedAt?: Timestamp;

  /**
   * Free-form labels for customer-side bookkeeping. NEVER used for
   * routing; just propagated back in audit logs and metering.
   *
   * @generated from field: map<string, string> labels = 10;
   */
  labels: { [key: string]: string } = {};

  /**
   * Exactly one of the typed payloads.
   *
   * @generated from oneof iogrid.workloads.v1.Workload.payload
   */
  payload: {
    /**
     * @generated from field: iogrid.workloads.v1.BandwidthRequest bandwidth = 20;
     */
    value: BandwidthRequest;
    case: "bandwidth";
  } | {
    /**
     * @generated from field: iogrid.workloads.v1.DockerRequest docker = 21;
     */
    value: DockerRequest;
    case: "docker";
  } | {
    /**
     * @generated from field: iogrid.workloads.v1.IosBuildRequest ios_build = 22;
     */
    value: IosBuildRequest;
    case: "iosBuild";
  } | {
    /**
     * @generated from field: iogrid.workloads.v1.GpuRequest gpu = 23;
     */
    value: GpuRequest;
    case: "gpu";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<Workload>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.workloads.v1.Workload";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: UUID },
    { no: 2, name: "workspace_id", kind: "message", T: UUID },
    { no: 3, name: "submitted_by_user_id", kind: "message", T: UUID },
    { no: 4, name: "type", kind: "enum", T: proto3.getEnumType(WorkloadType) },
    { no: 5, name: "priority", kind: "enum", T: proto3.getEnumType(WorkloadPriority) },
    { no: 6, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "submitted_at", kind: "message", T: Timestamp },
    { no: 8, name: "started_at", kind: "message", T: Timestamp },
    { no: 9, name: "finished_at", kind: "message", T: Timestamp },
    { no: 10, name: "labels", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 20, name: "bandwidth", kind: "message", T: BandwidthRequest, oneof: "payload" },
    { no: 21, name: "docker", kind: "message", T: DockerRequest, oneof: "payload" },
    { no: 22, name: "ios_build", kind: "message", T: IosBuildRequest, oneof: "payload" },
    { no: 23, name: "gpu", kind: "message", T: GpuRequest, oneof: "payload" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Workload {
    return new Workload().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Workload {
    return new Workload().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Workload {
    return new Workload().fromJsonString(jsonString, options);
  }

  static equals(a: Workload | PlainMessage<Workload> | undefined, b: Workload | PlainMessage<Workload> | undefined): boolean {
    return proto3.util.equals(Workload, a, b);
  }
}

/**
 * WorkloadResult is the customer-facing terminal state of a workload.
 *
 * @generated from message iogrid.workloads.v1.WorkloadResult
 */
export class WorkloadResult extends Message<WorkloadResult> {
  /**
   * @generated from field: iogrid.common.v1.UUID workload_id = 1;
   */
  workloadId?: UUID;

  /**
   * Terminal status: "succeeded", "failed", "timed_out", "cancelled".
   *
   * @generated from field: string terminal_status = 2;
   */
  terminalStatus = "";

  /**
   * Provider exit code (0 on success), where applicable.
   *
   * @generated from field: int32 exit_code = 3;
   */
  exitCode = 0;

  /**
   * For Docker/GPU: S3 key holding stdout+stderr (capped at 10 MiB).
   *
   * @generated from field: string logs_s3_key = 4;
   */
  logsS3Key = "";

  /**
   * For Bandwidth: bytes transferred + summary URL.
   *
   * @generated from field: uint64 bytes_in = 5;
   */
  bytesIn = protoInt64.zero;

  /**
   * @generated from field: uint64 bytes_out = 6;
   */
  bytesOut = protoInt64.zero;

  /**
   * For iOS build: list of produced artifact S3 keys.
   *
   * @generated from field: repeated string artifact_s3_keys = 7;
   */
  artifactS3Keys: string[] = [];

  /**
   * Final billable amount (denominated in micros).
   *
   * @generated from field: iogrid.common.v1.Money cost = 8;
   */
  cost?: Money;

  /**
   * @generated from field: google.protobuf.Timestamp completed_at = 9;
   */
  completedAt?: Timestamp;

  constructor(data?: PartialMessage<WorkloadResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.workloads.v1.WorkloadResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workload_id", kind: "message", T: UUID },
    { no: 2, name: "terminal_status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "exit_code", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "logs_s3_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "bytes_in", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 6, name: "bytes_out", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 7, name: "artifact_s3_keys", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 8, name: "cost", kind: "message", T: Money },
    { no: 9, name: "completed_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WorkloadResult {
    return new WorkloadResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WorkloadResult {
    return new WorkloadResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WorkloadResult {
    return new WorkloadResult().fromJsonString(jsonString, options);
  }

  static equals(a: WorkloadResult | PlainMessage<WorkloadResult> | undefined, b: WorkloadResult | PlainMessage<WorkloadResult> | undefined): boolean {
    return proto3.util.equals(WorkloadResult, a, b);
  }
}

/**
 * @generated from message iogrid.workloads.v1.SubmitWorkloadRequest
 */
export class SubmitWorkloadRequest extends Message<SubmitWorkloadRequest> {
  /**
   * @generated from field: iogrid.workloads.v1.Workload workload = 1;
   */
  workload?: Workload;

  constructor(data?: PartialMessage<SubmitWorkloadRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.workloads.v1.SubmitWorkloadRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workload", kind: "message", T: Workload },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubmitWorkloadRequest {
    return new SubmitWorkloadRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubmitWorkloadRequest {
    return new SubmitWorkloadRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubmitWorkloadRequest {
    return new SubmitWorkloadRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SubmitWorkloadRequest | PlainMessage<SubmitWorkloadRequest> | undefined, b: SubmitWorkloadRequest | PlainMessage<SubmitWorkloadRequest> | undefined): boolean {
    return proto3.util.equals(SubmitWorkloadRequest, a, b);
  }
}

/**
 * @generated from message iogrid.workloads.v1.SubmitWorkloadResponse
 */
export class SubmitWorkloadResponse extends Message<SubmitWorkloadResponse> {
  /**
   * The persisted workload (with id assigned + submitted_at filled).
   *
   * @generated from field: iogrid.workloads.v1.Workload workload = 1;
   */
  workload?: Workload;

  constructor(data?: PartialMessage<SubmitWorkloadResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.workloads.v1.SubmitWorkloadResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workload", kind: "message", T: Workload },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubmitWorkloadResponse {
    return new SubmitWorkloadResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubmitWorkloadResponse {
    return new SubmitWorkloadResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubmitWorkloadResponse {
    return new SubmitWorkloadResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SubmitWorkloadResponse | PlainMessage<SubmitWorkloadResponse> | undefined, b: SubmitWorkloadResponse | PlainMessage<SubmitWorkloadResponse> | undefined): boolean {
    return proto3.util.equals(SubmitWorkloadResponse, a, b);
  }
}

/**
 * @generated from message iogrid.workloads.v1.GetWorkloadRequest
 */
export class GetWorkloadRequest extends Message<GetWorkloadRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID id = 1;
   */
  id?: UUID;

  constructor(data?: PartialMessage<GetWorkloadRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.workloads.v1.GetWorkloadRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: UUID },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetWorkloadRequest {
    return new GetWorkloadRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetWorkloadRequest {
    return new GetWorkloadRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetWorkloadRequest {
    return new GetWorkloadRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetWorkloadRequest | PlainMessage<GetWorkloadRequest> | undefined, b: GetWorkloadRequest | PlainMessage<GetWorkloadRequest> | undefined): boolean {
    return proto3.util.equals(GetWorkloadRequest, a, b);
  }
}

/**
 * @generated from message iogrid.workloads.v1.GetWorkloadResponse
 */
export class GetWorkloadResponse extends Message<GetWorkloadResponse> {
  /**
   * @generated from field: iogrid.workloads.v1.Workload workload = 1;
   */
  workload?: Workload;

  /**
   * Set once workload reaches a terminal state.
   *
   * @generated from field: iogrid.workloads.v1.WorkloadResult result = 2;
   */
  result?: WorkloadResult;

  constructor(data?: PartialMessage<GetWorkloadResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.workloads.v1.GetWorkloadResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workload", kind: "message", T: Workload },
    { no: 2, name: "result", kind: "message", T: WorkloadResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetWorkloadResponse {
    return new GetWorkloadResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetWorkloadResponse {
    return new GetWorkloadResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetWorkloadResponse {
    return new GetWorkloadResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetWorkloadResponse | PlainMessage<GetWorkloadResponse> | undefined, b: GetWorkloadResponse | PlainMessage<GetWorkloadResponse> | undefined): boolean {
    return proto3.util.equals(GetWorkloadResponse, a, b);
  }
}

/**
 * @generated from message iogrid.workloads.v1.ListWorkloadsRequest
 */
export class ListWorkloadsRequest extends Message<ListWorkloadsRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID workspace_id = 1;
   */
  workspaceId?: UUID;

  /**
   * @generated from field: iogrid.common.v1.PageRequest page = 2;
   */
  page?: PageRequest;

  /**
   * Optional filters.
   *
   * @generated from field: iogrid.common.v1.WorkloadType type_filter = 3;
   */
  typeFilter = WorkloadType.UNSPECIFIED;

  /**
   * @generated from field: string status_filter = 4;
   */
  statusFilter = "";

  /**
   * @generated from field: iogrid.common.v1.TimeWindow submitted_window = 5;
   */
  submittedWindow?: TimeWindow;

  constructor(data?: PartialMessage<ListWorkloadsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.workloads.v1.ListWorkloadsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workspace_id", kind: "message", T: UUID },
    { no: 2, name: "page", kind: "message", T: PageRequest },
    { no: 3, name: "type_filter", kind: "enum", T: proto3.getEnumType(WorkloadType) },
    { no: 4, name: "status_filter", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "submitted_window", kind: "message", T: TimeWindow },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListWorkloadsRequest {
    return new ListWorkloadsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListWorkloadsRequest {
    return new ListWorkloadsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListWorkloadsRequest {
    return new ListWorkloadsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListWorkloadsRequest | PlainMessage<ListWorkloadsRequest> | undefined, b: ListWorkloadsRequest | PlainMessage<ListWorkloadsRequest> | undefined): boolean {
    return proto3.util.equals(ListWorkloadsRequest, a, b);
  }
}

/**
 * @generated from message iogrid.workloads.v1.ListWorkloadsResponse
 */
export class ListWorkloadsResponse extends Message<ListWorkloadsResponse> {
  /**
   * @generated from field: repeated iogrid.workloads.v1.Workload workloads = 1;
   */
  workloads: Workload[] = [];

  /**
   * @generated from field: iogrid.common.v1.PageResponse page = 2;
   */
  page?: PageResponse;

  constructor(data?: PartialMessage<ListWorkloadsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.workloads.v1.ListWorkloadsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workloads", kind: "message", T: Workload, repeated: true },
    { no: 2, name: "page", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListWorkloadsResponse {
    return new ListWorkloadsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListWorkloadsResponse {
    return new ListWorkloadsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListWorkloadsResponse {
    return new ListWorkloadsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListWorkloadsResponse | PlainMessage<ListWorkloadsResponse> | undefined, b: ListWorkloadsResponse | PlainMessage<ListWorkloadsResponse> | undefined): boolean {
    return proto3.util.equals(ListWorkloadsResponse, a, b);
  }
}

/**
 * @generated from message iogrid.workloads.v1.CancelWorkloadRequest
 */
export class CancelWorkloadRequest extends Message<CancelWorkloadRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID id = 1;
   */
  id?: UUID;

  /**
   * Optional reason captured in audit.
   *
   * @generated from field: string reason = 2;
   */
  reason = "";

  constructor(data?: PartialMessage<CancelWorkloadRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.workloads.v1.CancelWorkloadRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: UUID },
    { no: 2, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelWorkloadRequest {
    return new CancelWorkloadRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelWorkloadRequest {
    return new CancelWorkloadRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelWorkloadRequest {
    return new CancelWorkloadRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CancelWorkloadRequest | PlainMessage<CancelWorkloadRequest> | undefined, b: CancelWorkloadRequest | PlainMessage<CancelWorkloadRequest> | undefined): boolean {
    return proto3.util.equals(CancelWorkloadRequest, a, b);
  }
}

/**
 * @generated from message iogrid.workloads.v1.CancelWorkloadResponse
 */
export class CancelWorkloadResponse extends Message<CancelWorkloadResponse> {
  /**
   * @generated from field: iogrid.workloads.v1.Workload workload = 1;
   */
  workload?: Workload;

  constructor(data?: PartialMessage<CancelWorkloadResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.workloads.v1.CancelWorkloadResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workload", kind: "message", T: Workload },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelWorkloadResponse {
    return new CancelWorkloadResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelWorkloadResponse {
    return new CancelWorkloadResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelWorkloadResponse {
    return new CancelWorkloadResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CancelWorkloadResponse | PlainMessage<CancelWorkloadResponse> | undefined, b: CancelWorkloadResponse | PlainMessage<CancelWorkloadResponse> | undefined): boolean {
    return proto3.util.equals(CancelWorkloadResponse, a, b);
  }
}

/**
 * @generated from message iogrid.workloads.v1.StreamWorkloadEventsRequest
 */
export class StreamWorkloadEventsRequest extends Message<StreamWorkloadEventsRequest> {
  /**
   * @generated from field: iogrid.common.v1.UUID id = 1;
   */
  id?: UUID;

  constructor(data?: PartialMessage<StreamWorkloadEventsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.workloads.v1.StreamWorkloadEventsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: UUID },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamWorkloadEventsRequest {
    return new StreamWorkloadEventsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamWorkloadEventsRequest {
    return new StreamWorkloadEventsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamWorkloadEventsRequest {
    return new StreamWorkloadEventsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StreamWorkloadEventsRequest | PlainMessage<StreamWorkloadEventsRequest> | undefined, b: StreamWorkloadEventsRequest | PlainMessage<StreamWorkloadEventsRequest> | undefined): boolean {
    return proto3.util.equals(StreamWorkloadEventsRequest, a, b);
  }
}

/**
 * Streamed per-event update — minimal payload; clients re-fetch the
 * full Workload via GetWorkload when they need details.
 *
 * @generated from message iogrid.workloads.v1.WorkloadEvent
 */
export class WorkloadEvent extends Message<WorkloadEvent> {
  /**
   * @generated from field: iogrid.common.v1.UUID workload_id = 1;
   */
  workloadId?: UUID;

  /**
   * @generated from field: string new_status = 2;
   */
  newStatus = "";

  /**
   * @generated from field: google.protobuf.Timestamp occurred_at = 3;
   */
  occurredAt?: Timestamp;

  /**
   * Free-form note (e.g. "dispatched to provider sha-prefix abc123").
   *
   * @generated from field: string note = 4;
   */
  note = "";

  constructor(data?: PartialMessage<WorkloadEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "iogrid.workloads.v1.WorkloadEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workload_id", kind: "message", T: UUID },
    { no: 2, name: "new_status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "occurred_at", kind: "message", T: Timestamp },
    { no: 4, name: "note", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WorkloadEvent {
    return new WorkloadEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WorkloadEvent {
    return new WorkloadEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WorkloadEvent {
    return new WorkloadEvent().fromJsonString(jsonString, options);
  }

  static equals(a: WorkloadEvent | PlainMessage<WorkloadEvent> | undefined, b: WorkloadEvent | PlainMessage<WorkloadEvent> | undefined): boolean {
    return proto3.util.equals(WorkloadEvent, a, b);
  }
}

