apiVersion: v1
kind: Service
metadata:
  name: updates
  namespace: iogrid
  labels:
    app.kubernetes.io/name: updates
    app.kubernetes.io/part-of: iogrid
    app.kubernetes.io/component: updates
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: updates
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
