{{- range $name, $svc := .Values.services }}
{{- $cfg := include "iogrid.svcConfig" (dict "Values" $.Values "svcName" $name "svcCfg" $svc) | fromYaml }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iogrid.fullname" (dict "Release" $.Release "svcName" $name) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "iogrid.labels" (dict "Release" $.Release "svcName" $name) | nindent 4 }}
spec:
  type: {{ $cfg.service.type }}
  ports:
    - name: http
      port: {{ $cfg.service.port }}
      targetPort: {{ $cfg.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "iogrid.selectorLabels" (dict "Release" $.Release "svcName" $name) | nindent 4 }}
{{- end }}
