// Customer API keys + validation.
//
// API keys are the credential customers present to the proxy-gateway
// (SOCKS5 RFC 1929 password / HTTP CONNECT Proxy-Authorization) and to
// the build-gateway (Authorization: Bearer). billing-svc is the source
// of truth: keys are scoped to a workspace, carry a subscription tier
// (which gates rate-limit ceilings + allowed_categories), and may be
// individually revoked without affecting the workspace.
//
// proxy-gateway + build-gateway call ValidateApiKey on every connection
// (cached locally for ~5 minutes — see proxy-gateway internal/auth).
// Mint/list/revoke calls are routed via gateway-bff after bearer-auth
// against the BFF session.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: iogrid/billing/v1/api_keys.proto

package billingv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/iogrid/iogrid/coordinator/internal/pb/iogrid/billing/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ApiKeyServiceName is the fully-qualified name of the ApiKeyService service.
	ApiKeyServiceName = "iogrid.billing.v1.ApiKeyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ApiKeyServiceCreateApiKeyProcedure is the fully-qualified name of the ApiKeyService's
	// CreateApiKey RPC.
	ApiKeyServiceCreateApiKeyProcedure = "/iogrid.billing.v1.ApiKeyService/CreateApiKey"
	// ApiKeyServiceListApiKeysProcedure is the fully-qualified name of the ApiKeyService's ListApiKeys
	// RPC.
	ApiKeyServiceListApiKeysProcedure = "/iogrid.billing.v1.ApiKeyService/ListApiKeys"
	// ApiKeyServiceRevokeApiKeyProcedure is the fully-qualified name of the ApiKeyService's
	// RevokeApiKey RPC.
	ApiKeyServiceRevokeApiKeyProcedure = "/iogrid.billing.v1.ApiKeyService/RevokeApiKey"
	// ApiKeyServiceValidateApiKeyProcedure is the fully-qualified name of the ApiKeyService's
	// ValidateApiKey RPC.
	ApiKeyServiceValidateApiKeyProcedure = "/iogrid.billing.v1.ApiKeyService/ValidateApiKey"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	apiKeyServiceServiceDescriptor              = v1.File_iogrid_billing_v1_api_keys_proto.Services().ByName("ApiKeyService")
	apiKeyServiceCreateApiKeyMethodDescriptor   = apiKeyServiceServiceDescriptor.Methods().ByName("CreateApiKey")
	apiKeyServiceListApiKeysMethodDescriptor    = apiKeyServiceServiceDescriptor.Methods().ByName("ListApiKeys")
	apiKeyServiceRevokeApiKeyMethodDescriptor   = apiKeyServiceServiceDescriptor.Methods().ByName("RevokeApiKey")
	apiKeyServiceValidateApiKeyMethodDescriptor = apiKeyServiceServiceDescriptor.Methods().ByName("ValidateApiKey")
)

// ApiKeyServiceClient is a client for the iogrid.billing.v1.ApiKeyService service.
type ApiKeyServiceClient interface {
	CreateApiKey(context.Context, *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error)
	ListApiKeys(context.Context, *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error)
	RevokeApiKey(context.Context, *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error)
	ValidateApiKey(context.Context, *connect.Request[v1.ValidateApiKeyRequest]) (*connect.Response[v1.ValidateApiKeyResponse], error)
}

// NewApiKeyServiceClient constructs a client for the iogrid.billing.v1.ApiKeyService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewApiKeyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ApiKeyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &apiKeyServiceClient{
		createApiKey: connect.NewClient[v1.CreateApiKeyRequest, v1.CreateApiKeyResponse](
			httpClient,
			baseURL+ApiKeyServiceCreateApiKeyProcedure,
			connect.WithSchema(apiKeyServiceCreateApiKeyMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listApiKeys: connect.NewClient[v1.ListApiKeysRequest, v1.ListApiKeysResponse](
			httpClient,
			baseURL+ApiKeyServiceListApiKeysProcedure,
			connect.WithSchema(apiKeyServiceListApiKeysMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		revokeApiKey: connect.NewClient[v1.RevokeApiKeyRequest, v1.RevokeApiKeyResponse](
			httpClient,
			baseURL+ApiKeyServiceRevokeApiKeyProcedure,
			connect.WithSchema(apiKeyServiceRevokeApiKeyMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		validateApiKey: connect.NewClient[v1.ValidateApiKeyRequest, v1.ValidateApiKeyResponse](
			httpClient,
			baseURL+ApiKeyServiceValidateApiKeyProcedure,
			connect.WithSchema(apiKeyServiceValidateApiKeyMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// apiKeyServiceClient implements ApiKeyServiceClient.
type apiKeyServiceClient struct {
	createApiKey   *connect.Client[v1.CreateApiKeyRequest, v1.CreateApiKeyResponse]
	listApiKeys    *connect.Client[v1.ListApiKeysRequest, v1.ListApiKeysResponse]
	revokeApiKey   *connect.Client[v1.RevokeApiKeyRequest, v1.RevokeApiKeyResponse]
	validateApiKey *connect.Client[v1.ValidateApiKeyRequest, v1.ValidateApiKeyResponse]
}

// CreateApiKey calls iogrid.billing.v1.ApiKeyService.CreateApiKey.
func (c *apiKeyServiceClient) CreateApiKey(ctx context.Context, req *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error) {
	return c.createApiKey.CallUnary(ctx, req)
}

// ListApiKeys calls iogrid.billing.v1.ApiKeyService.ListApiKeys.
func (c *apiKeyServiceClient) ListApiKeys(ctx context.Context, req *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error) {
	return c.listApiKeys.CallUnary(ctx, req)
}

// RevokeApiKey calls iogrid.billing.v1.ApiKeyService.RevokeApiKey.
func (c *apiKeyServiceClient) RevokeApiKey(ctx context.Context, req *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error) {
	return c.revokeApiKey.CallUnary(ctx, req)
}

// ValidateApiKey calls iogrid.billing.v1.ApiKeyService.ValidateApiKey.
func (c *apiKeyServiceClient) ValidateApiKey(ctx context.Context, req *connect.Request[v1.ValidateApiKeyRequest]) (*connect.Response[v1.ValidateApiKeyResponse], error) {
	return c.validateApiKey.CallUnary(ctx, req)
}

// ApiKeyServiceHandler is an implementation of the iogrid.billing.v1.ApiKeyService service.
type ApiKeyServiceHandler interface {
	CreateApiKey(context.Context, *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error)
	ListApiKeys(context.Context, *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error)
	RevokeApiKey(context.Context, *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error)
	ValidateApiKey(context.Context, *connect.Request[v1.ValidateApiKeyRequest]) (*connect.Response[v1.ValidateApiKeyResponse], error)
}

// NewApiKeyServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewApiKeyServiceHandler(svc ApiKeyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	apiKeyServiceCreateApiKeyHandler := connect.NewUnaryHandler(
		ApiKeyServiceCreateApiKeyProcedure,
		svc.CreateApiKey,
		connect.WithSchema(apiKeyServiceCreateApiKeyMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	apiKeyServiceListApiKeysHandler := connect.NewUnaryHandler(
		ApiKeyServiceListApiKeysProcedure,
		svc.ListApiKeys,
		connect.WithSchema(apiKeyServiceListApiKeysMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	apiKeyServiceRevokeApiKeyHandler := connect.NewUnaryHandler(
		ApiKeyServiceRevokeApiKeyProcedure,
		svc.RevokeApiKey,
		connect.WithSchema(apiKeyServiceRevokeApiKeyMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	apiKeyServiceValidateApiKeyHandler := connect.NewUnaryHandler(
		ApiKeyServiceValidateApiKeyProcedure,
		svc.ValidateApiKey,
		connect.WithSchema(apiKeyServiceValidateApiKeyMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/iogrid.billing.v1.ApiKeyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ApiKeyServiceCreateApiKeyProcedure:
			apiKeyServiceCreateApiKeyHandler.ServeHTTP(w, r)
		case ApiKeyServiceListApiKeysProcedure:
			apiKeyServiceListApiKeysHandler.ServeHTTP(w, r)
		case ApiKeyServiceRevokeApiKeyProcedure:
			apiKeyServiceRevokeApiKeyHandler.ServeHTTP(w, r)
		case ApiKeyServiceValidateApiKeyProcedure:
			apiKeyServiceValidateApiKeyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedApiKeyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedApiKeyServiceHandler struct{}

func (UnimplementedApiKeyServiceHandler) CreateApiKey(context.Context, *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.billing.v1.ApiKeyService.CreateApiKey is not implemented"))
}

func (UnimplementedApiKeyServiceHandler) ListApiKeys(context.Context, *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.billing.v1.ApiKeyService.ListApiKeys is not implemented"))
}

func (UnimplementedApiKeyServiceHandler) RevokeApiKey(context.Context, *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.billing.v1.ApiKeyService.RevokeApiKey is not implemented"))
}

func (UnimplementedApiKeyServiceHandler) ValidateApiKey(context.Context, *connect.Request[v1.ValidateApiKeyRequest]) (*connect.Response[v1.ValidateApiKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.billing.v1.ApiKeyService.ValidateApiKey is not implemented"))
}
