// Provider earnings summary + payout-method preference for the
// /provide/earnings page. Lives in billing-svc (NOT providers-svc)
// because the canonical money state — including pending-payout balance,
// lifetime totals, and the user's preferred off-ramp variant — is owned
// by billing-svc's bounded context.
//
// providers-svc keeps its own GetEarningsSummary (proto: providers/v1/
// dashboard.proto) for the transparency feed: that one breaks revenue
// down by workload_type for a single TimeWindow. THIS service answers
// the headline-card shape the management UI shows (totals + rolling
// windows + payout method).

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: iogrid/billing/v1/earnings.proto

package billingv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/iogrid/iogrid/coordinator/internal/pb/iogrid/billing/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EarningsServiceName is the fully-qualified name of the EarningsService service.
	EarningsServiceName = "iogrid.billing.v1.EarningsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EarningsServiceGetEarningsSummaryProcedure is the fully-qualified name of the EarningsService's
	// GetEarningsSummary RPC.
	EarningsServiceGetEarningsSummaryProcedure = "/iogrid.billing.v1.EarningsService/GetEarningsSummary"
	// EarningsServiceGetPayoutMethodProcedure is the fully-qualified name of the EarningsService's
	// GetPayoutMethod RPC.
	EarningsServiceGetPayoutMethodProcedure = "/iogrid.billing.v1.EarningsService/GetPayoutMethod"
	// EarningsServiceSetPayoutMethodProcedure is the fully-qualified name of the EarningsService's
	// SetPayoutMethod RPC.
	EarningsServiceSetPayoutMethodProcedure = "/iogrid.billing.v1.EarningsService/SetPayoutMethod"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	earningsServiceServiceDescriptor                  = v1.File_iogrid_billing_v1_earnings_proto.Services().ByName("EarningsService")
	earningsServiceGetEarningsSummaryMethodDescriptor = earningsServiceServiceDescriptor.Methods().ByName("GetEarningsSummary")
	earningsServiceGetPayoutMethodMethodDescriptor    = earningsServiceServiceDescriptor.Methods().ByName("GetPayoutMethod")
	earningsServiceSetPayoutMethodMethodDescriptor    = earningsServiceServiceDescriptor.Methods().ByName("SetPayoutMethod")
)

// EarningsServiceClient is a client for the iogrid.billing.v1.EarningsService service.
type EarningsServiceClient interface {
	GetEarningsSummary(context.Context, *connect.Request[v1.GetEarningsSummaryRequest]) (*connect.Response[v1.GetEarningsSummaryResponse], error)
	GetPayoutMethod(context.Context, *connect.Request[v1.GetPayoutMethodRequest]) (*connect.Response[v1.GetPayoutMethodResponse], error)
	SetPayoutMethod(context.Context, *connect.Request[v1.SetPayoutMethodRequest]) (*connect.Response[v1.SetPayoutMethodResponse], error)
}

// NewEarningsServiceClient constructs a client for the iogrid.billing.v1.EarningsService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEarningsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EarningsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &earningsServiceClient{
		getEarningsSummary: connect.NewClient[v1.GetEarningsSummaryRequest, v1.GetEarningsSummaryResponse](
			httpClient,
			baseURL+EarningsServiceGetEarningsSummaryProcedure,
			connect.WithSchema(earningsServiceGetEarningsSummaryMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getPayoutMethod: connect.NewClient[v1.GetPayoutMethodRequest, v1.GetPayoutMethodResponse](
			httpClient,
			baseURL+EarningsServiceGetPayoutMethodProcedure,
			connect.WithSchema(earningsServiceGetPayoutMethodMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		setPayoutMethod: connect.NewClient[v1.SetPayoutMethodRequest, v1.SetPayoutMethodResponse](
			httpClient,
			baseURL+EarningsServiceSetPayoutMethodProcedure,
			connect.WithSchema(earningsServiceSetPayoutMethodMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// earningsServiceClient implements EarningsServiceClient.
type earningsServiceClient struct {
	getEarningsSummary *connect.Client[v1.GetEarningsSummaryRequest, v1.GetEarningsSummaryResponse]
	getPayoutMethod    *connect.Client[v1.GetPayoutMethodRequest, v1.GetPayoutMethodResponse]
	setPayoutMethod    *connect.Client[v1.SetPayoutMethodRequest, v1.SetPayoutMethodResponse]
}

// GetEarningsSummary calls iogrid.billing.v1.EarningsService.GetEarningsSummary.
func (c *earningsServiceClient) GetEarningsSummary(ctx context.Context, req *connect.Request[v1.GetEarningsSummaryRequest]) (*connect.Response[v1.GetEarningsSummaryResponse], error) {
	return c.getEarningsSummary.CallUnary(ctx, req)
}

// GetPayoutMethod calls iogrid.billing.v1.EarningsService.GetPayoutMethod.
func (c *earningsServiceClient) GetPayoutMethod(ctx context.Context, req *connect.Request[v1.GetPayoutMethodRequest]) (*connect.Response[v1.GetPayoutMethodResponse], error) {
	return c.getPayoutMethod.CallUnary(ctx, req)
}

// SetPayoutMethod calls iogrid.billing.v1.EarningsService.SetPayoutMethod.
func (c *earningsServiceClient) SetPayoutMethod(ctx context.Context, req *connect.Request[v1.SetPayoutMethodRequest]) (*connect.Response[v1.SetPayoutMethodResponse], error) {
	return c.setPayoutMethod.CallUnary(ctx, req)
}

// EarningsServiceHandler is an implementation of the iogrid.billing.v1.EarningsService service.
type EarningsServiceHandler interface {
	GetEarningsSummary(context.Context, *connect.Request[v1.GetEarningsSummaryRequest]) (*connect.Response[v1.GetEarningsSummaryResponse], error)
	GetPayoutMethod(context.Context, *connect.Request[v1.GetPayoutMethodRequest]) (*connect.Response[v1.GetPayoutMethodResponse], error)
	SetPayoutMethod(context.Context, *connect.Request[v1.SetPayoutMethodRequest]) (*connect.Response[v1.SetPayoutMethodResponse], error)
}

// NewEarningsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEarningsServiceHandler(svc EarningsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	earningsServiceGetEarningsSummaryHandler := connect.NewUnaryHandler(
		EarningsServiceGetEarningsSummaryProcedure,
		svc.GetEarningsSummary,
		connect.WithSchema(earningsServiceGetEarningsSummaryMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	earningsServiceGetPayoutMethodHandler := connect.NewUnaryHandler(
		EarningsServiceGetPayoutMethodProcedure,
		svc.GetPayoutMethod,
		connect.WithSchema(earningsServiceGetPayoutMethodMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	earningsServiceSetPayoutMethodHandler := connect.NewUnaryHandler(
		EarningsServiceSetPayoutMethodProcedure,
		svc.SetPayoutMethod,
		connect.WithSchema(earningsServiceSetPayoutMethodMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/iogrid.billing.v1.EarningsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EarningsServiceGetEarningsSummaryProcedure:
			earningsServiceGetEarningsSummaryHandler.ServeHTTP(w, r)
		case EarningsServiceGetPayoutMethodProcedure:
			earningsServiceGetPayoutMethodHandler.ServeHTTP(w, r)
		case EarningsServiceSetPayoutMethodProcedure:
			earningsServiceSetPayoutMethodHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEarningsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEarningsServiceHandler struct{}

func (UnimplementedEarningsServiceHandler) GetEarningsSummary(context.Context, *connect.Request[v1.GetEarningsSummaryRequest]) (*connect.Response[v1.GetEarningsSummaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.billing.v1.EarningsService.GetEarningsSummary is not implemented"))
}

func (UnimplementedEarningsServiceHandler) GetPayoutMethod(context.Context, *connect.Request[v1.GetPayoutMethodRequest]) (*connect.Response[v1.GetPayoutMethodResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.billing.v1.EarningsService.GetPayoutMethod is not implemented"))
}

func (UnimplementedEarningsServiceHandler) SetPayoutMethod(context.Context, *connect.Request[v1.SetPayoutMethodRequest]) (*connect.Response[v1.SetPayoutMethodResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.billing.v1.EarningsService.SetPayoutMethod is not implemented"))
}
