// Internal coordinator → daemon dispatch protocol. The daemon holds a
// long-lived bidirectional stream open against the coordinator; the
// coordinator pushes WorkloadAssignments down the wire, the daemon pushes
// WorkloadStatusUpdates back.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: iogrid/workloads/v1/dispatch.proto

package workloadsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/iogrid/iogrid/coordinator/internal/pb/iogrid/workloads/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WorkloadDispatchServiceName is the fully-qualified name of the WorkloadDispatchService service.
	WorkloadDispatchServiceName = "iogrid.workloads.v1.WorkloadDispatchService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WorkloadDispatchServiceDispatchProcedure is the fully-qualified name of the
	// WorkloadDispatchService's Dispatch RPC.
	WorkloadDispatchServiceDispatchProcedure = "/iogrid.workloads.v1.WorkloadDispatchService/Dispatch"
	// WorkloadDispatchServiceAckAssignmentProcedure is the fully-qualified name of the
	// WorkloadDispatchService's AckAssignment RPC.
	WorkloadDispatchServiceAckAssignmentProcedure = "/iogrid.workloads.v1.WorkloadDispatchService/AckAssignment"
	// WorkloadDispatchServiceGetAssignmentProcedure is the fully-qualified name of the
	// WorkloadDispatchService's GetAssignment RPC.
	WorkloadDispatchServiceGetAssignmentProcedure = "/iogrid.workloads.v1.WorkloadDispatchService/GetAssignment"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	workloadDispatchServiceServiceDescriptor             = v1.File_iogrid_workloads_v1_dispatch_proto.Services().ByName("WorkloadDispatchService")
	workloadDispatchServiceDispatchMethodDescriptor      = workloadDispatchServiceServiceDescriptor.Methods().ByName("Dispatch")
	workloadDispatchServiceAckAssignmentMethodDescriptor = workloadDispatchServiceServiceDescriptor.Methods().ByName("AckAssignment")
	workloadDispatchServiceGetAssignmentMethodDescriptor = workloadDispatchServiceServiceDescriptor.Methods().ByName("GetAssignment")
)

// WorkloadDispatchServiceClient is a client for the iogrid.workloads.v1.WorkloadDispatchService
// service.
type WorkloadDispatchServiceClient interface {
	// Long-lived bidi stream — the canonical path for production traffic.
	Dispatch(context.Context) *connect.BidiStreamForClient[v1.DispatchFrame, v1.DispatchFrame]
	// Side-band acknowledgement used for replay/debug paths only.
	AckAssignment(context.Context, *connect.Request[v1.AckAssignmentRequest]) (*connect.Response[v1.AckAssignmentResponse], error)
	// Inspect a single attempt — used by ops tooling.
	GetAssignment(context.Context, *connect.Request[v1.GetAssignmentRequest]) (*connect.Response[v1.GetAssignmentResponse], error)
}

// NewWorkloadDispatchServiceClient constructs a client for the
// iogrid.workloads.v1.WorkloadDispatchService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkloadDispatchServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkloadDispatchServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &workloadDispatchServiceClient{
		dispatch: connect.NewClient[v1.DispatchFrame, v1.DispatchFrame](
			httpClient,
			baseURL+WorkloadDispatchServiceDispatchProcedure,
			connect.WithSchema(workloadDispatchServiceDispatchMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		ackAssignment: connect.NewClient[v1.AckAssignmentRequest, v1.AckAssignmentResponse](
			httpClient,
			baseURL+WorkloadDispatchServiceAckAssignmentProcedure,
			connect.WithSchema(workloadDispatchServiceAckAssignmentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getAssignment: connect.NewClient[v1.GetAssignmentRequest, v1.GetAssignmentResponse](
			httpClient,
			baseURL+WorkloadDispatchServiceGetAssignmentProcedure,
			connect.WithSchema(workloadDispatchServiceGetAssignmentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// workloadDispatchServiceClient implements WorkloadDispatchServiceClient.
type workloadDispatchServiceClient struct {
	dispatch      *connect.Client[v1.DispatchFrame, v1.DispatchFrame]
	ackAssignment *connect.Client[v1.AckAssignmentRequest, v1.AckAssignmentResponse]
	getAssignment *connect.Client[v1.GetAssignmentRequest, v1.GetAssignmentResponse]
}

// Dispatch calls iogrid.workloads.v1.WorkloadDispatchService.Dispatch.
func (c *workloadDispatchServiceClient) Dispatch(ctx context.Context) *connect.BidiStreamForClient[v1.DispatchFrame, v1.DispatchFrame] {
	return c.dispatch.CallBidiStream(ctx)
}

// AckAssignment calls iogrid.workloads.v1.WorkloadDispatchService.AckAssignment.
func (c *workloadDispatchServiceClient) AckAssignment(ctx context.Context, req *connect.Request[v1.AckAssignmentRequest]) (*connect.Response[v1.AckAssignmentResponse], error) {
	return c.ackAssignment.CallUnary(ctx, req)
}

// GetAssignment calls iogrid.workloads.v1.WorkloadDispatchService.GetAssignment.
func (c *workloadDispatchServiceClient) GetAssignment(ctx context.Context, req *connect.Request[v1.GetAssignmentRequest]) (*connect.Response[v1.GetAssignmentResponse], error) {
	return c.getAssignment.CallUnary(ctx, req)
}

// WorkloadDispatchServiceHandler is an implementation of the
// iogrid.workloads.v1.WorkloadDispatchService service.
type WorkloadDispatchServiceHandler interface {
	// Long-lived bidi stream — the canonical path for production traffic.
	Dispatch(context.Context, *connect.BidiStream[v1.DispatchFrame, v1.DispatchFrame]) error
	// Side-band acknowledgement used for replay/debug paths only.
	AckAssignment(context.Context, *connect.Request[v1.AckAssignmentRequest]) (*connect.Response[v1.AckAssignmentResponse], error)
	// Inspect a single attempt — used by ops tooling.
	GetAssignment(context.Context, *connect.Request[v1.GetAssignmentRequest]) (*connect.Response[v1.GetAssignmentResponse], error)
}

// NewWorkloadDispatchServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkloadDispatchServiceHandler(svc WorkloadDispatchServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workloadDispatchServiceDispatchHandler := connect.NewBidiStreamHandler(
		WorkloadDispatchServiceDispatchProcedure,
		svc.Dispatch,
		connect.WithSchema(workloadDispatchServiceDispatchMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	workloadDispatchServiceAckAssignmentHandler := connect.NewUnaryHandler(
		WorkloadDispatchServiceAckAssignmentProcedure,
		svc.AckAssignment,
		connect.WithSchema(workloadDispatchServiceAckAssignmentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	workloadDispatchServiceGetAssignmentHandler := connect.NewUnaryHandler(
		WorkloadDispatchServiceGetAssignmentProcedure,
		svc.GetAssignment,
		connect.WithSchema(workloadDispatchServiceGetAssignmentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/iogrid.workloads.v1.WorkloadDispatchService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkloadDispatchServiceDispatchProcedure:
			workloadDispatchServiceDispatchHandler.ServeHTTP(w, r)
		case WorkloadDispatchServiceAckAssignmentProcedure:
			workloadDispatchServiceAckAssignmentHandler.ServeHTTP(w, r)
		case WorkloadDispatchServiceGetAssignmentProcedure:
			workloadDispatchServiceGetAssignmentHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkloadDispatchServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkloadDispatchServiceHandler struct{}

func (UnimplementedWorkloadDispatchServiceHandler) Dispatch(context.Context, *connect.BidiStream[v1.DispatchFrame, v1.DispatchFrame]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.workloads.v1.WorkloadDispatchService.Dispatch is not implemented"))
}

func (UnimplementedWorkloadDispatchServiceHandler) AckAssignment(context.Context, *connect.Request[v1.AckAssignmentRequest]) (*connect.Response[v1.AckAssignmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.workloads.v1.WorkloadDispatchService.AckAssignment is not implemented"))
}

func (UnimplementedWorkloadDispatchServiceHandler) GetAssignment(context.Context, *connect.Request[v1.GetAssignmentRequest]) (*connect.Response[v1.GetAssignmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.workloads.v1.WorkloadDispatchService.GetAssignment is not implemented"))
}
