// Customer-facing workload submission. Customers POST workloads here
// (via gateway-bff); workloads-svc validates, queues, then hands off to
// the dispatcher (see dispatch.proto).

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: iogrid/workloads/v1/submit.proto

package workloadsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/iogrid/iogrid/coordinator/internal/pb/iogrid/workloads/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WorkloadSubmissionServiceName is the fully-qualified name of the WorkloadSubmissionService
	// service.
	WorkloadSubmissionServiceName = "iogrid.workloads.v1.WorkloadSubmissionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WorkloadSubmissionServiceSubmitWorkloadProcedure is the fully-qualified name of the
	// WorkloadSubmissionService's SubmitWorkload RPC.
	WorkloadSubmissionServiceSubmitWorkloadProcedure = "/iogrid.workloads.v1.WorkloadSubmissionService/SubmitWorkload"
	// WorkloadSubmissionServiceGetWorkloadProcedure is the fully-qualified name of the
	// WorkloadSubmissionService's GetWorkload RPC.
	WorkloadSubmissionServiceGetWorkloadProcedure = "/iogrid.workloads.v1.WorkloadSubmissionService/GetWorkload"
	// WorkloadSubmissionServiceListWorkloadsProcedure is the fully-qualified name of the
	// WorkloadSubmissionService's ListWorkloads RPC.
	WorkloadSubmissionServiceListWorkloadsProcedure = "/iogrid.workloads.v1.WorkloadSubmissionService/ListWorkloads"
	// WorkloadSubmissionServiceCancelWorkloadProcedure is the fully-qualified name of the
	// WorkloadSubmissionService's CancelWorkload RPC.
	WorkloadSubmissionServiceCancelWorkloadProcedure = "/iogrid.workloads.v1.WorkloadSubmissionService/CancelWorkload"
	// WorkloadSubmissionServiceStreamWorkloadEventsProcedure is the fully-qualified name of the
	// WorkloadSubmissionService's StreamWorkloadEvents RPC.
	WorkloadSubmissionServiceStreamWorkloadEventsProcedure = "/iogrid.workloads.v1.WorkloadSubmissionService/StreamWorkloadEvents"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	workloadSubmissionServiceServiceDescriptor                    = v1.File_iogrid_workloads_v1_submit_proto.Services().ByName("WorkloadSubmissionService")
	workloadSubmissionServiceSubmitWorkloadMethodDescriptor       = workloadSubmissionServiceServiceDescriptor.Methods().ByName("SubmitWorkload")
	workloadSubmissionServiceGetWorkloadMethodDescriptor          = workloadSubmissionServiceServiceDescriptor.Methods().ByName("GetWorkload")
	workloadSubmissionServiceListWorkloadsMethodDescriptor        = workloadSubmissionServiceServiceDescriptor.Methods().ByName("ListWorkloads")
	workloadSubmissionServiceCancelWorkloadMethodDescriptor       = workloadSubmissionServiceServiceDescriptor.Methods().ByName("CancelWorkload")
	workloadSubmissionServiceStreamWorkloadEventsMethodDescriptor = workloadSubmissionServiceServiceDescriptor.Methods().ByName("StreamWorkloadEvents")
)

// WorkloadSubmissionServiceClient is a client for the iogrid.workloads.v1.WorkloadSubmissionService
// service.
type WorkloadSubmissionServiceClient interface {
	SubmitWorkload(context.Context, *connect.Request[v1.SubmitWorkloadRequest]) (*connect.Response[v1.SubmitWorkloadResponse], error)
	GetWorkload(context.Context, *connect.Request[v1.GetWorkloadRequest]) (*connect.Response[v1.GetWorkloadResponse], error)
	ListWorkloads(context.Context, *connect.Request[v1.ListWorkloadsRequest]) (*connect.Response[v1.ListWorkloadsResponse], error)
	CancelWorkload(context.Context, *connect.Request[v1.CancelWorkloadRequest]) (*connect.Response[v1.CancelWorkloadResponse], error)
	StreamWorkloadEvents(context.Context, *connect.Request[v1.StreamWorkloadEventsRequest]) (*connect.ServerStreamForClient[v1.WorkloadEvent], error)
}

// NewWorkloadSubmissionServiceClient constructs a client for the
// iogrid.workloads.v1.WorkloadSubmissionService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkloadSubmissionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkloadSubmissionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &workloadSubmissionServiceClient{
		submitWorkload: connect.NewClient[v1.SubmitWorkloadRequest, v1.SubmitWorkloadResponse](
			httpClient,
			baseURL+WorkloadSubmissionServiceSubmitWorkloadProcedure,
			connect.WithSchema(workloadSubmissionServiceSubmitWorkloadMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getWorkload: connect.NewClient[v1.GetWorkloadRequest, v1.GetWorkloadResponse](
			httpClient,
			baseURL+WorkloadSubmissionServiceGetWorkloadProcedure,
			connect.WithSchema(workloadSubmissionServiceGetWorkloadMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listWorkloads: connect.NewClient[v1.ListWorkloadsRequest, v1.ListWorkloadsResponse](
			httpClient,
			baseURL+WorkloadSubmissionServiceListWorkloadsProcedure,
			connect.WithSchema(workloadSubmissionServiceListWorkloadsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		cancelWorkload: connect.NewClient[v1.CancelWorkloadRequest, v1.CancelWorkloadResponse](
			httpClient,
			baseURL+WorkloadSubmissionServiceCancelWorkloadProcedure,
			connect.WithSchema(workloadSubmissionServiceCancelWorkloadMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		streamWorkloadEvents: connect.NewClient[v1.StreamWorkloadEventsRequest, v1.WorkloadEvent](
			httpClient,
			baseURL+WorkloadSubmissionServiceStreamWorkloadEventsProcedure,
			connect.WithSchema(workloadSubmissionServiceStreamWorkloadEventsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// workloadSubmissionServiceClient implements WorkloadSubmissionServiceClient.
type workloadSubmissionServiceClient struct {
	submitWorkload       *connect.Client[v1.SubmitWorkloadRequest, v1.SubmitWorkloadResponse]
	getWorkload          *connect.Client[v1.GetWorkloadRequest, v1.GetWorkloadResponse]
	listWorkloads        *connect.Client[v1.ListWorkloadsRequest, v1.ListWorkloadsResponse]
	cancelWorkload       *connect.Client[v1.CancelWorkloadRequest, v1.CancelWorkloadResponse]
	streamWorkloadEvents *connect.Client[v1.StreamWorkloadEventsRequest, v1.WorkloadEvent]
}

// SubmitWorkload calls iogrid.workloads.v1.WorkloadSubmissionService.SubmitWorkload.
func (c *workloadSubmissionServiceClient) SubmitWorkload(ctx context.Context, req *connect.Request[v1.SubmitWorkloadRequest]) (*connect.Response[v1.SubmitWorkloadResponse], error) {
	return c.submitWorkload.CallUnary(ctx, req)
}

// GetWorkload calls iogrid.workloads.v1.WorkloadSubmissionService.GetWorkload.
func (c *workloadSubmissionServiceClient) GetWorkload(ctx context.Context, req *connect.Request[v1.GetWorkloadRequest]) (*connect.Response[v1.GetWorkloadResponse], error) {
	return c.getWorkload.CallUnary(ctx, req)
}

// ListWorkloads calls iogrid.workloads.v1.WorkloadSubmissionService.ListWorkloads.
func (c *workloadSubmissionServiceClient) ListWorkloads(ctx context.Context, req *connect.Request[v1.ListWorkloadsRequest]) (*connect.Response[v1.ListWorkloadsResponse], error) {
	return c.listWorkloads.CallUnary(ctx, req)
}

// CancelWorkload calls iogrid.workloads.v1.WorkloadSubmissionService.CancelWorkload.
func (c *workloadSubmissionServiceClient) CancelWorkload(ctx context.Context, req *connect.Request[v1.CancelWorkloadRequest]) (*connect.Response[v1.CancelWorkloadResponse], error) {
	return c.cancelWorkload.CallUnary(ctx, req)
}

// StreamWorkloadEvents calls iogrid.workloads.v1.WorkloadSubmissionService.StreamWorkloadEvents.
func (c *workloadSubmissionServiceClient) StreamWorkloadEvents(ctx context.Context, req *connect.Request[v1.StreamWorkloadEventsRequest]) (*connect.ServerStreamForClient[v1.WorkloadEvent], error) {
	return c.streamWorkloadEvents.CallServerStream(ctx, req)
}

// WorkloadSubmissionServiceHandler is an implementation of the
// iogrid.workloads.v1.WorkloadSubmissionService service.
type WorkloadSubmissionServiceHandler interface {
	SubmitWorkload(context.Context, *connect.Request[v1.SubmitWorkloadRequest]) (*connect.Response[v1.SubmitWorkloadResponse], error)
	GetWorkload(context.Context, *connect.Request[v1.GetWorkloadRequest]) (*connect.Response[v1.GetWorkloadResponse], error)
	ListWorkloads(context.Context, *connect.Request[v1.ListWorkloadsRequest]) (*connect.Response[v1.ListWorkloadsResponse], error)
	CancelWorkload(context.Context, *connect.Request[v1.CancelWorkloadRequest]) (*connect.Response[v1.CancelWorkloadResponse], error)
	StreamWorkloadEvents(context.Context, *connect.Request[v1.StreamWorkloadEventsRequest], *connect.ServerStream[v1.WorkloadEvent]) error
}

// NewWorkloadSubmissionServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkloadSubmissionServiceHandler(svc WorkloadSubmissionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workloadSubmissionServiceSubmitWorkloadHandler := connect.NewUnaryHandler(
		WorkloadSubmissionServiceSubmitWorkloadProcedure,
		svc.SubmitWorkload,
		connect.WithSchema(workloadSubmissionServiceSubmitWorkloadMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	workloadSubmissionServiceGetWorkloadHandler := connect.NewUnaryHandler(
		WorkloadSubmissionServiceGetWorkloadProcedure,
		svc.GetWorkload,
		connect.WithSchema(workloadSubmissionServiceGetWorkloadMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	workloadSubmissionServiceListWorkloadsHandler := connect.NewUnaryHandler(
		WorkloadSubmissionServiceListWorkloadsProcedure,
		svc.ListWorkloads,
		connect.WithSchema(workloadSubmissionServiceListWorkloadsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	workloadSubmissionServiceCancelWorkloadHandler := connect.NewUnaryHandler(
		WorkloadSubmissionServiceCancelWorkloadProcedure,
		svc.CancelWorkload,
		connect.WithSchema(workloadSubmissionServiceCancelWorkloadMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	workloadSubmissionServiceStreamWorkloadEventsHandler := connect.NewServerStreamHandler(
		WorkloadSubmissionServiceStreamWorkloadEventsProcedure,
		svc.StreamWorkloadEvents,
		connect.WithSchema(workloadSubmissionServiceStreamWorkloadEventsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/iogrid.workloads.v1.WorkloadSubmissionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkloadSubmissionServiceSubmitWorkloadProcedure:
			workloadSubmissionServiceSubmitWorkloadHandler.ServeHTTP(w, r)
		case WorkloadSubmissionServiceGetWorkloadProcedure:
			workloadSubmissionServiceGetWorkloadHandler.ServeHTTP(w, r)
		case WorkloadSubmissionServiceListWorkloadsProcedure:
			workloadSubmissionServiceListWorkloadsHandler.ServeHTTP(w, r)
		case WorkloadSubmissionServiceCancelWorkloadProcedure:
			workloadSubmissionServiceCancelWorkloadHandler.ServeHTTP(w, r)
		case WorkloadSubmissionServiceStreamWorkloadEventsProcedure:
			workloadSubmissionServiceStreamWorkloadEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkloadSubmissionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkloadSubmissionServiceHandler struct{}

func (UnimplementedWorkloadSubmissionServiceHandler) SubmitWorkload(context.Context, *connect.Request[v1.SubmitWorkloadRequest]) (*connect.Response[v1.SubmitWorkloadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.workloads.v1.WorkloadSubmissionService.SubmitWorkload is not implemented"))
}

func (UnimplementedWorkloadSubmissionServiceHandler) GetWorkload(context.Context, *connect.Request[v1.GetWorkloadRequest]) (*connect.Response[v1.GetWorkloadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.workloads.v1.WorkloadSubmissionService.GetWorkload is not implemented"))
}

func (UnimplementedWorkloadSubmissionServiceHandler) ListWorkloads(context.Context, *connect.Request[v1.ListWorkloadsRequest]) (*connect.Response[v1.ListWorkloadsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.workloads.v1.WorkloadSubmissionService.ListWorkloads is not implemented"))
}

func (UnimplementedWorkloadSubmissionServiceHandler) CancelWorkload(context.Context, *connect.Request[v1.CancelWorkloadRequest]) (*connect.Response[v1.CancelWorkloadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.workloads.v1.WorkloadSubmissionService.CancelWorkload is not implemented"))
}

func (UnimplementedWorkloadSubmissionServiceHandler) StreamWorkloadEvents(context.Context, *connect.Request[v1.StreamWorkloadEventsRequest], *connect.ServerStream[v1.WorkloadEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("iogrid.workloads.v1.WorkloadSubmissionService.StreamWorkloadEvents is not implemented"))
}
