/// <reference types="react/canary" />
/// <reference types="@testing-library/jest-dom" />

// `@testing-library/jest-dom` augments Vitest's `Assertion<HTMLElement>`
// with the DOM matchers `toBeInTheDocument`, `toHaveTextContent`, etc.
// Test files import the runtime side via `import
// "@testing-library/jest-dom/vitest";` — that wires the matchers — but
// the TYPE augmentation only takes effect when this triple-slash
// reference is in scope of `tsc`. Without it, every test file using a
// jest-dom matcher fails typecheck with TS2339 'Property
// toBeInTheDocument does not exist on type Assertion<HTMLElement>'.
//
// Putting the reference here (instead of in each test file) means new
// tests don't need to remember to add it.

// React canary types — required so `<form action={serverAction}>` accepts
// a function value (Server Action) and not just a string URL. These types
// live behind a canary opt-in even on the stable @types/react@18.3.x line
// because they correspond to React features that landed in 18.3 but were
// kept under the canary channel for the type stubs.
//
// Without this reference, tsc reports TS2322 on every <form> bound to a
// signed-in / submit handler in the App Router (SignInPanel, future
// settings forms, etc.):
//
//   Type '(data: FormData) => Promise<void>' is not assignable to type 'string'.
//
// We put the triple-slash reference in a dedicated `types/global.d.ts`
// (not `next-env.d.ts`) because `next-env.d.ts` is .gitignored and
// regenerated by Next.js on every build.
//
// This file is intentionally a SCRIPT (no top-level imports / exports)
// so the triple-slash reference is program-wide. The vitest Assertion
// augmentation lives in `vitest-matchers.d.ts` next to it as a MODULE
// file; both contribute to the compilation unit via tsconfig's
// `**/*.ts` include glob.
