/// <reference types="react/canary" />

// React canary types — required so `<form action={serverAction}>` accepts
// a function value (Server Action) and not just a string URL. These types
// live behind a canary opt-in even on the stable @types/react@18.3.x line
// because they correspond to React features that landed in 18.3 but were
// kept under the canary channel for the type stubs.
//
// Without this reference, tsc reports TS2322 on every <form> bound to a
// signed-in / submit handler in the App Router (SignInPanel, future
// settings forms, etc.):
//
//   Type '(data: FormData) => Promise<void>' is not assignable to type 'string'.
//
// We put the triple-slash reference in a dedicated `types/global.d.ts`
// (not `next-env.d.ts`) because `next-env.d.ts` is .gitignored and
// regenerated by Next.js on every build.
export {};
