apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: iogrid
  labels:
    app.kubernetes.io/name: admin
    app.kubernetes.io/part-of: iogrid
    app.kubernetes.io/component: frontend
automountServiceAccountToken: true
