apiVersion: v1
kind: Service
metadata:
  name: billing-svc
  namespace: iogrid
  labels:
    app.kubernetes.io/name: billing-svc
    app.kubernetes.io/part-of: iogrid
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: billing-svc
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
