apiVersion: v1
kind: Service
metadata:
  name: build-gateway
  namespace: iogrid
  labels:
    app.kubernetes.io/name: build-gateway
    app.kubernetes.io/part-of: iogrid
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: build-gateway
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
