apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: iogrid
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: iogrid
    app.kubernetes.io/component: frontend
automountServiceAccountToken: true
